import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, History, KeyRound, RefreshCw, ShieldAlert, WalletCards } from 'lucide-react'
import { useAuth } from '../context/AuthContext'
import { api } from '../lib/api'


type WalletRow={id:number;address:string;verified:boolean;is_interactive_signer:boolean;is_reward_destination:boolean;wallet_client_type:string;wallet_type:string}
type SecurityEvent={id:number;event_type:string;route_group:string;detail:string;created_at:string}
type HistoryResponse={user_id:number;role:string;permissions:string[];events:SecurityEvent[]}

function when(value:string){const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleString()}
function short(value:string,front=12,back=8){return value.length<=front+back+3?value:`${value.slice(0,front)}…${value.slice(-back)}`}

export default function AdminRecoveryPanel({userId,username,privyUserId,wallets,onChanged}:{userId:number;username:string;privyUserId:string|null;wallets:WalletRow[];onChanged:()=>Promise<void>}){
 const {user}=useAuth();const canManage=user?.role==='ADMIN'
 const [history,setHistory]=useState<HistoryResponse|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [message,setMessage]=useState('')
 const [newDid,setNewDid]=useState('');const [loginReason,setLoginReason]=useState('');const [walletId,setWalletId]=useState('');const [replacementId,setReplacementId]=useState('');const [walletReason,setWalletReason]=useState('');const [busy,setBusy]=useState('')
 const load=async()=>{setLoading(true);setError('');try{setHistory(await api<HistoryResponse>(`/admin/recovery/users/${userId}/history`))}catch(e:any){setError(e.message||'Could not load security history')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[userId])
 const selectedWallet=wallets.find(w=>String(w.id)===walletId)||null
 const replacementWallets=wallets.filter(w=>w.verified&&(!selectedWallet||w.id!==selectedWallet.id))
 const events=history?.events||[]
 const loginEvents=useMemo(()=>events.filter(e=>/(LOGIN|LOGOUT|REGISTER|PRIVY)/.test(e.event_type)).slice(0,20),[events])
 const walletEvents=useMemo(()=>events.filter(e=>/(WALLET|PAYOUT|REWARD_DESTINATION|CONNECTED_LOGIN)/.test(e.event_type)).slice(0,20),[events])
 const suspiciousEvents=useMemo(()=>events.filter(e=>!loginEvents.includes(e)&&!walletEvents.includes(e)).slice(0,20),[events,loginEvents,walletEvents])
 const replaceLogin=async()=>{if(!canManage||newDid.trim().length<8||loginReason.trim().length<8)return;setBusy('login');setError('');setMessage('');try{await api(`/admin/recovery/users/${userId}/connected-login/replace`,{method:'POST',body:JSON.stringify({new_privy_user_id:newDid.trim(),reason:loginReason.trim()})});setMessage('Connected login replaced. Existing sessions were revoked and X/Google links were cleared for signed Privy resync on the next login.');setNewDid('');setLoginReason('');await onChanged();await load()}catch(e:any){setError(e.message||'Could not replace connected login')}finally{setBusy('')}}
 const retireWallet=async()=>{if(!canManage||!walletId||walletReason.trim().length<8)return;setBusy('wallet');setError('');setMessage('');try{await api(`/admin/recovery/users/${userId}/wallets/${walletId}/retire`,{method:'POST',body:JSON.stringify({replacement_wallet_id:replacementId?Number(replacementId):null,reason:walletReason.trim()})});setMessage(replacementId?'Compromised wallet retired and the already-verified replacement inherited the affected role(s). All user sessions were revoked.':'Compromised wallet retired. All user sessions were revoked; the user must verify/select a new signer or reward destination where required.');setWalletId('');setReplacementId('');setWalletReason('');await onChanged();await load()}catch(e:any){setError(e.message||'Could not retire wallet linkage')}finally{setBusy('')}}
 const eventList=(rows:SecurityEvent[],empty:string)=>rows.length?<div className="admin-security-history-list">{rows.map(row=><div className="admin-security-history-row" key={row.id}><div><strong>{row.event_type.replaceAll('_',' ')}</strong><small>{row.route_group} • {when(row.created_at)}</small></div><p>{row.detail}</p></div>)}</div>:<div className="admin-muted">{empty}</div>
 return <>
  <section className="panel admin-recovery-panel"><div className="panel-head"><div><span><ShieldAlert/> ACCOUNT RECOVERY</span><h2>Support-led recovery controls</h2></div><span className="admin-state-chip under-review">AUDITED</span></div><p>Recovery is deliberately manual. NuBagz can revoke its own sessions and replace NuBagz identity/wallet linkages after an identity investigation; it cannot recover blockchain private keys or move funds from a compromised wallet.</p>{message&&<div className="form-note">{message}</div>}{error&&<div className="admin-inline-error">{error}</div>}
   {!canManage&&<div className="admin-recovery-readonly"><KeyRound/><div><strong>Read-only support access</strong><p>Your role can investigate history, but only a privileged Admin can perform recovery mutations.</p></div></div>}
   {canManage&&<div className="admin-recovery-grid"><div className="admin-recovery-card"><span>CONNECTED LOGIN</span><strong>Replace canonical Privy login</strong><p>Use only after Support has verified the replacement Privy DID. This revokes all active sessions and clears the old X/Google provider rows so the replacement identity can resync them from a signed Privy token.</p><small>Current: {privyUserId?short(privyUserId,18,10):'No canonical Privy binding'}</small><label>Replacement Privy DID<input value={newDid} onChange={e=>setNewDid(e.target.value.trim())} placeholder="did:privy:..."/></label><label>Mandatory audit reason<textarea value={loginReason} onChange={e=>setLoginReason(e.target.value)} maxLength={2000} placeholder="Identity investigation and why the old connected login must be replaced."/></label><button className="btn admin-danger-btn" disabled={busy!==''||newDid.length<8||loginReason.trim().length<8} onClick={()=>void replaceLogin()}>{busy==='login'?'Replacing…':'Replace connected login'}</button></div>
    <div className="admin-recovery-card"><span>COMPROMISED WALLET</span><strong>Retire wallet linkage</strong><p>Retires the selected wallet from NuBagz. If it was the signer or reward destination, choose another already-verified wallet to inherit that role or leave replacement blank and require the user to verify a new wallet.</p><label>Wallet to retire<select value={walletId} onChange={e=>{setWalletId(e.target.value);setReplacementId('')}}><option value="">Select wallet…</option>{wallets.map(w=><option key={w.id} value={w.id}>{short(w.address,12,8)}{w.is_interactive_signer?' • signer':''}{w.is_reward_destination?' • rewards':''}</option>)}</select></label><label>Already-verified replacement (optional)<select value={replacementId} onChange={e=>setReplacementId(e.target.value)} disabled={!walletId}><option value="">Require user to verify/select replacement</option>{replacementWallets.map(w=><option key={w.id} value={w.id}>{short(w.address,12,8)} • {w.wallet_client_type}</option>)}</select></label><label>Mandatory audit reason<textarea value={walletReason} onChange={e=>setWalletReason(e.target.value)} maxLength={2000} placeholder="Compromise evidence and recovery context."/></label><button className="btn admin-danger-btn" disabled={busy!==''||!walletId||walletReason.trim().length<8} onClick={()=>void retireWallet()}>{busy==='wallet'?'Retiring…':'Retire compromised wallet'}</button></div></div>}
  </section>
  <section className="panel"><div className="panel-head"><div><span><History/> LOGIN & SECURITY HISTORY</span><h2>Authentication and wallet-role timeline</h2></div><button className="mini-action" disabled={loading} onClick={()=>void load()}><RefreshCw/> Refresh</button></div><p>These are append-only security observations. Network identifiers remain privacy-preserving keyed signals; raw IP addresses are not exposed here.</p><div className="admin-history-columns"><div><h3>Login history</h3>{eventList(loginEvents,'No login security events recorded yet.')}</div><div><h3>Wallet & identity changes</h3>{eventList(walletEvents,'No wallet or connected-login changes recorded yet.')}</div></div><h3 className="admin-subsection-title"><AlertTriangle/> Suspicious / anti-abuse events</h3>{eventList(suspiciousEvents,'No additional suspicious security events recorded.')}</section>
 </>
}
