import { useEffect, useState } from 'react'
import { AlertTriangle, RefreshCw, ShieldCheck } from 'lucide-react'
import { api } from '../lib/api'

type Risk={user_id:number;trust_level:string;risk_score:number;last_evaluated_at:string;signals:{id:number;type:string;severity:string;detail:string}[]}

export default function AccountTrust(){const [risk,setRisk]=useState<Risk|null>(null);const [msg,setMsg]=useState('');const load=()=>api<Risk>('/risk/me').then(setRisk);useEffect(()=>{load()},[]);const refresh=async()=>{try{setRisk(await api<Risk>('/risk/evaluate',{method:'POST'}));setMsg('Trust signals refreshed.')}catch(e:any){setMsg(e.message||'Could not refresh trust signals')}}
 return <div className="page"><div className="page-head"><div><span className="eyebrow small">ACCOUNT TRUST</span><h1>Earn more by staying <em>human.</em></h1><p>NuBagz protects project reward pools from bots, duplicate accounts and farming rings so genuine users retain access to better opportunities.</p></div><button className="btn primary" onClick={refresh}><RefreshCw/> Re-check</button></div>{msg&&<div className="form-note">{msg}</div>}
 <div className="stats-grid"><div className="stat-card hot"><span><ShieldCheck/>TRUST LEVEL</span><strong>{risk?.trust_level||'—'}</strong><small>Normal • Verified • Review • Restricted</small></div><div className="stat-card"><span><AlertTriangle/>RISK SCORE</span><strong>{risk?.risk_score??'—'}</strong><small>0 is lowest observed risk</small></div><div className="stat-card"><span>OPEN SIGNALS</span><strong>{risk?.signals.length??'—'}</strong><small>Explainable fraud indicators</small></div></div>
 <section className="panel"><div className="panel-head"><div><span>EXPLAINABLE SIGNALS</span><h2>What NuBagz can see</h2></div></div>{risk?.signals.length?risk.signals.map(s=><div className="activity-row" key={s.id}><div><span>{s.severity} • {s.type.replaceAll('_',' ')}</span><strong>{s.detail}</strong></div></div>):<div className="empty-state"><ShieldCheck/><strong>No active fraud signals.</strong><p>NuBagz does not sell this trust data. It is used to protect rewards and marketplace integrity.</p></div>}</section><div className="custody-note"><ShieldCheck/><p><strong>Progressive verification:</strong> higher-value opportunities can require stronger trust. A review flag is not an accusation; it means the account may need additional checks before accessing higher-risk reward inventory.</p></div></div>
}
