import { useEffect, useState } from 'react'
import { AlertTriangle, RefreshCw, ShieldCheck, Smartphone, CircleCheckBig } from 'lucide-react'
import { api } from '../lib/api'

type Signal={id:number;type:string;severity:string;detail:string}
type Risk={user_id:number;trust_level:string;risk_score:number;risk_band:string;can_earn:boolean;last_evaluated_at:string;signals:Signal[];privacy_note:string}

export default function AccountTrust(){const [risk,setRisk]=useState<Risk|null>(null);const [msg,setMsg]=useState('');const load=()=>api<Risk>('/risk/me').then(setRisk);useEffect(()=>{load()},[]);const refresh=async()=>{try{setRisk(await api<Risk>('/risk/evaluate',{method:'POST'}));setMsg('Trust signals refreshed.')}catch(e:any){setMsg(e.message||'Could not refresh trust signals')}}
 const band=risk?.risk_band||'—';const meaning=risk?.trust_level==='RESTRICTED'?'Reward access is paused pending review.':risk?.trust_level==='REVIEW'?'Some higher-risk earning routes may require manual review.':risk?.trust_level==='VERIFIED'?'NuBagz has manually verified this account after review.':'Your account has normal earning access.'
 return <div className="page"><div className="page-head"><div><span className="eyebrow small">ACCOUNT TRUST</span><h1>Earn more by staying <em>human.</em></h1><p>NuBagz protects project-funded reward pools from bots, duplicate accounts and farming rings so genuine users retain access to better opportunities.</p></div><button className="btn primary" onClick={refresh}><RefreshCw/> Re-check</button></div>{msg&&<div className="form-note">{msg}</div>}
 <div className="stats-grid"><div className="stat-card hot"><span><ShieldCheck/>TRUST LEVEL</span><strong>{risk?.trust_level||'—'}</strong><small>{meaning}</small></div><div className="stat-card"><span><AlertTriangle/>RISK SCORE</span><strong>{risk?.risk_score??'—'}</strong><small>{band} observed risk • 0 is lowest</small></div><div className="stat-card"><span>OPEN SIGNALS</span><strong>{risk?.signals.length??'—'}</strong><small>Explainable indicators, not hidden accusations</small></div><div className="stat-card"><span><CircleCheckBig/>EARNING ACCESS</span><strong>{risk?.can_earn?'ACTIVE':'PAUSED'}</strong><small>Restricted accounts cannot claim new rewards</small></div></div>
 <section className="panel"><div className="panel-head"><div><span>EXPLAINABLE SIGNALS</span><h2>What triggered the score</h2></div></div>{risk?.signals.length?risk.signals.map(s=><div className="activity-row" key={s.id}><div><span>{s.severity} • {s.type.replaceAll('_',' ')}</span><strong>{s.detail}</strong></div></div>):<div className="empty-state"><ShieldCheck/><strong>No active fraud signals.</strong><p>That does not guarantee an account is genuine; it means the current rules found no active anomaly.</p></div>}</section>
 <div className="two-col"><div className="custody-note"><Smartphone/><p><strong>Device privacy:</strong> {risk?.privacy_note||'NuBagz uses an app-local random install signal for anti-farming checks.'}</p></div><div className="custody-note"><ShieldCheck/><p><strong>Progressive verification:</strong> a REVIEW status is not an accusation. It means the account may need additional checks before accessing higher-value project inventory. Admin decisions are recorded separately from automated signals.</p></div></div></div>
}
