import { useEffect, useState } from 'react'
import { AlertTriangle, Coins, Layers3, Shield, TrendingUp, Users, WalletCards } from 'lucide-react'
import { api } from '../lib/api'

export default function Admin(){const [o,setO]=useState<any>(null);const [projects,setProjects]=useState<any[]>([]);const [campaigns,setCampaigns]=useState<any[]>([]);const [treasury,setTreasury]=useState<any[]>([]);const [withdrawals,setWithdrawals]=useState<any[]>([]);const [asset,setAsset]=useState('');const [price,setPrice]=useState('');const [priceMsg,setPriceMsg]=useState('')
 const load=()=>Promise.all([api('/admin/overview'),api<any[]>('/admin/projects'),api<any[]>('/admin/campaigns'),api<any[]>('/admin/treasury'),api<any[]>('/admin/withdrawals')]).then(([a,b,c,d,e])=>{setO(a);setProjects(b);setCampaigns(c);setTreasury(d);setWithdrawals(e)});useEffect(()=>{load()},[])
 const decide=async(kind:'projects'|'campaigns',id:number,status:string)=>{await api(`/admin/${kind}/${id}`,{method:'PATCH',body:JSON.stringify({status})});await load()}
 const addPrice=async()=>{setPriceMsg('');try{await api('/prices/snapshot',{method:'POST',body:JSON.stringify({asset:asset.toUpperCase(),price_gbp:Number(price),source:'NUBAGZ_ADMIN'})});setPriceMsg(`Saved ${asset.toUpperCase()} at £${Number(price).toFixed(6)}.`);setAsset('');setPrice('')}catch(e:any){setPriceMsg(e.message||'Could not save price')}}
 return <div className="page"><div className="page-head"><div><span className="eyebrow small">NUBAGZ CONTROL</span><h1>Trust, treasury & <em>market health.</em></h1><p>Administrative controls for project screening, campaign activation and settlement oversight.</p></div></div><div className="stats-grid admin-stats"><div className="stat-card"><span><Users/>USERS</span><strong>{o?.users??'—'}</strong></div><div className="stat-card"><span><Layers3/>LIVE BAGZ</span><strong>{o?.live_campaigns??'—'}</strong></div><div className="stat-card"><span><WalletCards/>WITHDRAWALS</span><strong>{o?.pending_withdrawals??'—'}</strong><small>pending</small></div><div className="stat-card hot"><span><AlertTriangle/>FLAGS</span><strong>{o?.open_flags??'—'}</strong><small>open abuse flags</small></div></div>
 <div className="admin-grid"><section className="panel"><div className="panel-head"><div><span>PROJECT REVIEW</span><h2>Project queue</h2></div></div>{projects.map(p=><div className="admin-row" key={p.id}><div><strong>{p.name}</strong><small>${p.symbol} • {p.chain}</small></div><span className={`status ${p.status.toLowerCase()}`}>{p.status}</span><div className="row-actions">{p.status!=='APPROVED'&&<button onClick={()=>decide('projects',p.id,'APPROVED')}>Approve</button>}<button onClick={()=>decide('projects',p.id,'REJECTED')}>Reject</button></div></div>)}</section><section className="panel"><div className="panel-head"><div><span>CAMPAIGN REVIEW</span><h2>Bag queue</h2></div></div>{campaigns.map(c=><div className="admin-row" key={c.id}><div><strong>{c.title}</strong><small>{Number(c.allocation).toLocaleString()} {c.asset} • funding {c.funding_status||'UNFUNDED'}</small></div><span className={`status ${c.status.toLowerCase()}`}>{c.status}</span><div className="row-actions">{c.status!=='LIVE'&&<button onClick={()=>decide('campaigns',c.id,'LIVE')}>Go live</button>}<button onClick={()=>decide('campaigns',c.id,'SUSPENDED')}>Suspend</button></div></div>)}</section></div>
 <div className="admin-grid"><section className="panel"><div className="panel-head"><div><span><Coins/> PLATFORM TREASURY</span><h2>Accrued reward shares</h2></div></div>{treasury.length?treasury.map(t=><div className="treasury-row" key={t.asset}><strong>{t.asset}</strong><b>{Number(t.amount).toLocaleString(undefined,{maximumFractionDigits:6})}</b></div>):<div className="empty-state">No platform shares have accrued yet.</div>}</section><section className="panel"><div className="panel-head"><div><span><Shield/> SETTLEMENT</span><h2>Withdrawal queue</h2></div></div>{withdrawals.length?withdrawals.map(w=><div className="withdraw-row" key={w.id}><div><strong>{w.amount} {w.asset}</strong><small>{w.chain} • user #{w.user_id}</small></div><span className={`status ${w.status.toLowerCase()}`}>{w.status}</span></div>):<div className="empty-state">No withdrawal requests.</div>}</section></div>
 <section className="panel"><div className="panel-head"><div><span><TrendingUp/> PRICE TRACKING</span><h2>Add GBP price snapshot</h2></div></div><p>Use a trusted market source to record the latest GBP price. Earnings pages never invent a price when none is available.</p><div className="form-grid"><label>Asset symbol<input value={asset} onChange={e=>setAsset(e.target.value)} placeholder="AVAX"/></label><label>GBP price<input type="number" min="0" step="any" value={price} onChange={e=>setPrice(e.target.value)} placeholder="24.50"/></label></div><button className="btn primary" disabled={!asset||!price||Number(price)<=0} onClick={addPrice}>Save price snapshot</button>{priceMsg&&<div className="form-note">{priceMsg}</div>}</section></div>
}
