import { useEffect, useState } from 'react'
import { AlertTriangle, Coins, Fuel, Layers3, Pause, Play, RefreshCw, Shield, TrendingUp, UserRoundCheck, Users, WalletCards } from 'lucide-react'
import { api } from '../lib/api'

type RiskRow={user_id:number;username:string;email:string|null;trust_level:string;risk_score:number;risk_band:string;signals:{id:number;type:string;severity:string;detail:string}[];latest_review:{trust_level:string;note:string;created_at:string}|null}
type AdminCampaign={id:number;title:string;project_id:number;asset:string;allocation:string;required_amount:string;status:string;featured:boolean;funding_status:string;declared_amount:string;verified_amount:string;funding_tx_hash?:string|null}
type GasPolicy={id:number;challenge_id:number;challenge_title:string;campaign_id:number;campaign_title:string;project_id:number;project_name:string;chain:string;native_asset:string;max_native_per_claim:string;max_unique_users?:number|null;max_claims:number;max_claims_per_wallet:number;funded_amount:string;spent_amount:string;remaining_funded_amount:string;executed_claims:number;reserved_claims:number;unique_users:number;funding_reference:string;funding_status:string;status:string}

export default function Admin(){
 const [o,setO]=useState<any>(null);const [projects,setProjects]=useState<any[]>([]);const [campaigns,setCampaigns]=useState<AdminCampaign[]>([]);const [gas,setGas]=useState<GasPolicy[]>([]);const [treasury,setTreasury]=useState<any[]>([]);const [withdrawals,setWithdrawals]=useState<any[]>([]);const [risk,setRisk]=useState<RiskRow[]>([]);const [asset,setAsset]=useState('');const [price,setPrice]=useState('');const [priceMsg,setPriceMsg]=useState('');const [riskMsg,setRiskMsg]=useState('');const [adminMsg,setAdminMsg]=useState('')
 const load=()=>Promise.all([api('/admin/overview'),api<any[]>('/admin/projects'),api<AdminCampaign[]>('/admin/campaigns'),api<GasPolicy[]>('/gas/policies/admin'),api<any[]>('/admin/treasury'),api<any[]>('/admin/withdrawals'),api<RiskRow[]>('/risk/users')]).then(([a,b,c,g,d,e,f])=>{setO(a);setProjects(b);setCampaigns(c);setGas(g);setTreasury(d);setWithdrawals(e);setRisk(f)});useEffect(()=>{void load()},[])
 const moderate=async(kind:'projects'|'campaigns',id:number,status:string)=>{setAdminMsg('');try{await api(`/admin/${kind}/${id}`,{method:'PATCH',body:JSON.stringify({status})});setAdminMsg(`${kind==='projects'?'Project':'Bag'} set to ${status}.`);await load()}catch(e:any){setAdminMsg(e.message||'Moderation action failed')}}
 const verifyReward=async(c:AdminCampaign)=>{const amountRaw=window.prompt(`Verify reward funding for ${c.title}\nRequired: ${c.required_amount} ${c.asset}\nDeclared: ${c.declared_amount} ${c.asset}`,c.declared_amount||c.required_amount);if(amountRaw===null)return;const tx=window.prompt('Verified funding transaction / reference:',c.funding_tx_hash||'');if(tx===null)return;try{const result=await api<{discoverable?:boolean;campaign_status?:string;discoverability_blockers?:string[]}>(`/funding/campaigns/${c.id}/verify`,{method:'POST',body:JSON.stringify({amount:Number(amountRaw),tx_hash:tx||null})});setAdminMsg(result.discoverable?`Reward funding verified for ${c.title}. The Bag is now discoverable in Bag Work.`:`Reward funding verified for ${c.title}. Publication is still blocked by: ${(result.discoverability_blockers||[]).join(', ')||result.campaign_status||'configuration requirements'}.`);await load()}catch(e:any){setAdminMsg(e.message||'Could not verify reward funding')}}
 const verifyGas=async(g:GasPolicy)=>{const amount=window.prompt(`Verify Gas Pass funding for ${g.challenge_title}\nConfigured: ${g.funded_amount} ${g.native_asset}`,g.funded_amount);if(amount===null)return;const ref=window.prompt('Verified gas funding transaction / reference:',g.funding_reference||'');if(ref===null)return;try{await api(`/gas/policies/${g.id}/verify`,{method:'POST',body:JSON.stringify({funded_amount:Number(amount),funding_reference:ref})});setAdminMsg(`Gas Pass funding verified and activated for ${g.challenge_title}.`);await load()}catch(e:any){setAdminMsg(e.message||'Could not verify Gas Pass funding')}}
 const setGasStatus=async(g:GasPolicy,status:'ACTIVE'|'PAUSED')=>{try{await api(`/gas/policies/${g.id}/status`,{method:'POST',body:JSON.stringify({status})});setAdminMsg(`Gas Pass ${status==='ACTIVE'?'resumed':'paused'} for ${g.challenge_title}.`);await load()}catch(e:any){setAdminMsg(e.message||'Could not update Gas Pass')}}
 const addPrice=async()=>{setPriceMsg('');try{await api('/prices/snapshot',{method:'POST',body:JSON.stringify({asset:asset.toUpperCase(),price_gbp:Number(price),source:'NUBAGZ_ADMIN'})});setPriceMsg(`Saved ${asset.toUpperCase()} at £${Number(price).toFixed(6)}.`);setAsset('');setPrice('')}catch(e:any){setPriceMsg(e.message||'Could not save price')}}
 const evaluateAll=async()=>{setRiskMsg('');try{const r=await api<{evaluated:number}>('/risk/admin/evaluate-all',{method:'POST'});setRiskMsg(`Re-evaluated ${r.evaluated} active accounts.`);await load()}catch(e:any){setRiskMsg(e.message||'Could not run anti-farming evaluation')}}
 const review=async(row:RiskRow,trust_level:string)=>{const note=window.prompt(`${trust_level} ${row.username}\nAdd an internal review note:`,row.latest_review?.note||'');if(note===null)return;try{await api(`/risk/users/${row.user_id}/trust`,{method:'POST',body:JSON.stringify({trust_level,note})});setRiskMsg(`${row.username} set to ${trust_level}. Review recorded.`);await load()}catch(e:any){setRiskMsg(e.message||'Could not update trust decision')}}
 return <div className="page"><div className="page-head"><div><span className="eyebrow small">NUBAGZ CONTROL</span><h1>Moderation, trust & <em>market health.</em></h1><p>NuBagz does not approve every project or Bag. Admin intervenes for abuse/risk, independently verifies funding and monitors settlement and sponsored gas.</p></div></div>{adminMsg&&<div className="form-note">{adminMsg}</div>}<div className="stats-grid admin-stats"><div className="stat-card"><span><Users/>LIVE PROJECTS</span><strong>{o?.live_projects??'—'}</strong><small>{o?.suspended_projects??0} suspended</small></div><div className="stat-card"><span><Layers3/>LIVE BAGZ</span><strong>{o?.live_campaigns??'—'}</strong><small>{o?.suspended_campaigns??0} suspended</small></div><div className="stat-card"><span><Fuel/>GAS PASSES</span><strong>{o?.active_gas_passes??'—'}</strong><small>{o?.gas_funding_pending??0} funding checks</small></div><div className="stat-card hot"><span><AlertTriangle/>FLAGS</span><strong>{o?.open_flags??'—'}</strong><small>open abuse signals</small></div></div>
 <section className="panel"><div className="panel-head"><div><span><UserRoundCheck/> ANTI-SYBIL REVIEW</span><h2>Explainable account risk queue</h2></div><button className="mini-action" onClick={()=>void evaluateAll()}><RefreshCw/> Re-evaluate all</button></div><p>Automated signals can move an account to REVIEW, but only an admin can explicitly VERIFY or RESTRICT it. Review decisions and notes are retained.</p>{riskMsg&&<div className="form-note">{riskMsg}</div>}{risk.length?risk.slice(0,20).map(r=><div className="admin-row" key={r.user_id}><div><strong>{r.username}</strong><small>{r.email||`User #${r.user_id}`} • Risk {r.risk_score}/100 • {r.risk_band}</small><small>{r.signals.length?r.signals.map(s=>s.type.replaceAll('_',' ')).join(' • '):'No open signals'}{r.latest_review?.note?` • Last review: ${r.latest_review.note}`:''}</small></div><span className={`status ${r.trust_level.toLowerCase()}`}>{r.trust_level}</span><div className="row-actions"><button onClick={()=>void review(r,'VERIFIED')}>Verify</button><button onClick={()=>void review(r,'NORMAL')}>Normal</button><button onClick={()=>void review(r,'REVIEW')}>Review</button><button onClick={()=>void review(r,'RESTRICTED')}>Restrict</button></div></div>):<div className="empty-state">No account trust profiles yet. Run evaluation to populate the queue.</div>}</section>
 <div className="admin-grid"><section className="panel"><div className="panel-head"><div><span>PROJECT MODERATION</span><h2>Projects</h2></div></div>{projects.length?projects.map(p=><div className="admin-row" key={p.id}><div><strong>{p.name}</strong><small>${p.symbol} • {p.chain} • owner #{p.owner_id}</small></div><span className={`status ${p.status.toLowerCase()}`}>{p.status==='APPROVED'?'LIVE (legacy)':p.status}</span><div className="row-actions">{(p.status==='LIVE'||p.status==='APPROVED')&&<button onClick={()=>void moderate('projects',p.id,'SUSPENDED')}>Suspend</button>}{p.status==='SUSPENDED'&&<button onClick={()=>void moderate('projects',p.id,'LIVE')}>Restore</button>}{p.status!=='ARCHIVED'&&<button onClick={()=>void moderate('projects',p.id,'ARCHIVED')}>Archive</button>}{p.status==='ARCHIVED'&&<button onClick={()=>void moderate('projects',p.id,'LIVE')}>Restore</button>}</div></div>):<div className="empty-state">No projects.</div>}</section><section className="panel"><div className="panel-head"><div><span>BAG MODERATION & FUNDING</span><h2>Bagz</h2></div></div>{campaigns.length?campaigns.map(c=><div className="admin-row" key={c.id}><div><strong>{c.title}</strong><small>{Number(c.allocation).toLocaleString()} {c.asset} • requires {Number(c.required_amount).toLocaleString()} • funding {c.funding_status}</small></div><span className={`status ${c.status.toLowerCase()}`}>{c.status}</span><div className="row-actions">{c.funding_status==='DECLARED'&&<button className="approve" onClick={()=>void verifyReward(c)}>Verify funding</button>}{c.status==='LIVE'&&<><button onClick={()=>void moderate('campaigns',c.id,'PAUSED')}>Pause</button><button onClick={()=>void moderate('campaigns',c.id,'SUSPENDED')}>Suspend</button></>}{c.status==='SUSPENDED'&&<button onClick={()=>void moderate('campaigns',c.id,'LIVE')}>Restore</button>}</div></div>):<div className="empty-state">No Bagz.</div>}</section></div>
 <section className="panel"><div className="panel-head"><div><span><Fuel/> GAS PASS OVERSIGHT</span><h2>Challenge-level sponsored gas</h2></div></div><p>Funding verification only confirms the project has supplied the configured gas inventory; it is not an endorsement of the project or its on-chain action.</p>{gas.length?gas.map(g=><div className="admin-row" key={g.id}><div><strong>{g.challenge_title}</strong><small>{g.project_name} • {g.campaign_title} • {g.chain}</small><small>{g.unique_users}{g.max_unique_users?`/${g.max_unique_users}`:''} users • {g.executed_claims}/{g.max_claims} executed • {g.reserved_claims} reserved • {Number(g.spent_amount).toLocaleString(undefined,{maximumFractionDigits:8})}/{Number(g.funded_amount).toLocaleString(undefined,{maximumFractionDigits:8})} {g.native_asset}</small></div><span className={`status ${g.status.toLowerCase()}`}>{g.funding_status} / {g.status}</span><div className="row-actions">{g.funding_status!=='VERIFIED'&&<button className="approve" onClick={()=>void verifyGas(g)}>Verify funding</button>}{g.status==='ACTIVE'&&<button onClick={()=>void setGasStatus(g,'PAUSED')}><Pause/> Pause</button>}{g.status==='PAUSED'&&<button onClick={()=>void setGasStatus(g,'ACTIVE')}><Play/> Resume</button>}</div></div>):<div className="empty-state"><Fuel/><strong>No challenge-level Gas Passes configured.</strong></div>}</section>
 <div className="admin-grid"><section className="panel"><div className="panel-head"><div><span><Coins/> PLATFORM TREASURY</span><h2>Accrued reward shares</h2></div></div>{treasury.length?treasury.map(t=><div className="treasury-row" key={t.asset}><strong>{t.asset}</strong><b>{Number(t.amount).toLocaleString(undefined,{maximumFractionDigits:6})}</b></div>):<div className="empty-state">No platform shares have accrued yet.</div>}</section><section className="panel"><div className="panel-head"><div><span><Shield/> SETTLEMENT</span><h2>Withdrawal queue</h2></div></div>{withdrawals.length?withdrawals.map(w=><div className="withdraw-row" key={w.id}><div><strong>{w.amount} {w.asset}</strong><small>{w.chain} • user #{w.user_id}</small></div><span className={`status ${w.status.toLowerCase()}`}>{w.status}</span></div>):<div className="empty-state">No withdrawal requests.</div>}</section></div>
 <section className="panel"><div className="panel-head"><div><span><TrendingUp/> PRICE TRACKING</span><h2>Add GBP price snapshot</h2></div></div><p>Use a trusted market source to record the latest GBP price. Earnings pages never invent a price when none is available.</p><div className="form-grid"><label>Asset symbol<input value={asset} onChange={e=>setAsset(e.target.value)} placeholder="AVAX"/></label><label>GBP price<input type="number" min="0" step="any" value={price} onChange={e=>setPrice(e.target.value)} placeholder="24.50"/></label></div><button className="btn primary" disabled={!asset||!price||Number(price)<=0} onClick={()=>void addPrice()}>Save price snapshot</button>{priceMsg&&<div className="form-note">{priceMsg}</div>}</section></div>
}
