import { getIdentityToken } from '@privy-io/react-auth'
import { useEffect, useState } from 'react'
import { Clock3, Copy, KeyRound, LockKeyhole, RefreshCw, ShieldCheck, ShieldOff } from 'lucide-react'
import { AdminNav } from '../components/AdminNav'
import { useAuth } from '../context/AuthContext'
import { api, setAdminPrivilege } from '../lib/api'

type SecurityStatus={mfa_enrolled:boolean;mfa_enabled:boolean;mfa_verified_at:string|null;auth_method:string;privileged:boolean;privilege_expires_at:string|null;privileged_minutes:number}
type AuditEvent={id:number;admin_user_id:number;user_session_id:string|null;privilege_session_id:number|null;event_type:string;method:string|null;path:string|null;reason:string|null;details:Record<string,unknown>|null;created_at:string}
type AuditResponse={total:number;events:AuditEvent[];privilege_session_id:number}

export default function AdminSecurity(){
 const {authSource}=useAuth();const [status,setStatus]=useState<SecurityStatus|null>(null);const [password,setPassword]=useState('');const [code,setCode]=useState('');const [setupCode,setSetupCode]=useState('');const [setup,setSetup]=useState<{secret:string;otpauth_uri:string}|null>(null);const [audit,setAudit]=useState<AuditEvent[]>([]);const [msg,setMsg]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false)
 const load=async()=>{try{const s=await api<SecurityStatus>('/admin/security/status');setStatus(s);if(s.privileged){const a=await api<AuditResponse>('/admin/security/audit?limit=100');setAudit(a.events)}else setAudit([])}catch(e:any){setError(e.message||'Could not load Admin security status')}}
 useEffect(()=>{void load()},[])
 const primaryProof=async()=>authSource==='privy'?{identity_token:await getIdentityToken()}:{password}
 const startSetup=async()=>{setBusy(true);setError('');setMsg('');try{const proof=await primaryProof();const r=await api<{secret:string;otpauth_uri:string}>('/admin/security/mfa/setup',{method:'POST',body:JSON.stringify(proof)});setSetup(r);setMsg('Authenticator secret created. Add it to your authenticator, then confirm a current 6-digit code.')}catch(e:any){setError(e.message||'Could not start MFA setup')}finally{setBusy(false)}}
 const confirmSetup=async()=>{setBusy(true);setError('');try{await api('/admin/security/mfa/confirm',{method:'POST',body:JSON.stringify({code:setupCode})});setSetup(null);setSetupCode('');setPassword('');setMsg('Admin MFA enabled. You can now open a short-lived privileged session.');await load()}catch(e:any){setError(e.message||'Could not confirm MFA')}finally{setBusy(false)}}
 const unlock=async()=>{setBusy(true);setError('');setMsg('');try{const proof=await primaryProof();const r=await api<{privilege_token:string;expires_at:string}>('/admin/security/privilege/start',{method:'POST',body:JSON.stringify({...proof,code})});setAdminPrivilege(r.privilege_token);setCode('');setPassword('');setMsg(`Privileged Admin session opened until ${new Date(r.expires_at).toLocaleTimeString()}.`);await load()}catch(e:any){setError(e.message||'Privileged reauthentication failed')}finally{setBusy(false)}}
 const lock=async()=>{setBusy(true);setError('');try{await api('/admin/security/privilege/revoke',{method:'POST'});setAdminPrivilege(null);setMsg('Privileged Admin session locked. Sensitive writes are blocked again.');await load()}catch(e:any){setError(e.message||'Could not lock privileged session')}finally{setBusy(false)}}
 const copy=async(value:string)=>{try{await navigator.clipboard.writeText(value);setMsg('Copied.')}catch{setError('Could not copy to clipboard')}}
 return <div className="page admin-security-page"><AdminNav/><div className="page-head"><div><span className="eyebrow small">ADMIN SECURITY</span><h1>Privileged access, <em>MFA & audit.</em></h1><p>Normal Admin read access is separate from privileged operations. Sensitive writes require a fresh primary-factor reauthentication plus a one-time authenticator code, and the resulting privilege expires automatically.</p></div></div>
 {msg&&<div className="form-note">{msg}</div>}{error&&<div className="form-error">{error}</div>}
 <div className="admin-security-grid"><section className="panel admin-security-card"><div className="panel-head"><div><span><ShieldCheck/> MFA STATUS</span><h2>{status?.mfa_enabled?'Authenticator enabled':'Authenticator required'}</h2></div><span className={`status ${status?.mfa_enabled?'verified':'pending'}`}>{status?.mfa_enabled?'ENABLED':'SETUP'}</span></div><p>NuBagz uses TOTP MFA for privileged Admin access. The secret is encrypted server-side and authenticator codes are single-use within the accepted time window.</p>{status?.mfa_verified_at&&<small>Verified {new Date(status.mfa_verified_at).toLocaleString()}</small>}
 {!status?.mfa_enabled&&!setup&&<div className="admin-security-form">{authSource==='password'&&<label>Re-enter Admin password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label>}{authSource==='privy'&&<div className="admin-security-callout">Your current Privy identity will be re-verified before an authenticator secret is issued.</div>}<button className="btn primary" disabled={busy||(authSource==='password'&&!password)} onClick={()=>void startSetup()}><KeyRound/> Start MFA setup</button></div>}
 {setup&&<div className="admin-mfa-setup"><label>Authenticator secret<div className="copy-field"><code>{setup.secret}</code><button onClick={()=>void copy(setup.secret)}><Copy/></button></div></label><label>Provisioning URI<div className="copy-field"><code>{setup.otpauth_uri}</code><button onClick={()=>void copy(setup.otpauth_uri)}><Copy/></button></div></label><label>Current 6-digit code<input inputMode="numeric" value={setupCode} onChange={e=>setSetupCode(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="123456"/></label><button className="btn primary" disabled={busy||setupCode.length!==6} onClick={()=>void confirmSetup()}>Confirm & enable MFA</button></div>}</section>
 <section className="panel admin-security-card"><div className="panel-head"><div><span><LockKeyhole/> PRIVILEGED SESSION</span><h2>{status?.privileged?'Sensitive controls unlocked':'Sensitive controls locked'}</h2></div><span className={`status ${status?.privileged?'verified':'restricted'}`}>{status?.privileged?'UNLOCKED':'LOCKED'}</span></div><p>Privilege is bound to this exact NuBagz login session and expires after {status?.privileged_minutes??10} minutes. Logging out, session revocation or expiry prevents reuse.</p>{status?.privilege_expires_at&&<div className="admin-security-expiry"><Clock3/> Expires {new Date(status.privilege_expires_at).toLocaleString()}</div>}
 {status?.mfa_enabled&&!status?.privileged&&<div className="admin-security-form">{authSource==='password'&&<label>Re-enter Admin password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label>}{authSource==='privy'&&<div className="admin-security-callout">NuBagz will re-verify the Privy identity bound to this Admin account.</div>}<label>Authenticator code<input inputMode="numeric" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="123456"/></label><button className="btn primary" disabled={busy||code.length!==6||(authSource==='password'&&!password)} onClick={()=>void unlock()}><ShieldCheck/> Reauthenticate & unlock</button></div>}
 {status?.privileged&&<button className="btn glass" disabled={busy} onClick={()=>void lock()}><ShieldOff/> Lock privileged session now</button>}</section></div>
 <section className="panel"><div className="panel-head"><div><span>AUDIT TRAIL</span><h2>Admin security timeline</h2></div><button className="mini-action" disabled={!status?.privileged} onClick={()=>void load()}><RefreshCw/> Refresh</button></div><p>Audit access itself requires an active privileged session. Detailed user-moderation before/after state remains in the Users & Trust action history; this timeline records Admin route access, MFA and privileged-session security events.</p>{!status?.privileged?<div className="empty-state"><LockKeyhole/><strong>Unlock privileged access to view the audit timeline.</strong></div>:audit.length?<div className="admin-audit-list">{audit.map(row=><div className="admin-audit-row" key={row.id}><div><strong>{row.event_type.replaceAll('_',' ')}</strong><small>{row.method||'SECURITY'} {row.path||''}</small>{row.reason&&<small>{row.reason}</small>}</div><div><span>Admin #{row.admin_user_id}</span><small>{new Date(row.created_at).toLocaleString()}</small></div></div>)}</div>:<div className="empty-state">No Admin audit events recorded yet.</div>}</section></div>
}