import { FormEvent, useEffect, useMemo, useState } from 'react'
import { AlertTriangle, ArrowLeft, BadgeCheck, Ban, CirclePause, Clock3, History, KeyRound, LockKeyhole, RefreshCw, Search, ShieldAlert, ShieldCheck, UserRoundCog, UsersRound, WalletCards } from 'lucide-react'
import { useLocation, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { AdminNav } from '../components/AdminNav'
import AdminRecoveryPanel from '../components/AdminRecoveryPanel'
import { api } from '../lib/api'

type TrustSummary={trust_level:string;risk_score:number;risk_band:string;open_signal_count:number;last_evaluated_at:string|null}
type AdminUserSummary={id:number;username:string;email:string;role:string;account_state:string;created_at:string;last_active_at:string|null;trust:TrustSummary;security:{active_session_count:number};wallet:{interactive_signer:string|null;reward_destination:string|null};reward_hold:{active:boolean;hold_id:number|null;created_at:string|null}}
type AdminUserList={total:number;limit:number;offset:number;users:AdminUserSummary[]}
type ProviderIdentity={provider:string;provider_user_id:string;username:string|null;email:string|null;display_name:string|null;connected_at:string;last_verified_at:string}
type WalletRow={id:number;address:string;chain_type:string;chain_id:number|null;wallet_client_type:string;connector_type:string;wallet_type:string;verified:boolean;verified_at:string|null;is_interactive_signer:boolean;is_reward_destination:boolean;last_connected_at:string}
type PayoutRow={id:number;address:string;chain:string;label:string;is_reward_destination:boolean;verification_status:string;created_at:string}
type RiskSignal={id:number;type:string;severity:string;detail:string;status:string;created_at:string;resolved_at:string|null}
type TrustReview={id:number;trust_level:string;note:string;reviewed_by_id:number;created_at:string}
type RewardState={asset:string;status:string;amount:string}
type RewardHold={id:number;status:string;reason:string;created_by_id:number;created_at:string;released_by_id:number|null;released_at:string|null;release_reason:string|null}
type SessionRow={session_id:string;auth_method:string;created_at:string;expires_at:string;last_seen_at:string;revoked_at:string|null;revoke_reason:string|null}
type AdminAction={id:number;admin_user_id:number;action_type:string;reason:string;before_state:Record<string,unknown>|null;after_state:Record<string,unknown>|null;created_at:string}
type AdminUserDetail={
 account:AdminUserSummary
 identities:{privy:{privy_user_id:string;created_at:string;last_verified_at:string}|null;providers:ProviderIdentity[]}
 wallets:WalletRow[]
 payout_addresses:PayoutRow[]
 trust:{trust_level:string;risk_score:number;risk_band:string;last_evaluated_at:string|null;reasoning:{positive:string[];risk:string[];note:string};signals:RiskSignal[];review_history:TrustReview[]}
 challenges:{status_counts:Record<string,number>}
 rewards:{balances_by_state:RewardState[];withdrawal_status_counts:Record<string,number>;holds:RewardHold[]}
 security:{sessions:SessionRow[]}
 admin_actions:AdminAction[]
}

type PendingAction={title:string;description:string;confirmLabel:string;danger?:boolean;run:(reason:string)=>Promise<void>}

const ACCOUNT_STATES=['ACTIVE','UNDER_REVIEW','RESTRICTED','SUSPENDED','DISQUALIFIED']
const TRUST_LEVELS=['NORMAL','VERIFIED','REVIEW','RESTRICTED']
const LIMIT=50

function when(value:string|null|undefined){if(!value)return '—';const date=new Date(value);return Number.isNaN(date.getTime())?value:date.toLocaleString()}
function short(value:string|null|undefined,front=10,back=8){if(!value)return '—';return value.length<=front+back+3?value:`${value.slice(0,front)}…${value.slice(-back)}`}
function statusClass(value:string){return `admin-state-chip ${String(value||'UNKNOWN').toLowerCase().replaceAll('_','-')}`}
function jsonPreview(value:Record<string,unknown>|null){if(!value)return '—';const text=JSON.stringify(value);return text.length>140?`${text.slice(0,137)}…`:text}

function ActionModal({action,onClose,onDone}:{action:PendingAction;onClose:()=>void;onDone:()=>Promise<void>}){
 const [reason,setReason]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('')
 const submit=async(e:FormEvent)=>{e.preventDefault();if(reason.trim().length<8)return;setBusy(true);setError('');try{await action.run(reason.trim());await onDone();onClose()}catch(err:any){setError(err.message||'Action failed')}finally{setBusy(false)}}
 return <div className="admin-modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)onClose()}}><form className="admin-action-modal" role="dialog" aria-modal="true" aria-labelledby="admin-action-title" onSubmit={e=>void submit(e)}>
   <div className="admin-action-icon"><ShieldAlert size={22}/></div><div><span className="eyebrow small">AUDITED ADMIN ACTION</span><h2 id="admin-action-title">{action.title}</h2><p>{action.description}</p></div>
   <label>Reason required<textarea autoFocus value={reason} onChange={e=>setReason(e.target.value)} maxLength={2000} placeholder="Record the evidence, support context or operational reason for this change."/></label>
   <small className="admin-reason-help">Minimum 8 characters. This reason is stored with the Admin action history.</small>{error&&<div className="admin-inline-error">{error}</div>}
   <div className="admin-modal-actions"><button type="button" className="btn glass" disabled={busy} onClick={onClose}>Cancel</button><button type="submit" className={`btn ${action.danger?'admin-danger-btn':'primary'}`} disabled={busy||reason.trim().length<8}>{busy?'Applying…':action.confirmLabel}</button></div>
  </form></div>
}

export default function AdminUsers(){
 const {userId}=useParams();const numericUserId=userId?Number(userId):null
 return numericUserId?<AdminUserDetailView userId={numericUserId}/>:<AdminUserListView/>
}

function AdminUserListView(){
 const navigate=useNavigate();const location=useLocation();const [searchParams,setSearchParams]=useSearchParams()
 const [query,setQuery]=useState(searchParams.get('q')||'');const [appliedQuery,setAppliedQuery]=useState(searchParams.get('q')||'')
 const [accountState,setAccountState]=useState(searchParams.get('state')||'');const [trustLevel,setTrustLevel]=useState(searchParams.get('trust')||'');const [holdFilter,setHoldFilter]=useState(searchParams.get('hold')||'')
 const [offset,setOffset]=useState(Math.max(0,Number(searchParams.get('offset')||0)||0));const [data,setData]=useState<AdminUserList|null>(null);const [loading,setLoading]=useState(true);const [message,setMessage]=useState('');const [error,setError]=useState('')
 const params=useMemo(()=>{const p=new URLSearchParams();if(appliedQuery)p.set('q',appliedQuery);if(accountState)p.set('state',accountState);if(trustLevel)p.set('trust',trustLevel);if(holdFilter)p.set('hold',holdFilter);if(offset)p.set('offset',String(offset));return p},[appliedQuery,accountState,trustLevel,holdFilter,offset])
 const load=async()=>{setLoading(true);setError('');const q=new URLSearchParams();if(appliedQuery)q.set('q',appliedQuery);if(accountState)q.set('account_state',accountState);if(trustLevel)q.set('trust_level',trustLevel);if(holdFilter)q.set('reward_hold',String(holdFilter==='held'));q.set('limit',String(LIMIT));q.set('offset',String(offset));try{setData(await api<AdminUserList>(`/admin/users?${q.toString()}`))}catch(err:any){setError(err.message||'Could not load users')}finally{setLoading(false)}}
 useEffect(()=>{setSearchParams(params,{replace:true});void load()},[params])
 const submitSearch=(e:FormEvent)=>{e.preventDefault();setOffset(0);setAppliedQuery(query.trim())}
 const clearFilters=()=>{setQuery('');setAppliedQuery('');setAccountState('');setTrustLevel('');setHoldFilter('');setOffset(0)}
 const evaluateAll=async()=>{setMessage('');setError('');try{const result=await api<{evaluated:number}>('/risk/admin/evaluate-all',{method:'POST'});setMessage(`Re-evaluated ${result.evaluated} active accounts.`);await load()}catch(err:any){setError(err.message||'Could not run account risk evaluation')}}
 const visible=data?.users||[];const reviewCount=visible.filter(u=>['REVIEW','RESTRICTED'].includes(u.trust.trust_level)).length;const heldCount=visible.filter(u=>u.reward_hold.active).length;const limitedCount=visible.filter(u=>['RESTRICTED','SUSPENDED','DISQUALIFIED'].includes(u.account_state)).length
 const openUser=(id:number)=>navigate(`/app/admin/users/${id}${location.search}`)
 return <div className="page admin-users-page"><div className="page-head admin-users-head"><div><span className="eyebrow small">ADMIN USERS</span><h1>Investigate users without <em>mixing the controls.</em></h1><p>Search identities, wallets and account records, then review Trust, account access, reward holds and sessions as separate audited decisions.</p></div><button className="btn glass" onClick={()=>void evaluateAll()}><RefreshCw size={16}/> Re-evaluate active accounts</button></div><AdminNav/>
  {message&&<div className="form-note">{message}</div>}{error&&<div className="admin-inline-error">{error}</div>}
  <div className="admin-user-stats"><div><span>RESULTS</span><strong>{data?.total??'—'}</strong><small>matching users</small></div><div><span>VISIBLE TRUST REVIEW</span><strong>{reviewCount}</strong><small>Review / Restricted</small></div><div><span>VISIBLE REWARD HOLDS</span><strong>{heldCount}</strong><small>payout blocked</small></div><div><span>VISIBLE ACCESS LIMITS</span><strong>{limitedCount}</strong><small>restricted or blocked</small></div></div>
  <section className="panel admin-user-search-panel"><form className="admin-user-search" onSubmit={submitSearch}><label className="admin-search-field"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, email, user ID, wallet, X/Google or Privy ID"/></label><button className="btn primary" type="submit">Search</button></form><div className="admin-filter-row"><label>Account state<select value={accountState} onChange={e=>{setOffset(0);setAccountState(e.target.value)}}><option value="">All states</option>{ACCOUNT_STATES.map(s=><option key={s}>{s}</option>)}</select></label><label>Trust<select value={trustLevel} onChange={e=>{setOffset(0);setTrustLevel(e.target.value)}}><option value="">All Trust levels</option>{TRUST_LEVELS.map(s=><option key={s}>{s}</option>)}</select></label><label>Reward hold<select value={holdFilter} onChange={e=>{setOffset(0);setHoldFilter(e.target.value)}}><option value="">All users</option><option value="held">Held</option><option value="clear">Not held</option></select></label><button className="admin-clear-filters" type="button" onClick={clearFilters}>Clear filters</button></div></section>
  <section className="panel admin-user-results"><div className="panel-head"><div><span><UsersRound/> USER DIRECTORY</span><h2>{loading?'Loading users…':`${data?.total??0} matching account${data?.total===1?'':'s'}`}</h2></div><small>Showing {visible.length?offset+1:0}–{Math.min(offset+visible.length,data?.total||0)}</small></div>
   {loading?<div className="empty-state">Loading Admin user records…</div>:visible.length?visible.map(user=><button className="admin-user-row" key={user.id} onClick={()=>openUser(user.id)}><div className="admin-user-avatar">{user.username.slice(0,2).toUpperCase()}</div><div className="admin-user-main"><div><strong>{user.username}</strong><span>#{user.id}</span></div><small>{user.email}</small><small>{short(user.wallet.interactive_signer)} signer • {short(user.wallet.reward_destination)} reward destination</small></div><div className="admin-user-statuses"><span className={statusClass(user.account_state)}>{user.account_state}</span><span className={statusClass(user.trust.trust_level)}>Trust {user.trust.trust_level}</span>{user.reward_hold.active&&<span className="admin-state-chip reward-held">REWARD HOLD</span>}</div><div className="admin-user-risk"><strong>{user.trust.risk_score}/100</strong><small>{user.trust.risk_band} risk</small><small>{user.trust.open_signal_count} open signal{user.trust.open_signal_count===1?'':'s'}</small></div><div className="admin-user-session"><KeyRound size={15}/><strong>{user.security.active_session_count}</strong><small>active</small></div></button>):<div className="empty-state"><Search/><strong>No users matched.</strong><p>Try removing a filter or searching another identity.</p></div>}
   <div className="admin-pagination"><button className="btn glass" disabled={offset===0||loading} onClick={()=>setOffset(Math.max(0,offset-LIMIT))}>Previous</button><span>Page {Math.floor(offset/LIMIT)+1}</span><button className="btn glass" disabled={loading||!data||offset+LIMIT>=data.total} onClick={()=>setOffset(offset+LIMIT)}>Next</button></div>
  </section>
 </div>
}

function AdminUserDetailView({userId}:{userId:number}){
 const navigate=useNavigate();const location=useLocation();const [detail,setDetail]=useState<AdminUserDetail|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [message,setMessage]=useState('');const [action,setAction]=useState<PendingAction|null>(null);const [stateDraft,setStateDraft]=useState('');const [trustDraft,setTrustDraft]=useState('')
 const listUrl=`/app/admin/users${location.search}`
 const load=async()=>{setLoading(true);setError('');try{const value=await api<AdminUserDetail>(`/admin/users/${userId}`);setDetail(value);setStateDraft(value.account.account_state);setTrustDraft(value.trust.trust_level)}catch(err:any){setError(err.message||'Could not load user investigation record')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[userId])
 const afterAction=async()=>{setMessage('Action recorded. User investigation record refreshed.');await load()}
 const openAction=(next:PendingAction)=>{setMessage('');setAction(next)}
 if(loading)return <div className="page admin-users-page"><AdminNav/><div className="empty-state">Loading user investigation…</div></div>
 if(error||!detail)return <div className="page admin-users-page"><AdminNav/><button className="admin-back-link" onClick={()=>navigate(listUrl)}><ArrowLeft/> Back to users</button><div className="admin-inline-error">{error||'User not found'}</div></div>
 const account=detail.account;const activeSessions=detail.security.sessions.filter(s=>!s.revoked_at);const challengeTotal=Object.values(detail.challenges.status_counts).reduce((a,b)=>a+b,0)
 return <div className="page admin-users-page"><div className="admin-detail-top"><button className="admin-back-link" onClick={()=>navigate(listUrl)}><ArrowLeft/> Back to users</button><AdminNav/></div>
  <div className="admin-user-hero"><div className="admin-user-hero-avatar">{account.username.slice(0,2).toUpperCase()}</div><div><span className="eyebrow small">USER INVESTIGATION #{account.id}</span><h1>{account.username}</h1><p>{account.email} • {account.role} • joined {when(account.created_at)}</p></div><div className="admin-user-hero-flags"><span className={statusClass(account.account_state)}>{account.account_state}</span><span className={statusClass(detail.trust.trust_level)}>Trust {detail.trust.trust_level}</span>{account.reward_hold.active&&<span className="admin-state-chip reward-held">REWARD HOLD</span>}</div></div>{message&&<div className="form-note">{message}</div>}
  <div className="admin-separation-note"><ShieldCheck/><div><strong>These controls are deliberately independent.</strong><p>Trust is evidence/risk assessment. Account State controls access. Reward Hold blocks withdrawals. Session revocation invalidates login sessions. Changing one does not silently rewrite the others.</p></div></div>
  <div className="admin-control-grid"><section className="admin-control-card"><span><UserRoundCog/> ACCOUNT STATE</span><strong>{account.account_state}</strong><p>Controls whether the user can authenticate or start reward/on-chain value actions.</p><select value={stateDraft} onChange={e=>setStateDraft(e.target.value)}>{ACCOUNT_STATES.map(s=><option key={s}>{s}</option>)}</select><button className="btn glass" disabled={stateDraft===account.account_state} onClick={()=>openAction({title:`Change account state to ${stateDraft}`,description:`This changes access for ${account.username}. Suspending or disqualifying also revokes active sessions. Historical records remain intact.`,confirmLabel:'Apply account state',danger:['SUSPENDED','DISQUALIFIED'].includes(stateDraft),run:reason=>api(`/admin/users/${account.id}/state`,{method:'PATCH',body:JSON.stringify({account_state:stateDraft,reason})})})}>Apply state</button></section>
   <section className="admin-control-card"><span><ShieldCheck/> TRUST DECISION</span><strong>{detail.trust.trust_level}</strong><p>Manual Trust correction with the existing risk score retained for investigation context.</p><select value={trustDraft} onChange={e=>setTrustDraft(e.target.value)}>{TRUST_LEVELS.map(s=><option key={s}>{s}</option>)}</select><button className="btn glass" disabled={trustDraft===detail.trust.trust_level} onClick={()=>openAction({title:`Correct Trust to ${trustDraft}`,description:`This records a manual Trust decision for ${account.username}. It does not automatically change Account State or delete risk signals.`,confirmLabel:'Record Trust correction',run:reason=>api(`/admin/users/${account.id}/trust/correct`,{method:'POST',body:JSON.stringify({trust_level:trustDraft,reason})})})}>Correct Trust</button></section>
   <section className="admin-control-card"><span><LockKeyhole/> REWARD HOLD</span><strong>{account.reward_hold.active?'HELD':'CLEAR'}</strong><p>Blocks new withdrawals without rewriting ledger balances, approved rewards or settlement history.</p><button className={`btn ${account.reward_hold.active?'glass':'admin-warning-btn'}`} onClick={()=>openAction(account.reward_hold.active?{title:'Release reward hold',description:`Allow ${account.username} to request withdrawals again. Existing reward history is unchanged.`,confirmLabel:'Release reward hold',run:reason=>api(`/admin/users/${account.id}/rewards/release`,{method:'POST',body:JSON.stringify({reason})})}:{title:'Place reward hold',description:`Block new withdrawal requests for ${account.username}. Ledger history and approved rewards remain untouched.`,confirmLabel:'Hold rewards',danger:true,run:reason=>api(`/admin/users/${account.id}/rewards/hold`,{method:'POST',body:JSON.stringify({reason})})})}>{account.reward_hold.active?'Release hold':'Hold rewards'}</button></section>
   <section className="admin-control-card"><span><KeyRound/> SESSION SECURITY</span><strong>{activeSessions.length} ACTIVE</strong><p>Revoke server-side sessions. Restoring an account later will not resurrect revoked sessions.</p><button className="btn admin-danger-btn" disabled={!activeSessions.length} onClick={()=>openAction({title:'Revoke all active sessions',description:`Immediately invalidate all active NuBagz sessions for ${account.username}. The user must authenticate again.`,confirmLabel:'Revoke all sessions',danger:true,run:reason=>api(`/admin/users/${account.id}/sessions/revoke`,{method:'POST',body:JSON.stringify({reason,session_id:null})})})}>Revoke all sessions</button></section></div>
  <div className="admin-detail-grid"><section className="panel admin-trust-investigation"><div className="panel-head"><div><span><ShieldAlert/> TRUST INVESTIGATION</span><h2>Reasoning & signals</h2></div><span className={statusClass(detail.trust.risk_band)}>Risk {detail.trust.risk_score}/100</span></div><p className="admin-trust-note">{detail.trust.reasoning.note}</p><div className="admin-reason-columns"><div><h3>Positive context</h3>{detail.trust.reasoning.positive.length?detail.trust.reasoning.positive.map(item=><div className="admin-reason positive" key={item}><BadgeCheck/>{item}</div>):<div className="admin-muted">No positive reasoning recorded.</div>}</div><div><h3>Open risk context</h3>{detail.trust.reasoning.risk.length?detail.trust.reasoning.risk.map(item=><div className="admin-reason risk" key={item}><AlertTriangle/>{item}</div>):<div className="admin-muted">No open risk reasoning.</div>}</div></div><div className="admin-signal-list"><h3>Signals</h3>{detail.trust.signals.length?detail.trust.signals.map(signal=><div className="admin-signal-row" key={signal.id}><div><strong>{signal.type.replaceAll('_',' ')}</strong><small>{signal.severity} • opened {when(signal.created_at)}{signal.resolved_at?` • resolved ${when(signal.resolved_at)}`:''}</small><p>{signal.detail}</p></div><span className={statusClass(signal.status)}>{signal.status}</span><button className="btn glass" onClick={()=>openAction({title:`${signal.status==='OPEN'?'Resolve':'Reopen'} risk signal`,description:`${signal.status==='OPEN'?'Resolve':'Reopen'} ${signal.type.replaceAll('_',' ')} for ${account.username}. This changes the signal record only; it does not silently change Trust or Account State.`,confirmLabel:signal.status==='OPEN'?'Resolve signal':'Reopen signal',run:reason=>api(`/admin/users/${account.id}/signals/${signal.id}`,{method:'POST',body:JSON.stringify({status:signal.status==='OPEN'?'RESOLVED':'OPEN',reason})})})}>{signal.status==='OPEN'?'Resolve':'Reopen'}</button></div>):<div className="empty-state">No risk signals recorded.</div>}</div></section>
   <section className="panel"><div className="panel-head"><div><span><UsersRound/> IDENTITY EVIDENCE</span><h2>Linked identities</h2></div></div><div className="admin-identity-card"><strong>Privy identity</strong><code>{detail.identities.privy?.privy_user_id||'No canonical Privy binding'}</code><small>{detail.identities.privy?`Last verified ${when(detail.identities.privy.last_verified_at)}`:'Not currently bound'}</small></div>{detail.identities.providers.length?detail.identities.providers.map(row=><div className="admin-identity-card" key={row.provider}><strong>{row.provider}</strong><code>{row.provider_user_id}</code><small>{row.display_name||row.username||row.email||'Provider identity'} • verified {when(row.last_verified_at)}</small></div>):<div className="admin-muted">No X or Google identity currently linked.</div>}</section></div>
  <div className="admin-detail-grid"><section className="panel"><div className="panel-head"><div><span><WalletCards/> WALLET SEMANTICS</span><h2>Interactive vs reward wallets</h2></div></div><p>Interactive signers are cryptographically verified. Reward destinations are payout addresses and do not prove wallet ownership.</p>{detail.wallets.length?detail.wallets.map(row=><div className="admin-wallet-row" key={row.id}><div><strong>{short(row.address,14,10)}</strong><small>{row.chain_type}{row.chain_id?` #${row.chain_id}`:''} • {row.wallet_type} • {row.wallet_client_type}</small></div><div className="admin-wallet-badges">{row.verified&&<span className="admin-state-chip verified">VERIFIED SIGNER</span>}{row.is_interactive_signer&&<span className="admin-state-chip active">INTERACTIVE</span>}{row.is_reward_destination&&<span className="admin-state-chip under-review">REWARD DESTINATION</span>}</div></div>):<div className="admin-muted">No wallet connections.</div>}<h3 className="admin-subsection-title">Payout-only destinations</h3>{detail.payout_addresses.length?detail.payout_addresses.map(row=><div className="admin-wallet-row" key={row.id}><div><strong>{short(row.address,14,10)}</strong><small>{row.chain} • {row.label}</small></div><div className="admin-wallet-badges"><span className={statusClass(row.verification_status)}>{row.verification_status}</span>{row.is_reward_destination&&<span className="admin-state-chip reward-held">REWARD DESTINATION</span>}</div></div>):<div className="admin-muted">No payout-only destinations.</div>}</section>
   <section className="panel"><div className="panel-head"><div><span><CirclePause/> REWARDS & WORK</span><h2>History remains intact</h2></div><strong>{challengeTotal} Challenges</strong></div><div className="admin-mini-metrics">{Object.entries(detail.challenges.status_counts).map(([status,count])=><div key={status}><span>{status}</span><strong>{count}</strong></div>)}</div><h3 className="admin-subsection-title">Reward balances by ledger state</h3>{detail.rewards.balances_by_state.length?detail.rewards.balances_by_state.map((row,i)=><div className="admin-ledger-row" key={`${row.asset}-${row.status}-${i}`}><strong>{row.asset}</strong><span>{row.status}</span><b>{row.amount}</b></div>):<div className="admin-muted">No reward ledger entries.</div>}<h3 className="admin-subsection-title">Reward hold history</h3>{detail.rewards.holds.length?detail.rewards.holds.map(row=><div className="admin-hold-history" key={row.id}><div><strong>{row.status}</strong><small>Hold #{row.id} • {when(row.created_at)}</small></div><p>{row.reason}</p>{row.release_reason&&<small>Release: {row.release_reason} • {when(row.released_at)}</small>}</div>):<div className="admin-muted">No reward holds have been recorded.</div>}</section></div>
  <div className="admin-detail-grid"><section className="panel"><div className="panel-head"><div><span><KeyRound/> SESSIONS</span><h2>Server-side login sessions</h2></div></div>{detail.security.sessions.length?detail.security.sessions.map(row=><div className="admin-session-row" key={row.session_id}><div><strong>{short(row.session_id,12,8)}</strong><small>{row.auth_method} • created {when(row.created_at)} • last seen {when(row.last_seen_at)}</small>{row.revoke_reason&&<small>Revocation: {row.revoke_reason}</small>}</div><span className={statusClass(row.revoked_at?'REVOKED':'ACTIVE')}>{row.revoked_at?'REVOKED':'ACTIVE'}</span>{!row.revoked_at&&<button className="btn glass" onClick={()=>openAction({title:'Revoke this session',description:`Invalidate session ${short(row.session_id,12,8)} for ${account.username}.`,confirmLabel:'Revoke session',danger:true,run:reason=>api(`/admin/users/${account.id}/sessions/revoke`,{method:'POST',body:JSON.stringify({reason,session_id:row.session_id})})})}>Revoke</button>}</div>):<div className="admin-muted">No sessions recorded.</div>}</section>
   <section className="panel"><div className="panel-head"><div><span><History/> TRUST REVIEW HISTORY</span><h2>Manual decisions</h2></div></div>{detail.trust.review_history.length?detail.trust.review_history.map(row=><div className="admin-history-row" key={row.id}><div><span className={statusClass(row.trust_level)}>{row.trust_level}</span><small>{when(row.created_at)} • admin #{row.reviewed_by_id}</small></div><p>{row.note||'No review note.'}</p></div>):<div className="admin-muted">No manual Trust reviews recorded.</div>}</section></div>
  <AdminRecoveryPanel userId={account.id} username={account.username} privyUserId={detail.identities.privy?.privy_user_id||null} wallets={detail.wallets} onChanged={load}/>
  <section className="panel"><div className="panel-head"><div><span><Clock3/> ADMIN ACTION HISTORY</span><h2>Audited user actions</h2></div><span>{detail.admin_actions.length} shown</span></div>{detail.admin_actions.length?detail.admin_actions.map(row=><div className="admin-audit-row" key={row.id}><div><strong>{row.action_type.replaceAll('_',' ')}</strong><small>{when(row.created_at)} • admin #{row.admin_user_id}</small></div><p>{row.reason}</p><code title={JSON.stringify({before:row.before_state,after:row.after_state})}>Before: {jsonPreview(row.before_state)} | After: {jsonPreview(row.after_state)}</code></div>):<div className="admin-muted">No Phase 2.3 Admin user actions recorded yet.</div>}</section>
  {action&&<ActionModal action={action} onClose={()=>setAction(null)} onDone={afterAction}/>}</div>
}
