import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, CheckCircle2, Hammer, Plus, Sparkles } from 'lucide-react'
import { api } from '../lib/api'
import { useAuth } from '../context/AuthContext'
import type { Campaign } from '../types'

type Pathway={id:number;campaign_id:number;campaign_title:string;project_name:string;creator_username:string;title:string;summary:string;creator_share_pct:string;status:string}

export default function BagBuilders(){
 const {user}=useAuth();const [rows,setRows]=useState<Pathway[]>([]);const [mine,setMine]=useState<Pathway[]>([]);const [review,setReview]=useState<Pathway[]>([]);const [campaigns,setCampaigns]=useState<Campaign[]>([]);const [msg,setMsg]=useState('');const [show,setShow]=useState(false)
 const [f,setF]=useState({campaign_id:0,title:'',summary:'',creator_share_pct:5})
 const load=()=>{Promise.all([api<Pathway[]>('/builders'),api<Pathway[]>('/builders/mine'),api<Campaign[]>('/campaigns')]).then(([a,b,c])=>{setRows(a);setMine(b);setCampaigns(c);if(!f.campaign_id&&c[0])setF(v=>({...v,campaign_id:c[0].id}))});api<Pathway[]>('/builders/review').then(setReview).catch(()=>setReview([]))};useEffect(()=>{load()},[])
 const available=useMemo(()=>rows,[rows])
 const create=async(e:React.FormEvent)=>{e.preventDefault();try{await api('/builders',{method:'POST',body:JSON.stringify(f)});setMsg('Pathway submitted to the project owner for approval.');setShow(false);load()}catch(e:any){setMsg(e.message||'Could not submit pathway')}}
 const decide=async(id:number,status:string)=>{try{await api(`/builders/${id}`,{method:'PATCH',body:JSON.stringify({status})});setMsg(`Pathway ${status.toLowerCase()}.`);load()}catch(e:any){setMsg(e.message||'Could not review pathway')}}
 const start=async(row:Pathway)=>{try{await api(`/builders/${row.id}/start`,{method:'POST'});setMsg(`Pathway attributed. Complete ${row.campaign_title} and ${row.creator_username} earns from NuBagz's share.`)}catch(e:any){setMsg(e.message||'Could not start pathway')}}
 return <div className="page"><div className="page-head"><div><span className="eyebrow small">BAGBUILDER MARKETPLACE</span><h1>Teach the route. <em>Earn from value.</em></h1><p>Create useful onboarding pathways for live projects. Approved BagBuilders earn from NuBagz’s existing platform share when attributed users complete the funded campaign.</p></div><button className="btn primary" onClick={()=>setShow(!show)}><Plus/> Build a pathway</button></div>{msg&&<div className="form-note">{msg}</div>}
 {show&&<form className="panel builder" onSubmit={create}><h3>Create a BagBuilder pathway</h3><div className="form-grid"><label>Live Bag<select value={f.campaign_id} onChange={e=>setF({...f,campaign_id:Number(e.target.value)})}>{campaigns.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>Your share of gross<input type="number" min="0.1" max="15" step="0.1" value={f.creator_share_pct} onChange={e=>setF({...f,creator_share_pct:Number(e.target.value)})}/><small>Must fit inside NuBagz’s platform share.</small></label><label className="full-span">Pathway title<input required value={f.title} onChange={e=>setF({...f,title:e.target.value})} placeholder="The 5-minute beginner route"/></label><label className="full-span">Guide / value proposition<textarea required minLength={20} value={f.summary} onChange={e=>setF({...f,summary:e.target.value})} placeholder="Explain how your pathway helps a newcomer understand and complete this Bag."/></label></div><button className="btn primary"><Hammer/> Submit for project approval</button></form>}
 {review.some(r=>r.status==='PENDING')&&<section className="panel"><div className="panel-head"><div><span>PROJECT OWNER REVIEW</span><h2>Approve community pathways</h2></div></div>{review.filter(r=>r.status==='PENDING').map(r=><div className="activity-row" key={r.id}><div><span>{r.project_name} • by {r.creator_username}</span><strong>{r.title}</strong></div><b>{r.creator_share_pct}%</b><div className="row-actions"><button className="mini-action" onClick={()=>decide(r.id,'APPROVED')}>Approve</button><button className="mini-action" onClick={()=>decide(r.id,'REJECTED')}>Reject</button></div></div>)}</section>}
 <section className="panel"><div className="panel-head"><div><span>APPROVED PATHWAYS</span><h2>Choose a community route</h2></div></div>{available.length?available.map(r=><div className="activity-row" key={r.id}><div><span>{r.project_name} • {r.creator_username}</span><strong>{r.title}</strong><small>{r.summary}</small></div><b>{r.creator_share_pct}% builder share</b><button className="mini-action" disabled={r.creator_username===user?.username} onClick={()=>start(r)}>Use pathway <ArrowRight/></button></div>):<div className="empty-state"><Hammer/><strong>No approved BagBuilder pathways yet.</strong><p>Be the first to create a genuinely useful onboarding route.</p></div>}</section>
 <section className="panel"><div className="panel-head"><div><span><Sparkles/> YOUR BUILDS</span><h2>Creator history</h2></div></div>{mine.length?mine.map(r=><div className="activity-row" key={r.id}><div><span>{r.status}</span><strong>{r.title}</strong></div><b>{r.creator_share_pct}%</b>{r.status==='APPROVED'&&<CheckCircle2/>}</div>):<div className="empty-state">No pathways created yet.</div>}</section></div>
}
