import { useEffect, useState } from 'react'
import { useParams, Link } from 'react-router-dom'
import { ArrowLeft, ArrowRight, Bookmark, BookmarkCheck, Check, CheckCircle2, Clock3, Coins, ExternalLink, LockKeyhole, ShieldCheck, Sparkles, Trophy, Users, Zap } from 'lucide-react'
import { api } from '../lib/api'
import type { Campaign } from '../types'

type WatchStatus={campaign_id:number;watched:boolean;watchable:boolean}
type AccessStatus={campaign_id:number;min_bag_score:number;required_tier:string;eligible:boolean;your_bag_score:number;your_tier:string;shortfall:number;reason:string|null;applies_to:string}

export default function BagDetail(){const {id}=useParams();const [c,setC]=useState<Campaign|null>(null);const [progress,setProgress]=useState<any>(null);const [watch,setWatch]=useState<WatchStatus|null>(null);const [access,setAccess]=useState<AccessStatus|null>(null);const [busy,setBusy]=useState<number|null>(null);const [message,setMessage]=useState('')
 const load=()=>Promise.all([api<Campaign>(`/campaigns/${id}`),api<any>(`/campaigns/${id}/progress`),api<WatchStatus>(`/watchbag/status/${id}`),api<AccessStatus>(`/access/campaigns/${id}`)]).then(([campaign,p,w,a])=>{setC(campaign);setProgress(p);setWatch(w);setAccess(a)}).catch(()=>{})
 useEffect(()=>{load()},[id])
 if(!c)return <div className="page"><div className="skeleton detail"/></div>
 const userReward=Number(c.gross_reward_per_user)*Number(c.user_share_pct)/100; const doneIds=progress?.completed_mission_ids||[]
 const join=async()=>{if(access&&!access.eligible){setMessage(access.reason||'Your BagScore is not high enough for this Bag yet.');return}try{await api(`/campaigns/${id}/enroll`,{method:'POST'});await load()}catch(e:any){setMessage(e.message)}}
 const toggleWatch=async()=>{try{if(watch?.watched)await api(`/watchbag/${id}`,{method:'DELETE'});else await api(`/watchbag/${id}`,{method:'POST'});setMessage(watch?.watched?'Removed from WatchBag.':'Added to WatchBag.');await load()}catch(e:any){setMessage(e.message||'Could not update WatchBag')}}
 const complete=async(m:any)=>{setBusy(m.id);setMessage('');let answer:string|undefined=undefined;if(m.verification_type==='QUIZ'){answer=window.prompt(`${m.quiz_question}\n\n${(m.quiz_options||[]).join('   •   ')}`)||undefined;if(!answer){setBusy(null);return}}try{const result=await api<any>(`/campaigns/${id}/missions/${m.id}/complete`,{method:'POST',body:JSON.stringify({answer})});setMessage(result.completed?`Bag complete — ${userReward.toLocaleString()} ${c.reward_asset} added to your ledger.`:`Mission complete. +${m.xp_reward} XP`);await load()}catch(e:any){setMessage(e.message)}finally{setBusy(null)}}
 return <div className="page bag-detail"><Link to="/app/work?view=all" className="back-link"><ArrowLeft/> Back to Bag Work</Link><div className="detail-hero"><div className="detail-copy"><div className="detail-project"><div className="big-token">{c.project?.symbol?.slice(0,4)}</div><div><span>{c.project?.name}</span><small>{c.project?.chain} • {c.category}</small></div></div><h1>{c.title}</h1><p>{c.description}</p><div className="detail-tags"><span><Clock3/> ~{c.missions.length*2+2} min</span><span><Users/> {Math.max(0,c.max_users-c.enrolled_count).toLocaleString()} spots left</span><span><ShieldCheck/> Reward backed</span>{access&&access.min_bag_score>0&&<span><LockKeyhole/> BagScore {access.min_bag_score}+ • {access.required_tier}</span>}</div><button className="mini-action" disabled={!watch?.watchable&&!watch?.watched} onClick={toggleWatch}>{watch?.watched?<BookmarkCheck/>:<Bookmark/>} {watch?.watched?'Watching':'Watch Bag'}</button></div><div className="reward-ticket"><div className="ticket-glow"/><span>COMPLETE THE BAG</span><strong>{userReward.toLocaleString(undefined,{maximumFractionDigits:4})}</strong><b>{c.reward_asset}</b>{c.estimated_value_gbp&&<small>Estimated campaign value ~£{(Number(c.estimated_value_gbp)*0.8).toFixed(2)}</small>}<div className="split-mini"><span>{c.user_share_pct}% user share</span><span>{c.nubagz_share_pct}% NuBagz</span><span>{c.referral_share_pct}% referral</span></div>{!progress?.joined?(access&&!access.eligible?<div><button className="btn glass full" disabled><LockKeyhole/> Locked • {access.required_tier}</button><small className="form-note">{access.reason}</small></div>:<button className="btn primary full" onClick={join}>Join this Bag <ArrowRight/></button>):<div className="joined"><CheckCircle2/> Bag joined</div>}</div></div>
 <div className="mission-layout"><section><div className="section-row"><div><span className="eyebrow small">MISSION PATH</span><h2>Earn it. Don't buy it.</h2></div><span className="progress-count">{doneIds.length}/{c.missions.length} complete</span></div><div className="missions">{c.missions.map((m,i)=>{const done=doneIds.includes(m.id);return <div className={done?'mission done':'mission'} key={m.id}><div className="mission-index">{done?<Check/>:String(i+1).padStart(2,'0')}</div><div className="mission-content"><div className="mission-top"><div><span>{m.mission_type}</span><h3>{m.title}</h3></div><b><Zap/> +{m.xp_reward} XP</b></div><p>{m.description}</p>{m.target_url&&<a href={m.target_url} target="_blank">Open destination <ExternalLink/></a>}{done?<div className="done-label"><CheckCircle2/> Completed</div>:<button disabled={!progress?.joined||busy===m.id} onClick={()=>complete(m)} className="btn glass">{busy===m.id?'Verifying…':m.verification_type==='QUIZ'?'Answer check':'Complete mission'} <ArrowRight/></button>}</div></div>})}</div>{message&&<div className="toast-inline"><Sparkles/>{message}</div>}</section>
 <aside><div className="info-panel"><span>WHY THIS BAG EXISTS</span><p>{c.project?.name} has allocated <strong>{Number(c.token_allocation).toLocaleString()} {c.reward_asset}</strong> to this campaign. You earn by participating — not by depositing.</p>{access&&<div><LockKeyhole/><span><b>{access.min_bag_score||0}+</b>BagScore requirement • you are {access.your_tier} ({access.your_bag_score})</span></div>}<div><Coins/><span><b>{c.user_share_pct}%</b>User rewards</span></div><div><Trophy/><span><b>{c.nubagz_share_pct}%</b>Platform economy</span></div><div><Sparkles/><span><b>{c.referral_share_pct}%</b>Discovery rewards</span></div></div></aside></div></div>
}
