import { useEffect, useState } from 'react'
import { Gift, LockKeyhole, Plus, ShieldCheck, Sparkles } from 'lucide-react'
import { api } from '../lib/api'
import { useAuth } from '../context/AuthContext'
import type { Project } from '../types'

type DropItem={asset:string;amount_per_claim:string;funded_amount:string;distributed_amount:string}
type Drop={id:number;project_id:number;title:string;rarity:string;status:string;max_claims:number;claims_count:number;remaining_claims:number;min_bag_score:number;funding_status:string;claimed:boolean;items:DropItem[]}

export default function BagDrops(){
 const {user}=useAuth();const [drops,setDrops]=useState<Drop[]>([]);const [projects,setProjects]=useState<Project[]>([]);const [msg,setMsg]=useState('');const [showCreate,setShowCreate]=useState(false)
 const [f,setF]=useState({project_id:0,title:'',rarity:'COMMON',max_claims:100,min_bag_score:0,funding_tx_hash:'',asset:'',amount_per_claim:100,funded_amount:10000})
 const load=()=>{
   if(user?.role==='ADMIN') api<Drop[]>('/bagdrops/admin').then(setDrops).catch(()=>{})
   else if(user?.role==='CREATOR') Promise.all([api<Drop[]>('/bagdrops'),api<Drop[]>('/bagdrops/mine')]).then(([live,mine])=>{const merged=[...mine,...live.filter(d=>!mine.some(m=>m.id===d.id))];setDrops(merged)}).catch(()=>{})
   else api<Drop[]>('/bagdrops').then(setDrops).catch(()=>{})
   if(user?.role==='CREATOR') api<Project[]>('/projects/mine').then(p=>{const live=p.filter(x=>x.status==='LIVE'||x.status==='APPROVED');setProjects(live);if(!f.project_id&&live[0])setF(v=>({...v,project_id:live[0].id,asset:live[0].symbol}))}).catch(()=>{})
 }
 useEffect(()=>{load()},[user?.role])
 const claim=async(id:number)=>{try{const out=await api<{rewards:{asset:string;amount:string}[]}>(`/bagdrops/${id}/claim`,{method:'POST'});setMsg(`Bag opened: ${out.rewards.map(r=>`${r.amount} ${r.asset}`).join(' + ')}`);load()}catch(e:any){setMsg(e.message||'Could not claim BagDrop')}}
 const activate=async(id:number)=>{try{await api(`/bagdrops/${id}/activate`,{method:'POST'});setMsg('BagDrop allocation manually verified by admin and activated.');load()}catch(e:any){setMsg(e.message||'Could not activate BagDrop')}}
 const create=async(e:React.FormEvent)=>{e.preventDefault();try{await api('/bagdrops',{method:'POST',body:JSON.stringify({project_id:f.project_id,title:f.title,rarity:f.rarity,max_claims:f.max_claims,min_bag_score:f.min_bag_score,funding_tx_hash:f.funding_tx_hash,items:[{asset:f.asset,amount_per_claim:f.amount_per_claim,funded_amount:f.funded_amount}]})});setMsg('BagDrop submitted for funding verification.');setShowCreate(false);load()}catch(e:any){setMsg(e.message||'Could not create BagDrop')}}
 return <div className="page"><div className="page-head"><div><span className="eyebrow small">BAGDROPS</span><h1>Open something <em>unexpected.</em></h1><p>Project-funded reward bundles. No NuBagz founder subsidy, no hidden deposit requirement.</p></div>{projects.length>0&&<button className="btn primary" onClick={()=>setShowCreate(!showCreate)}><Plus/> Sponsor BagDrop</button>}</div>{msg&&<div className="form-note">{msg}</div>}
 {showCreate&&<form className="panel builder" onSubmit={create}><h3>Sponsor a funded BagDrop</h3><div className="form-grid"><label>Project<select value={f.project_id} onChange={e=>{const id=Number(e.target.value);const p=projects.find(x=>x.id===id);setF({...f,project_id:id,asset:p?.symbol||f.asset})}}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Rarity<select value={f.rarity} onChange={e=>setF({...f,rarity:e.target.value})}><option>COMMON</option><option>RARE</option><option>EPIC</option><option>LEGENDARY</option></select></label><label className="full-span">Drop title<input required value={f.title} onChange={e=>setF({...f,title:e.target.value})} placeholder="Neon Starter Drop"/></label><label>Max claims<input type="number" min="1" value={f.max_claims} onChange={e=>setF({...f,max_claims:Number(e.target.value)})}/></label><label>Minimum BagScore<input type="number" min="0" max="1000" value={f.min_bag_score} onChange={e=>setF({...f,min_bag_score:Number(e.target.value)})}/></label><label>Reward asset<input required value={f.asset} onChange={e=>setF({...f,asset:e.target.value.toUpperCase()})}/></label><label>Amount per claim<input type="number" min="0" step="any" value={f.amount_per_claim} onChange={e=>setF({...f,amount_per_claim:Number(e.target.value)})}/></label><label>Total funded amount<input type="number" min="0" step="any" value={f.funded_amount} onChange={e=>setF({...f,funded_amount:Number(e.target.value)})}/></label><label>Funding transaction / reference<input required value={f.funding_tx_hash} onChange={e=>setF({...f,funding_tx_hash:e.target.value})}/></label></div><div className={f.funded_amount>=f.amount_per_claim*f.max_claims?'fund-check good':'fund-check bad'}><span>Maximum obligation</span><strong>{(f.amount_per_claim*f.max_claims).toLocaleString()} {f.asset}</strong><small>{f.funded_amount>=f.amount_per_claim*f.max_claims?'✓ Covered':'Increase funded amount'}</small></div><button className="btn primary" disabled={f.funded_amount<f.amount_per_claim*f.max_claims}>Submit BagDrop</button></form>}
 <div className="bag-grid">{drops.map(d=><article className="bag-card" key={d.id}><div className="bag-card-top"><span className="category"><Sparkles/> {d.rarity}</span><span>{d.status==='LIVE'?`${d.remaining_claims} left`:d.status}</span></div><div className="big-token">{d.rarity.slice(0,2)}</div><h3>{d.title}</h3><p>{d.items.map(i=>`${Number(i.amount_per_claim).toLocaleString()} ${i.asset}`).join(' + ')}</p><div className="bag-meta"><span><ShieldCheck/> {d.funding_status==='VERIFIED'?'Funding verified':'Awaiting verification'}</span><span><LockKeyhole/> Score {d.min_bag_score}+</span></div>{d.status==='LIVE'?(d.claimed?<button className="btn ghost full" disabled>Already Bagged ✓</button>:<button className="btn primary full" disabled={(user?.bag_score||0)<d.min_bag_score} onClick={()=>claim(d.id)}><Gift/> Open BagDrop</button>):<button className="btn ghost full" disabled>Pending funding verification</button>}{user?.role==='ADMIN'&&d.status!=='LIVE'&&<button className="mini-action" onClick={()=>activate(d.id)}>Verify funding & activate</button>}</article>)}</div>{!drops.length&&<div className="empty-state"><Gift/><strong>No BagDrops right now.</strong><p>When projects fund new drops, they’ll appear here.</p></div>}</div>
}
