import { useEffect, useState } from 'react'
import { Award, CheckCircle2, FileCheck2, Plus, ShieldCheck } from 'lucide-react'
import { api } from '../lib/api'
import { useAuth } from '../context/AuthContext'
import type { Project } from '../types'

type Bounty={id:number;project_id:number;project_name:string;title:string;description:string;reward_asset:string;reward_per_winner:string;max_winners:number;winners_count:number;remaining_winners:number;funded_amount:string;distributed_amount:string;funding_status:string;status:string;my_submission_status:string|null}
type Submission={id:number;bounty_id:number;bounty_title:string;user_id:number;username:string;evidence:string;status:string;created_at:string}

export default function Bounties(){
 const {user}=useAuth();const [rows,setRows]=useState<Bounty[]>([]);const [projects,setProjects]=useState<Project[]>([]);const [review,setReview]=useState<Submission[]>([]);const [show,setShow]=useState(false);const [msg,setMsg]=useState('')
 const [f,setF]=useState({project_id:0,title:'',description:'',reward_asset:'',reward_per_winner:25,max_winners:10,funded_amount:250,funding_reference:''})
 const load=()=>{
  if(user?.role==='ADMIN') api<Bounty[]>('/bounties/admin').then(setRows).catch(()=>{})
  else if(user?.role==='CREATOR') Promise.all([api<Bounty[]>('/bounties'),api<Bounty[]>('/bounties/mine')]).then(([live,mine])=>setRows([...mine,...live.filter(x=>!mine.some(m=>m.id===x.id))])).catch(()=>{})
  else api<Bounty[]>('/bounties').then(setRows).catch(()=>{})
  if(user?.role==='CREATOR'){
   api<Project[]>('/projects/mine').then(p=>{const approved=p.filter(x=>x.status==='APPROVED');setProjects(approved);if(!f.project_id&&approved[0])setF(v=>({...v,project_id:approved[0].id,reward_asset:approved[0].symbol}))}).catch(()=>{})
   api<Submission[]>('/bounties/review').then(setReview).catch(()=>setReview([]))
  }
 }
 useEffect(()=>{load()},[user?.role])
 const create=async(e:React.FormEvent)=>{e.preventDefault();try{await api('/bounties',{method:'POST',body:JSON.stringify(f)});setMsg('Bounty submitted for funding verification.');setShow(false);load()}catch(e:any){setMsg(e.message||'Could not create bounty')}}
 const activate=async(id:number)=>{try{await api(`/bounties/${id}/activate`,{method:'POST'});setMsg('Bounty funding manually verified and bounty activated.');load()}catch(e:any){setMsg(e.message||'Could not activate bounty')}}
 const submit=async(row:Bounty)=>{const evidence=window.prompt(`Submit evidence for ${row.title}\nPaste a link or describe the completed work.`);if(!evidence)return;try{await api(`/bounties/${row.id}/submit`,{method:'POST',body:JSON.stringify({evidence})});setMsg('Bounty submission sent to the project owner for review.');load()}catch(e:any){setMsg(e.message||'Could not submit bounty')}}
 const decide=async(id:number,status:string)=>{try{await api(`/bounties/submissions/${id}/decision`,{method:'POST',body:JSON.stringify({status})});setMsg(status==='APPROVED'?'Submission approved and funded reward credited.':'Submission rejected.');load()}catch(e:any){setMsg(e.message||'Could not review submission')}}
 const obligation=f.reward_per_winner*f.max_winners
 return <div className="page"><div className="page-head"><div><span className="eyebrow small">FUNDED BOUNTIES</span><h1>Do useful work. <em>Bag the reward.</em></h1><p>Projects pre-fund defined reward pools for research, content, testing and community contributions. NuBagz never invents the payout after the work is done.</p></div>{projects.length>0&&<button className="btn primary" onClick={()=>setShow(!show)}><Plus/> Create bounty</button>}</div>{msg&&<div className="form-note">{msg}</div>}
 {show&&<form className="panel builder" onSubmit={create}><h3>Create a fully funded bounty</h3><div className="form-grid"><label>Project<select value={f.project_id} onChange={e=>{const id=Number(e.target.value);const p=projects.find(x=>x.id===id);setF({...f,project_id:id,reward_asset:p?.symbol||f.reward_asset})}}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Reward asset<input required value={f.reward_asset} onChange={e=>setF({...f,reward_asset:e.target.value.toUpperCase()})}/></label><label className="full-span">Title<input required value={f.title} onChange={e=>setF({...f,title:e.target.value})}/></label><label className="full-span">What needs doing?<textarea required minLength={20} value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></label><label>Reward per winner<input type="number" min="0" step="any" value={f.reward_per_winner} onChange={e=>setF({...f,reward_per_winner:Number(e.target.value)})}/></label><label>Maximum winners<input type="number" min="1" value={f.max_winners} onChange={e=>setF({...f,max_winners:Number(e.target.value)})}/></label><label>Total funded amount<input type="number" min="0" step="any" value={f.funded_amount} onChange={e=>setF({...f,funded_amount:Number(e.target.value)})}/></label><label>Funding transaction / reference<input required value={f.funding_reference} onChange={e=>setF({...f,funding_reference:e.target.value})}/></label></div><div className={f.funded_amount>=obligation?'fund-check good':'fund-check bad'}><span>Maximum obligation</span><strong>{obligation.toLocaleString()} {f.reward_asset}</strong><small>{f.funded_amount>=obligation?'✓ Covered':'Increase funded amount'}</small></div><button className="btn primary" disabled={f.funded_amount<obligation}><Award/> Submit bounty</button></form>}
 {review.some(s=>s.status==='PENDING')&&<section className="panel"><div className="panel-head"><div><span>PROJECT REVIEW</span><h2>Pending bounty submissions</h2></div></div>{review.filter(s=>s.status==='PENDING').map(s=><div className="activity-row" key={s.id}><div><span>{s.bounty_title} • {s.username}</span><strong>{s.evidence}</strong></div><div className="row-actions"><button className="mini-action" onClick={()=>decide(s.id,'APPROVED')}>Approve + pay</button><button className="mini-action" onClick={()=>decide(s.id,'REJECTED')}>Reject</button></div></div>)}</section>}
 <div className="bag-grid">{rows.map(b=><article className="bag-card" key={b.id}><div className="bag-card-top"><span className="category"><Award/> {b.project_name}</span><span>{b.status==='LIVE'?`${b.remaining_winners} rewards left`:b.status}</span></div><div className="big-token">{b.reward_asset.slice(0,3)}</div><h3>{b.title}</h3><p>{b.description}</p><div className="bag-meta"><span><ShieldCheck/> {b.funding_status==='VERIFIED'?'Funding verified':'Awaiting verification'}</span><span>{b.reward_per_winner} {b.reward_asset} / winner</span></div>{b.status==='LIVE'?(b.my_submission_status?<button className="btn ghost full" disabled><CheckCircle2/> Submitted • {b.my_submission_status}</button>:<button className="btn primary full" onClick={()=>submit(b)}><FileCheck2/> Submit work</button>):<button className="btn ghost full" disabled>Not open</button>}{user?.role==='ADMIN'&&b.status==='PENDING'&&<button className="mini-action" onClick={()=>activate(b.id)}>Verify funding & activate</button>}</article>)}</div>{!rows.length&&<div className="empty-state"><Award/><strong>No funded bounties yet.</strong><p>When projects sponsor useful work, opportunities will appear here.</p></div>}</div>
}
