import { useEffect, useState } from 'react'
import { Award, CheckCircle2, FileCheck2, Plus, ShieldCheck } from 'lucide-react'
import { api } from '../lib/api'
import { useAuth } from '../context/AuthContext'
import type { Project } from '../types'

type Bounty={id:number;project_id:number;project_name:string;title:string;description:string;reward_asset:string;reward_per_winner:string;max_winners:number;winners_count:number;remaining_winners:number;funded_amount:string;distributed_amount:string;remaining_funded_amount:string;maximum_obligation:string;funding_status:string;funding_reference?:string;status:string;my_submission_status:string|null}
type Submission={id:number;bounty_id:number;bounty_title:string;user_id:number;username:string;evidence:string;status:string;created_at:string;reviewed_at:string|null}
type VerifyDraft={funded_amount:string;funding_reference:string}

export default function Bounties(){
 const {user}=useAuth();const [rows,setRows]=useState<Bounty[]>([]);const [projects,setProjects]=useState<Project[]>([]);const [review,setReview]=useState<Submission[]>([]);const [history,setHistory]=useState<Submission[]>([]);const [show,setShow]=useState(false);const [msg,setMsg]=useState('');const [submitFor,setSubmitFor]=useState<number|null>(null);const [evidence,setEvidence]=useState('');const [verifyDrafts,setVerifyDrafts]=useState<Record<number,VerifyDraft>>({})
 const [f,setF]=useState({project_id:0,title:'',description:'',reward_asset:'',reward_per_winner:25,max_winners:10,funded_amount:250,funding_reference:''})
 const load=()=>{
  if(user?.role==='ADMIN') api<Bounty[]>('/bounties/admin').then(data=>{setRows(data);setVerifyDrafts(current=>{const next={...current};data.filter(x=>x.status==='PENDING').forEach(x=>{if(!next[x.id])next[x.id]={funded_amount:x.funded_amount,funding_reference:x.funding_reference||''}});return next})}).catch(()=>{})
  else if(user?.role==='CREATOR') Promise.all([api<Bounty[]>('/bounties'),api<Bounty[]>('/bounties/mine')]).then(([live,mine])=>setRows([...mine,...live.filter(x=>!mine.some(m=>m.id===x.id))])).catch(()=>{})
  else api<Bounty[]>('/bounties').then(setRows).catch(()=>{})
  api<Submission[]>('/bounties/submissions/mine').then(setHistory).catch(()=>setHistory([]))
  if(user?.role==='CREATOR'){
   api<Project[]>('/projects/mine').then(p=>{const live=p.filter(x=>x.status==='LIVE'||x.status==='APPROVED');setProjects(live);if(!f.project_id&&live[0])setF(v=>({...v,project_id:live[0].id,reward_asset:live[0].symbol}))}).catch(()=>{})
   api<Submission[]>('/bounties/review').then(setReview).catch(()=>setReview([]))
  }
 }
 useEffect(()=>{load()},[user?.role])
 const create=async(e:React.FormEvent)=>{e.preventDefault();try{await api('/bounties',{method:'POST',body:JSON.stringify(f)});setMsg('Bounty funding declared. An admin must independently verify the funded amount and reference before it becomes live.');setShow(false);load()}catch(e:any){setMsg(e.message||'Could not create bounty')}}
 const activate=async(row:Bounty)=>{const draft=verifyDrafts[row.id]||{funded_amount:row.funded_amount,funding_reference:row.funding_reference||''};try{await api(`/bounties/${row.id}/activate`,{method:'POST',body:JSON.stringify({funded_amount:Number(draft.funded_amount),funding_reference:draft.funding_reference})});setMsg('Funding independently verified and bounty activated.');load()}catch(e:any){setMsg(e.message||'Could not verify bounty funding')}}
 const submit=async(row:Bounty)=>{if(!evidence.trim())return;try{await api(`/bounties/${row.id}/submit`,{method:'POST',body:JSON.stringify({evidence:evidence.trim()})});setMsg('Bounty submission sent to the project owner for review.');setSubmitFor(null);setEvidence('');load()}catch(e:any){setMsg(e.message||'Could not submit bounty')}}
 const decide=async(id:number,status:string)=>{try{await api(`/bounties/submissions/${id}/decision`,{method:'POST',body:JSON.stringify({status})});setMsg(status==='APPROVED'?'Submission approved and funded reward credited once.':'Submission rejected.');load()}catch(e:any){setMsg(e.message||'Could not review submission')}}
 const obligation=f.reward_per_winner*f.max_winners
 return <div className="page"><div className="page-head"><div><span className="eyebrow small">FUNDED BOUNTIES</span><h1>Do useful work. <em>Bag the reward.</em></h1><p>Projects pre-fund defined reward pools for research, content, testing and community contributions. Creator declarations do not make a bounty payable: NuBagz requires independent funding verification before the opportunity goes live.</p></div>{projects.length>0&&<button className="btn primary" onClick={()=>setShow(!show)}><Plus/> Create bounty</button>}</div>{msg&&<div className="form-note">{msg}</div>}
 {show&&<form className="panel builder" onSubmit={create}><h3>Create a fully funded bounty</h3><div className="form-grid"><label>Project<select value={f.project_id} onChange={e=>{const id=Number(e.target.value);const p=projects.find(x=>x.id===id);setF({...f,project_id:id,reward_asset:p?.symbol||f.reward_asset})}}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Reward asset<input required value={f.reward_asset} onChange={e=>setF({...f,reward_asset:e.target.value.toUpperCase()})}/></label><label className="full-span">Title<input required value={f.title} onChange={e=>setF({...f,title:e.target.value})}/></label><label className="full-span">What needs doing?<textarea required minLength={20} value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></label><label>Reward per winner<input type="number" min="0.00000001" step="any" value={f.reward_per_winner} onChange={e=>setF({...f,reward_per_winner:Number(e.target.value)})}/></label><label>Maximum winners<input type="number" min="1" value={f.max_winners} onChange={e=>setF({...f,max_winners:Number(e.target.value)})}/></label><label>Total funded amount<input type="number" min="0.00000001" step="any" value={f.funded_amount} onChange={e=>setF({...f,funded_amount:Number(e.target.value)})}/></label><label>Funding transaction / reference<input required minLength={4} value={f.funding_reference} onChange={e=>setF({...f,funding_reference:e.target.value})}/><small>This is a declaration only until independently verified.</small></label></div><div className={f.funded_amount>=obligation?'fund-check good':'fund-check bad'}><span>Maximum obligation</span><strong>{obligation.toLocaleString()} {f.reward_asset}</strong><small>{f.funded_amount>=obligation?'✓ Declared amount covers maximum payout':'Increase funded amount'}</small></div><button className="btn primary" disabled={f.funded_amount<obligation}><Award/> Submit funding declaration</button></form>}
 {review.some(s=>s.status==='PENDING')&&<section className="panel"><div className="panel-head"><div><span>PROJECT REVIEW</span><h2>Pending bounty submissions</h2></div></div>{review.filter(s=>s.status==='PENDING').map(s=><div className="activity-row" key={s.id}><div><span>{s.bounty_title} • {s.username}</span><strong>{s.evidence}</strong></div><div className="row-actions"><button className="mini-action" onClick={()=>decide(s.id,'APPROVED')}>Approve + pay</button><button className="mini-action" onClick={()=>decide(s.id,'REJECTED')}>Reject</button></div></div>)}</section>}
 <div className="bag-grid">{rows.map(b=><article className="bag-card" key={b.id}><div className="bag-card-top"><span className="category"><Award/> {b.project_name}</span><span>{b.status==='LIVE'?`${b.remaining_winners} rewards left`:b.status}</span></div><div className="big-token">{b.reward_asset.slice(0,3)}</div><h3>{b.title}</h3><p>{b.description}</p><div className="bag-meta"><span><ShieldCheck/> {b.funding_status==='VERIFIED'?'Funding verified':'Funding declared — awaiting independent verification'}</span><span>{b.reward_per_winner} {b.reward_asset} / winner</span></div><div className="bag-meta"><span>Paid: {Number(b.distributed_amount).toLocaleString()} {b.reward_asset}</span><span>Verified pool remaining: {Number(b.remaining_funded_amount).toLocaleString()} {b.reward_asset}</span></div>{b.status==='LIVE'?(b.my_submission_status?<button className="btn ghost full" disabled><CheckCircle2/> Submitted • {b.my_submission_status}</button>:submitFor===b.id?<div><textarea value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="Paste a link or describe the completed work." minLength={4}/><div className="row-actions"><button className="mini-action" disabled={!evidence.trim()} onClick={()=>submit(b)}>Send submission</button><button className="mini-action" onClick={()=>{setSubmitFor(null);setEvidence('')}}>Cancel</button></div></div>:<button className="btn primary full" onClick={()=>{setSubmitFor(b.id);setEvidence('')}}><FileCheck2/> Submit work</button>):<button className="btn ghost full" disabled>Not open</button>}{user?.role==='ADMIN'&&b.status==='PENDING'&&<div><label>Verified funded amount<input type="number" min="0" step="any" value={(verifyDrafts[b.id]?.funded_amount??b.funded_amount)} onChange={e=>setVerifyDrafts({...verifyDrafts,[b.id]:{funded_amount:e.target.value,funding_reference:verifyDrafts[b.id]?.funding_reference??b.funding_reference??''}})}/></label><label>Verified transaction / reference<input value={(verifyDrafts[b.id]?.funding_reference??b.funding_reference??'')} onChange={e=>setVerifyDrafts({...verifyDrafts,[b.id]:{funded_amount:verifyDrafts[b.id]?.funded_amount??b.funded_amount,funding_reference:e.target.value}})}/></label><button className="mini-action" disabled={Number(verifyDrafts[b.id]?.funded_amount??b.funded_amount)<Number(b.maximum_obligation)||(verifyDrafts[b.id]?.funding_reference??b.funding_reference??'').trim().length<4} onClick={()=>activate(b)}>Verify funding & activate</button></div>}</article>)}</div>{!rows.length&&<div className="empty-state"><Award/><strong>No funded bounties yet.</strong><p>When projects sponsor useful work, opportunities will appear here.</p></div>}
 {history.length>0&&<section className="panel"><div className="panel-head"><div><span>YOUR BOUNTY HISTORY</span><h2>Submitted work and decisions</h2></div></div>{history.map(s=><div className="activity-row" key={s.id}><div><span>{s.bounty_title}</span><strong>{s.evidence}</strong></div><b>{s.status}</b></div>)}</section>}</div>
}
