import { useEffect, useState } from 'react'
import { CopyPlus, FileStack, Save, ShieldCheck } from 'lucide-react'
import { api } from '../lib/api'
import type { Campaign, Project } from '../types'

type Template={id:number;name:string;description:string;category:string;difficulty:string;user_share_pct:string;nubagz_share_pct:string;referral_share_pct:string;default_max_users:number;missions:any[];is_system:boolean}

export default function CampaignTemplates(){
 const [templates,setTemplates]=useState<Template[]>([]);const [projects,setProjects]=useState<Project[]>([]);const [campaigns,setCampaigns]=useState<Campaign[]>([]);const [msg,setMsg]=useState('')
 const [use,setUse]=useState({template_id:0,project_id:0,title:'',reward_asset:'',gross_reward_per_user:100,max_users:100,token_allocation:10000})
 const load=()=>Promise.all([api<Template[]>('/templates'),api<Project[]>('/projects/mine'),api<Campaign[]>('/campaigns/mine')]).then(([t,p,c])=>{setTemplates(t);const approved=p.filter(x=>x.status==='APPROVED');setProjects(approved);setCampaigns(c);setUse(v=>({...v,template_id:v.template_id||t[0]?.id||0,project_id:v.project_id||approved[0]?.id||0,reward_asset:v.reward_asset||approved[0]?.symbol||''}))});useEffect(()=>{load()},[])
 const instantiate=async(e:React.FormEvent)=>{e.preventDefault();try{const out=await api<{id:number;status:string;missions_created:number;message:string}>(`/templates/${use.template_id}/instantiate`,{method:'POST',body:JSON.stringify({project_id:use.project_id,title:use.title,reward_asset:use.reward_asset,gross_reward_per_user:use.gross_reward_per_user,max_users:use.max_users,token_allocation:use.token_allocation,funding_type:'TOKEN'})});setMsg(`Campaign #${out.id} created with ${out.missions_created} missions. ${out.message}`);load()}catch(e:any){setMsg(e.message||'Could not instantiate template')}}
 const save=async(c:Campaign)=>{const name=window.prompt('Name this reusable template',`${c.title} template`);if(!name)return;const description=window.prompt('Template description',c.description);if(!description)return;try{await api('/templates/from-campaign',{method:'POST',body:JSON.stringify({campaign_id:c.id,name,description})});setMsg('Custom template saved from your campaign.');load()}catch(e:any){setMsg(e.message||'Could not save template')}}
 const obligation=use.gross_reward_per_user*use.max_users
 return <div className="page"><div className="page-head"><div><span className="eyebrow small">CAMPAIGN TEMPLATES</span><h1>Reuse what <em>works.</em></h1><p>Start from proven mission structures without bypassing funding, validation or approval. Templates create normal pending campaigns.</p></div></div>{msg&&<div className="form-note">{msg}</div>}
 <form className="panel builder" onSubmit={instantiate}><div className="panel-head"><div><span>INSTANTIATE</span><h2>Create from template</h2></div></div><div className="form-grid"><label>Template<select value={use.template_id} onChange={e=>setUse({...use,template_id:Number(e.target.value)})}>{templates.map(t=><option key={t.id} value={t.id}>{t.is_system?'Built-in • ':''}{t.name}</option>)}</select></label><label>Approved project<select value={use.project_id} onChange={e=>{const id=Number(e.target.value);const p=projects.find(x=>x.id===id);setUse({...use,project_id:id,reward_asset:p?.symbol||use.reward_asset})}}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="full-span">Campaign title<input required value={use.title} onChange={e=>setUse({...use,title:e.target.value})}/></label><label>Reward asset<input required value={use.reward_asset} onChange={e=>setUse({...use,reward_asset:e.target.value.toUpperCase()})}/></label><label>Gross reward / user<input type="number" min="0" step="any" value={use.gross_reward_per_user} onChange={e=>setUse({...use,gross_reward_per_user:Number(e.target.value)})}/></label><label>Max users<input type="number" min="1" value={use.max_users} onChange={e=>setUse({...use,max_users:Number(e.target.value)})}/></label><label>Token allocation<input type="number" min="0" step="any" value={use.token_allocation} onChange={e=>setUse({...use,token_allocation:Number(e.target.value)})}/></label></div><div className={use.token_allocation>=obligation?'fund-check good':'fund-check bad'}><span>Maximum obligation</span><strong>{obligation.toLocaleString()} {use.reward_asset}</strong><small>{use.token_allocation>=obligation?'✓ Allocation covers template campaign':'Increase allocation'}</small></div><button className="btn primary" disabled={!use.template_id||!use.project_id||use.token_allocation<obligation}><CopyPlus/> Create pending campaign</button></form>
 <section className="panel"><div className="panel-head"><div><span>LIBRARY</span><h2>Available templates</h2></div></div>{templates.map(t=><div className="activity-row" key={t.id}><div><span>{t.is_system?'BUILT-IN':'YOUR TEMPLATE'} • {t.category} • {t.difficulty}</span><strong>{t.name}</strong><small>{t.description} • {t.missions.length} missions • split {t.user_share_pct}/{t.nubagz_share_pct}/{t.referral_share_pct}</small></div><b>{t.default_max_users.toLocaleString()} default users</b></div>)}</section>
 <section className="panel"><div className="panel-head"><div><span><Save/> SAVE FROM CAMPAIGN</span><h2>Turn your work into a reusable template</h2></div></div>{campaigns.slice(0,10).map(c=><div className="activity-row" key={c.id}><div><span>{c.status}</span><strong>{c.title}</strong></div><button className="mini-action" onClick={()=>save(c)}><FileStack/> Save template</button></div>)}</section><div className="custody-note"><ShieldCheck/><p>Templates never carry verified funding or approval state forward. Every new campaign must fund and activate independently.</p></div></div>
}