import { useEffect, useState } from 'react'
import { AlertTriangle, ArrowRight, BarChart3, CheckCircle2, Coins, Eye, Fuel, LockKeyhole, Pause, Play, Plus, Rocket, ShieldCheck, Users, XCircle } from 'lucide-react'
import { Link, useSearchParams } from 'react-router-dom'
import CreatorTrustModal from '../components/CreatorTrustModal'
import { api } from '../lib/api'
import { formatTokenAmount, tokenAmountTitle } from '../lib/formatToken'
import type { Campaign, Project } from '../types'

type Funding={campaign_id:number;asset:string;required_amount:string;declared_amount:string;verified_amount:string;status:string;fully_funded:boolean;tx_hash?:string|null;campaign_status?:string;active_work_count?:number;discoverable?:boolean;discoverability_blockers?:string[]}
type AccessRule={campaign_id:number;min_bag_score:number;eligible:boolean;your_bag_score:number}
type WorkSubmission={id:number;challenge_id:number;challenge_title:string;campaign_title:string;project_name:string;username:string;evidence?:{submission?:string}|null;submitted_at:string}
type GasPolicy={id:number;challenge_id:number;challenge_title:string;campaign_id:number;campaign_title:string;project_id:number;project_name:string;chain:string;native_asset:string;max_native_per_claim:string;max_unique_users?:number|null;max_claims:number;max_claims_per_wallet:number;funded_amount:string;spent_amount:string;remaining_funded_amount:string;executed_claims:number;reserved_claims:number;unique_users:number;funding_reference:string;funding_status:string;status:string;starts_at?:string|null;ends_at?:string|null}
type TrustSummary={project_id:number;score:number;level:string;evidence:{status:string};metrics:{campaigns:number;verified_funded_campaigns:number}}

const blockerText=(code:string)=>({PROJECT_NOT_PUBLIC:'Project is not currently public',NO_ACTIVE_BAG_WORK:'No active Bag Work activities',FUNDING_NOT_VERIFIED:'Reward funding has not been verified',FUNDING_BELOW_MAX_LIABILITY:'Verified funding is below maximum reward liability',BAG_PAUSED:'Bag is paused by the creator',BAG_SUSPENDED:'Bag is suspended by moderation',BAG_ARCHIVED:'Bag is archived',BAG_NOT_LIVE:'Bag is not in a public lifecycle state'}[code]||code.replaceAll('_',' '))

export default function CreatorStudio(){
 const [params]=useSearchParams();const [projects,setProjects]=useState<Project[]>([]);const [campaigns,setCampaigns]=useState<Campaign[]>([]);const [funding,setFunding]=useState<Funding[]>([]);const [access,setAccess]=useState<AccessRule[]>([]);const [submissions,setSubmissions]=useState<WorkSubmission[]>([]);const [gas,setGas]=useState<GasPolicy[]>([]);const [trust,setTrust]=useState<Record<number,TrustSummary>>({});const [trustProject,setTrustProject]=useState<Project|null>(null);const [msg,setMsg]=useState(params.get('created')?'Project created and published. Your first Bag is waiting for reward-funding verification; once fully verified it will become live in Bag Work automatically.':params.get('bagCreated')?'Bag draft created. Once its reward funding is fully verified it will become live in Bag Work automatically.':'')
 const load=()=>Promise.all([api<Project[]>('/projects/mine'),api<Campaign[]>('/campaigns/mine'),api<Funding[]>('/funding/mine'),api<WorkSubmission[]>('/challenges/submissions/project'),api<GasPolicy[]>('/gas/policies/mine')]).then(async([p,c,f,s,g])=>{setProjects(p);setCampaigns(c);setFunding(f);setSubmissions(s);setGas(g);const trustRows=await Promise.all(p.filter(x=>x.status!=='ARCHIVED'&&x.status!=='SUSPENDED').map(x=>api<TrustSummary>(`/trust/projects/${x.id}`).catch(()=>null)));setTrust(Object.fromEntries(trustRows.filter(Boolean).map(row=>[(row as TrustSummary).project_id,row as TrustSummary])));Promise.all(c.map(x=>api<AccessRule>(`/access/campaigns/${x.id}`))).then(setAccess).catch(()=>setAccess([]))}).catch(()=>{})
 useEffect(()=>{void load()},[])
 const allocated=campaigns.reduce((a,c)=>a+Number(c.token_allocation),0);const participants=campaigns.reduce((a,c)=>a+c.enrolled_count,0);const liveProjects=projects.filter(p=>p.status==='LIVE'||p.status==='APPROVED');const discoverableBagz=funding.filter(f=>f.discoverable).length
 const declare=async(c:Campaign)=>{const f=funding.find(x=>x.campaign_id===c.id);const requiredRaw=f?.required_amount||String(Number(c.gross_reward_per_user)*c.max_users);const tx=window.prompt(`Reward funding transaction / reference for ${c.title}\nMaximum obligation: ${formatTokenAmount(requiredRaw)} ${c.reward_asset}`);if(tx===null)return;try{await api(`/funding/campaigns/${c.id}/declare`,{method:'POST',body:JSON.stringify({amount:Number(c.token_allocation),tx_hash:tx||null})});setMsg('Reward funding declared. NuBagz verifies the reward inventory only; once the full obligation is verified this Bag will go live automatically.');await load()}catch(e:any){setMsg(e.message||'Could not declare funding')}}
 const publish=async(c:Campaign)=>{try{await api(`/campaigns/${c.id}/publish`,{method:'POST'});setMsg(`${c.title} is live again.`);await load()}catch(e:any){setMsg(e.message||'This Bag is not publishable yet')}}
 const pause=async(c:Campaign)=>{try{await api(`/campaigns/${c.id}/pause`,{method:'POST'});setMsg(`${c.title} paused. It is hidden from Bag Work until you resume it.`);await load()}catch(e:any){setMsg(e.message||'Could not pause this Bag')}}
 const setGate=async(c:Campaign)=>{const current=access.find(a=>a.campaign_id===c.id)?.min_bag_score||0;const raw=window.prompt(`Minimum BagScore for ${c.title}\n0 = open to everyone\n200 = Explorer\n400 = Contributor\n600 = Premium\n800 = Elite`,String(current));if(raw===null)return;const score=Number(raw);if(!Number.isInteger(score)||score<0||score>1000){setMsg('BagScore gate must be a whole number from 0 to 1000.');return}try{await api(`/access/campaigns/${c.id}`,{method:'POST',body:JSON.stringify({min_bag_score:score})});setMsg(score?`BagScore ${score}+ is now required for new enrollments.`:'BagScore gate removed.');await load()}catch(e:any){setMsg(e.message||'Could not update BagScore gate')}}
 const decide=async(id:number,status:'APPROVED'|'REJECTED')=>{try{const r=await api<{completed:boolean}>(`/challenges/completions/${id}/decision`,{method:'POST',body:JSON.stringify({status})});setMsg(status==='APPROVED'?(r.completed?'Participant proof accepted and the worker completed the Bag.':'Participant proof accepted. Remaining Bag Work is still required.'):'Participant proof rejected. The worker can correct the evidence and resubmit.');await load()}catch(e:any){setMsg(e.message||'Could not review this proof')}}
 const pathState=(c:Campaign,f?:Funding)=>{if(f?.discoverable)return 4;if(f?.fully_funded)return 3;if(f?.status==='DECLARED')return 2;return 1}
 return <div className="page"><div className="page-head"><div><span className="eyebrow small">CREATOR STUDIO</span><h1>Project, Bags and work. <em>One place.</em></h1><p>Create the launch, maintain your project Trust profile, fund Bags, review participant evidence and manage optional sponsored gas without mixing creator controls into public discovery.</p></div><Link to="/app/studio/projects/new" className="btn primary"><Plus/> Create project + first Bag</Link></div>{msg&&<div className="form-note">{msg}</div>}
 <div className="stats-grid creator-stats"><div className="stat-card"><span><Rocket/>PROJECTS</span><strong>{projects.length}</strong><small>{liveProjects.length} live</small></div><div className="stat-card"><span><Coins/>ALLOCATED</span><strong>{formatTokenAmount(String(allocated))}</strong><small>Configured reward allocation</small></div><div className="stat-card"><span><Users/>PARTICIPANTS</span><strong>{participants.toLocaleString()}</strong><small>Bag enrollments</small></div><div className="stat-card hot"><span><BarChart3/>DISCOVERABLE BAGZ</span><strong>{discoverableBagz}</strong><small>Actually visible in Bag Work</small></div></div>
 <div className="studio-grid"><section className="panel"><div className="panel-head"><div><span>YOUR PROJECTS</span><h2>Projects & Trust</h2></div></div>{projects.length?projects.map(p=>{const t=trust[p.id];return <div className="project-row" key={p.id}><div className="big-token smallish">{p.symbol.slice(0,4)}</div><div><strong>{p.name}</strong><small>{p.chain} • ${p.symbol}</small><div className="creator-project-meta"><span>{p.status==='APPROVED'?'LIVE':p.status}</span>{t?<><span>Trust {t.score}/100 • {t.level}</span><span className={t.evidence.status==='VERIFIED'?'verified':''}>Evidence {t.evidence.status.replace(/_/g,' ')}</span></>:<span>Trust unavailable</span>}</div></div><div className="row-actions">{(p.status==='LIVE'||p.status==='APPROVED')&&<><button className="mini-action" type="button" onClick={()=>setTrustProject(p)}><ShieldCheck/> Manage Trust</button><Link className="mini-action" to={`/app/studio/campaigns/new?project=${p.id}`}>Create another Bag <ArrowRight/></Link></>}</div></div>}):<div className="empty-state"><Rocket/><strong>No project yet.</strong><p>Start with the guided launch. It creates the project, Trust information, first Bag, Bag Work and funding declaration together.</p><Link className="btn primary" to="/app/studio/projects/new">Create project + first Bag</Link></div>}</section>
 <section className="panel"><div className="panel-head"><div><span>YOUR BAGZ</span><h2>Configure → fund → discoverable</h2></div></div>{campaigns.length?campaigns.slice(0,20).map(c=>{const f=funding.find(x=>x.campaign_id===c.id);const a=access.find(x=>x.campaign_id===c.id);const canResume=Boolean(f?.fully_funded&&Number(f?.active_work_count||0)>0)&&c.status==='PAUSED';const state=pathState(c,f);const blockers=f?.discoverability_blockers||[];const requiredRaw=f?.required_amount||String(Number(c.gross_reward_per_user)*c.max_users);return <div className="campaign-mini" key={c.id}><div><strong>{c.title}</strong><small>{c.enrolled_count.toLocaleString()} joined • {c.completed_count.toLocaleString()} completed • {f?.active_work_count??0} active Bag Work • BagScore {a?.min_bag_score||0}+</small><div className="funding-state-line"><ShieldCheck size={12}/><span>Maximum liability <b title={tokenAmountTitle(requiredRaw)}>{formatTokenAmount(requiredRaw)} {c.reward_asset}</b></span><b>{f?.fully_funded?`VERIFIED ${formatTokenAmount(f.verified_amount)}`:f?.status==='DECLARED'?`DECLARED ${formatTokenAmount(f.declared_amount)}`:'UNFUNDED'}</b></div><div className="publish-path"><span className={state===1?'current':''}>1 Configure</span><span className={state===2?'current':''}>2 Declare funding</span><span className={state===3?'current':''}>3 Funding verified</span><span className={state===4?'current':''}>4 Discoverable in Bag Work</span></div>{!f?.discoverable&&blockers.length>0&&<div className="builder-note"><AlertTriangle/><p><strong>Not discoverable:</strong> {blockers.map(blockerText).join(' • ')}</p></div>}</div><span className={`status ${(f?.discoverable?'live':c.status).toLowerCase()}`}>{f?.discoverable?'DISCOVERABLE':c.status==='PENDING'?'DRAFT':c.status}</span><div className="row-actions">{!f||f.status==='UNFUNDED'||(!f.fully_funded&&f.status!=='DECLARED')?<button className="mini-action" onClick={()=>void declare(c)}>Declare funding</button>:null}{f?.status==='DECLARED'&&!f.fully_funded&&<button className="mini-action" disabled title="NuBagz verifies reward inventory; this is not project approval.">Awaiting funding verification</button>}{canResume&&<button className="mini-action approve" onClick={()=>void publish(c)}><Play/> Resume</button>}{f?.discoverable&&<><Link className="mini-action approve" to={`/app/bagz/${c.id}?return=${encodeURIComponent('/app/studio')}`}><Eye/> View Bag</Link><button className="mini-action" onClick={()=>void pause(c)}><Pause/> Pause</button></>}<button className="mini-action" onClick={()=>void setGate(c)}><LockKeyhole/> Score gate</button></div></div>}):<div className="empty-state"><Coins/><strong>No Bags yet.</strong><p>The first Bag is created by the guided project launch. After that, add as many new Bags as the project needs.</p></div>}</section></div>
 {gas.length>0&&<section className="panel"><div className="panel-head"><div><span><Fuel/> SPONSORED GAS INSIDE BAG WORK</span><h2>Optional Gas Pass policies</h2></div></div><p>Gas Pass is not a separate product area. Each policy belongs to one on-chain Bag Work activity. When its time, user, claim or budget limit ends, the same activity continues with normal user-paid network gas.</p>{gas.map(g=><div className="activity-row" key={g.id}><div><span>{g.project_name} • {g.campaign_title} • {g.chain}</span><strong>{g.challenge_title}</strong><small>{g.unique_users}{g.max_unique_users?`/${g.max_unique_users}`:''} eligible users • {g.executed_claims}/{g.max_claims} executed • {g.reserved_claims} reserved</small><small>{formatTokenAmount(g.spent_amount)}/{formatTokenAmount(g.funded_amount)} {g.native_asset} spent • funding {g.funding_status}</small></div><span className={`status ${g.status.toLowerCase()}`}>{g.status}</span></div>)}</section>}
 {submissions.length>0&&<section className="panel work-review-panel"><div className="panel-head"><div><span>PROJECT-REVIEWED BAG WORK</span><h2>Participant evidence you chose to review</h2></div><span className="review-count">{submissions.length} to review</span></div><div className="builder-note"><ShieldCheck/><p>These are participant proofs only for activities configured as <strong>Project review</strong>. Automatic X, on-chain and quiz verification never enter this queue.</p></div><div className="work-review-list">{submissions.map(s=><div className="work-review-row" key={s.id}><div><strong>{s.challenge_title}</strong><small>{s.project_name} · {s.campaign_title} · @{s.username}</small><p>{s.evidence?.submission||'No evidence text supplied.'}</p><small>Submitted {new Date(s.submitted_at).toLocaleString()}</small></div><div className="row-actions"><button className="mini-action approve" onClick={()=>void decide(s.id,'APPROVED')}><CheckCircle2/> Accept proof</button><button className="mini-action reject" onClick={()=>void decide(s.id,'REJECTED')}><XCircle/> Reject proof</button></div></div>)}</div></section>}
 <div className="creator-explainer"><span>HOW CREATOR PUBLISHING WORKS</span><div><b>01</b><h3>Project publishes without endorsement</h3><p>Project Trust replaces blanket approval. Verified and unverified signals stay distinct so users can assess the project themselves.</p></div><div><b>02</b><h3>Reward inventory must be real</h3><p>The Bag stays DRAFT while NuBagz independently verifies that its maximum reward liability is fully funded.</p></div><div><b>03</b><h3>Verified funding makes it discoverable</h3><p>Once full reward funding is verified and active Bag Work exists, a new Bag automatically becomes discoverable. You can pause and resume it here.</p></div><div><b>04</b><h3>Every completion has evidence</h3><p>Use automatic verification, quiz verification or project-reviewed proof. There is no one-click self-attestation reward path.</p></div></div>{trustProject&&<CreatorTrustModal project={trustProject} onClose={()=>setTrustProject(null)} onSaved={()=>void load()}/>}</div>
}
