import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, ArrowRight, Coins, Plus, Trash2, Zap } from 'lucide-react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { api } from '../lib/api'
import type { Project } from '../types'

type MissionDraft={title:string;description:string;mission_type:string;verification_type:string;quiz_question?:string;quiz_options?:string;quiz_answer?:string;xp_reward:number}
const blankMission=():MissionDraft=>({title:'',description:'',mission_type:'LEARN',verification_type:'SELF_ATTEST',xp_reward:50})
export default function CreateCampaign(){const [params]=useSearchParams();const nav=useNavigate();const [projects,setProjects]=useState<Project[]>([]);const [missions,setMissions]=useState<MissionDraft[]>([blankMission()]);const [error,setError]=useState('');const [f,setF]=useState({project_id:Number(params.get('project')||0),title:'',description:'',category:'DISCOVER',difficulty:'EASY',reward_asset:'',funding_type:'TOKEN',token_allocation:100000,gross_reward_per_user:100,max_users:1000,user_share_pct:80,nubagz_share_pct:15,referral_share_pct:5,estimated_value_gbp:''})
 useEffect(()=>{api<Project[]>('/projects/mine').then(p=>{const approved=p.filter(x=>x.status==='APPROVED');setProjects(approved);if(!f.project_id&&approved[0])setF(v=>({...v,project_id:approved[0].id,reward_asset:approved[0].symbol}))})},[])
 const required=useMemo(()=>Number(f.gross_reward_per_user)*Number(f.max_users),[f]);const userReward=Number(f.gross_reward_per_user)*Number(f.user_share_pct)/100
 const updateMission=(i:number,key:keyof MissionDraft,val:any)=>setMissions(ms=>ms.map((m,idx)=>idx===i?{...m,[key]:val}:m))
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');try{await api('/campaigns',{method:'POST',body:JSON.stringify({...f,estimated_value_gbp:f.estimated_value_gbp?Number(f.estimated_value_gbp):null,missions:missions.map(m=>({...m,quiz_options:m.quiz_options?m.quiz_options.split(',').map(x=>x.trim()):null}))})});nav('/app/studio')}catch(e:any){setError(e.message)}}
 return <div className="page narrow wide-builder"><Link to="/app/studio" className="back-link"><ArrowLeft/> Creator Studio</Link><div className="form-hero"><Coins/><span>NEW BAG</span><h1>Turn token supply into <em>participation.</em></h1><p>Your allocation must fully cover the maximum reward obligation. NuBagz does not front the rewards.</p></div><form className="builder panel" onSubmit={submit}><h3>01 — Campaign basics</h3><div className="form-grid"><label>Project<select value={f.project_id} onChange={e=>{const id=Number(e.target.value);const p=projects.find(x=>x.id===id);setF({...f,project_id:id,reward_asset:p?.symbol||f.reward_asset})}}>{projects.map(p=><option value={p.id} key={p.id}>{p.name} (${p.symbol})</option>)}</select></label><label>Category<select value={f.category} onChange={e=>setF({...f,category:e.target.value})}><option>DISCOVER</option><option>LEARN</option><option>PLAY</option><option>CREATE</option></select></label><label className="full-span">Bag title<input required value={f.title} onChange={e=>setF({...f,title:e.target.value})} placeholder="Enter the Neon Swamp"/></label><label className="full-span">Description<textarea required minLength={20} value={f.description} onChange={e=>setF({...f,description:e.target.value})} placeholder="What will users discover or achieve?"/></label></div>
 <h3>02 — Reward economics</h3><div className="form-grid four"><label>Reward asset<input required value={f.reward_asset} onChange={e=>setF({...f,reward_asset:e.target.value.toUpperCase()})}/></label><label>Total allocation<input type="number" min="1" value={f.token_allocation} onChange={e=>setF({...f,token_allocation:Number(e.target.value)})}/></label><label>Gross / completion<input type="number" min="0.000001" step="any" value={f.gross_reward_per_user} onChange={e=>setF({...f,gross_reward_per_user:Number(e.target.value)})}/></label><label>Max users<input type="number" min="1" value={f.max_users} onChange={e=>setF({...f,max_users:Number(e.target.value)})}/></label></div><div className={required<=f.token_allocation?'fund-check good':'fund-check bad'}><span>Maximum obligation</span><strong>{required.toLocaleString()} {f.reward_asset||'TOKEN'}</strong><small>{required<=f.token_allocation?'✓ Fully covered by allocation':'Allocation is too small'}</small></div><div className="split-builder"><label>User share<input type="number" value={f.user_share_pct} onChange={e=>setF({...f,user_share_pct:Number(e.target.value)})}/><span>%</span></label><label>NuBagz share<input type="number" value={f.nubagz_share_pct} onChange={e=>setF({...f,nubagz_share_pct:Number(e.target.value)})}/><span>%</span></label><label>Referral share<input type="number" value={f.referral_share_pct} onChange={e=>setF({...f,referral_share_pct:Number(e.target.value)})}/><span>%</span></label><div><small>User earns per completion</small><strong>{userReward.toLocaleString()} {f.reward_asset}</strong></div></div>
 <h3>03 — Mission path</h3><div className="mission-builder">{missions.map((m,i)=><div className="mission-draft" key={i}><div className="draft-head"><b>{String(i+1).padStart(2,'0')}</b><span>Mission</span>{missions.length>1&&<button type="button" onClick={()=>setMissions(ms=>ms.filter((_,idx)=>idx!==i))}><Trash2/></button>}</div><div className="form-grid"><label>Title<input required value={m.title} onChange={e=>updateMission(i,'title',e.target.value)} placeholder="Meet the project"/></label><label>Type<select value={m.mission_type} onChange={e=>updateMission(i,'mission_type',e.target.value)}><option>LEARN</option><option>DISCOVER</option><option>PLAY</option><option>CREATE</option></select></label><label>Verification<select value={m.verification_type} onChange={e=>updateMission(i,'verification_type',e.target.value)}><option value="SELF_ATTEST">Completion button</option><option value="QUIZ">Quiz answer</option></select></label><label>XP reward<input type="number" value={m.xp_reward} onChange={e=>updateMission(i,'xp_reward',Number(e.target.value))}/></label><label className="full-span">Description<input value={m.description} onChange={e=>updateMission(i,'description',e.target.value)}/></label>{m.verification_type==='QUIZ'&&<><label className="full-span">Quiz question<input required value={m.quiz_question||''} onChange={e=>updateMission(i,'quiz_question',e.target.value)}/></label><label>Options <small>comma separated</small><input required value={m.quiz_options||''} onChange={e=>updateMission(i,'quiz_options',e.target.value)} placeholder="NFROG, BTC, NONE"/></label><label>Correct answer<input required value={m.quiz_answer||''} onChange={e=>updateMission(i,'quiz_answer',e.target.value)}/></label></>}</div></div>)}</div><button type="button" className="add-mission" onClick={()=>setMissions(ms=>[...ms,blankMission()])}><Plus/> Add mission</button>{error&&<div className="form-error">{error}</div>}<button className="btn primary big" disabled={required>f.token_allocation}>Submit Bag for review <ArrowRight/></button></form></div>
}
