import { useEffect, useState } from 'react'
import { ArrowRight, BarChart3, Coins, Plus, Rocket, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import { api } from '../lib/api'
import type { Campaign, Project } from '../types'

export default function CreatorStudio(){const [projects,setProjects]=useState<Project[]>([]);const [campaigns,setCampaigns]=useState<Campaign[]>([]);useEffect(()=>{Promise.all([api<Project[]>('/projects/mine'),api<Campaign[]>('/campaigns/mine')]).then(([p,c])=>{setProjects(p);setCampaigns(c)}).catch(()=>{})},[])
 const allocated=campaigns.reduce((a,c)=>a+Number(c.token_allocation),0);const participants=campaigns.reduce((a,c)=>a+c.enrolled_count,0)
 return <div className="page"><div className="page-head"><div><span className="eyebrow small">CREATOR STUDIO</span><h1>Turn supply into <em>participation.</em></h1><p>Create funded Bagz with token inventory you already control. No giant ad budget required.</p></div><Link to="/app/studio/projects/new" className="btn primary"><Plus/> Add project</Link></div>
 <div className="stats-grid creator-stats"><div className="stat-card"><span><Rocket/>PROJECTS</span><strong>{projects.length}</strong><small>{projects.filter(p=>p.status==='APPROVED').length} approved</small></div><div className="stat-card"><span><Coins/>ALLOCATED</span><strong>{allocated.toLocaleString()}</strong><small>Across all reward assets</small></div><div className="stat-card"><span><Users/>PARTICIPANTS</span><strong>{participants.toLocaleString()}</strong><small>Campaign enrollments</small></div><div className="stat-card hot"><span><BarChart3/>LIVE BAGZ</span><strong>{campaigns.filter(c=>c.status==='LIVE').length}</strong><small>In the marketplace</small></div></div>
 <div className="studio-grid"><section className="panel"><div className="panel-head"><div><span>YOUR PROJECTS</span><h2>Project roster</h2></div></div>{projects.length?projects.map(p=><div className="project-row" key={p.id}><div className="big-token smallish">{p.symbol.slice(0,4)}</div><div><strong>{p.name}</strong><small>{p.chain} • ${p.symbol}</small></div><span className={`status ${p.status.toLowerCase()}`}>{p.status}</span>{p.status==='APPROVED'&&<Link to={`/app/studio/campaigns/new?project=${p.id}`}>Create Bag <ArrowRight/></Link>}</div>):<div className="empty-state"><Rocket/><strong>No project yet.</strong><p>Add your project. NuBagz will review it before you can distribute rewards.</p><Link to="/app/studio/projects/new">Add project</Link></div>}</section>
 <section className="panel"><div className="panel-head"><div><span>YOUR BAGZ</span><h2>Campaigns</h2></div></div>{campaigns.length?campaigns.slice(0,6).map(c=><div className="campaign-mini" key={c.id}><div><strong>{c.title}</strong><small>{c.enrolled_count.toLocaleString()} joined • {c.completed_count.toLocaleString()} completed</small></div><span className={`status ${c.status.toLowerCase()}`}>{c.status}</span></div>):<div className="empty-state"><Coins/><strong>No campaigns yet.</strong><p>Once a project is approved, turn its token allocation into a NuBag.</p></div>}</section></div>
 <div className="creator-explainer"><span>HOW NUBAGZ MAKES THIS SUSTAINABLE</span><div><b>01</b><h3>You allocate token inventory</h3><p>No mandatory cash ad spend. Your allocation must cover the rewards you promise.</p></div><div><b>02</b><h3>NuBagz splits every completion</h3><p>User, platform and referral/community shares are calculated transparently at completion.</p></div><div><b>03</b><h3>You get measurable participation</h3><p>Track enrollments, completions and the exact amount of inventory distributed.</p></div></div></div>
}
