import { useEffect, useMemo, useState } from 'react'
import { ArrowDownToLine, Coins, FileDown, Gem, History, ReceiptText, ShieldCheck, Sparkles, TrendingUp } from 'lucide-react'
import { api, apiDownload } from '../lib/api'

type AssetAmount={asset:string;amount:string}
type Valuation={asset:string;available_amount:string;current_price_gbp:string|null;current_value_gbp:string|null;original_estimated_value_gbp:string|null;change_pct:string|null}
type Summary={lifetime:AssetAmount[];available:AssetAmount[];pending:AssetAmount[];withdrawn:AssetAmount[];referral:AssetAmount[];unique_assets:number;total_current_value_gbp:string;total_original_estimated_value_gbp:string;valuations:Valuation[];monthly:{month:string;assets:AssetAmount[]}[]}
type TaxReceipt={id:number;received_at:string;asset:string;amount:string;entry_type:string;status:string;campaign_title:string|null;note:string|null;estimated_value_gbp:string|null;valuation_source:string}
type TaxWithdrawal={id:number;requested_at:string;asset:string;amount:string;status:string;chain:string;wallet_address:string;tx_hash:string|null;estimated_value_gbp:string|null;valuation_source:string}
type TaxReport={year:number;basis:string;generated_at:string;available_years:number[];receipt_count:number;withdrawal_count:number;estimated_receipts_gbp:string;estimated_withdrawals_gbp:string;unpriced_receipt_count:number;unpriced_withdrawal_count:number;receipts_by_asset:AssetAmount[];withdrawals_by_asset:AssetAmount[];receipts:TaxReceipt[];withdrawals:TaxWithdrawal[];disclaimer:string}

const totalUnits=(rows:AssetAmount[])=>rows.reduce((sum,row)=>sum+Number(row.amount||0),0)
const money=(value:string|number|null|undefined)=>value===null||value===undefined?'—':`£${Number(value).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`

export default function Earnings(){
 const [data,setData]=useState<Summary|null>(null);const [year,setYear]=useState(new Date().getFullYear());const [tax,setTax]=useState<TaxReport|null>(null);const [msg,setMsg]=useState('')
 useEffect(()=>{api<Summary>('/earnings/summary').then(setData)},[])
 useEffect(()=>{api<TaxReport>(`/earnings/tax-report?year=${year}`).then(setTax).catch((e:any)=>setMsg(e.message||'Could not load yearly earnings statement'))},[year])
 const lifetimeUnits=useMemo(()=>totalUnits(data?.lifetime||[]),[data])
 const download=async()=>{try{const name=await apiDownload(`/earnings/tax-export.csv?year=${year}`,`nubagz-earnings-${year}.csv`);setMsg(`${name} downloaded.`)}catch(e:any){setMsg(e.message||'Could not download earnings CSV')}}
 return <div className="page"><div className="page-head"><div><span className="eyebrow small">EARNINGS CENTRE</span><h1>Everything you’ve <em>Bagged.</em></h1><p>Track earned assets, what they were worth when you earned them, what your available rewards are worth now, and export a yearly activity statement.</p></div></div>{msg&&<div className="form-note">{msg}</div>}
 <div className="stats-grid"><div className="stat-card hot"><span><Sparkles/>CURRENT TRACKED VALUE</span><strong>{money(data?.total_current_value_gbp)}</strong><small>Available rewards with a price feed</small></div><div className="stat-card"><span><History/>ORIGINAL ESTIMATE</span><strong>{money(data?.total_original_estimated_value_gbp)}</strong><small>Estimated value when Bagged</small></div><div className="stat-card"><span><Gem/>ASSETS BAGGED</span><strong>{data?.unique_assets??'—'}</strong><small>{lifetimeUnits.toLocaleString(undefined,{maximumFractionDigits:2})} lifetime token units</small></div><div className="stat-card"><span><ArrowDownToLine/>WITHDRAWALS</span><strong>{data?.withdrawn.length??'—'}</strong><small>Assets with settled withdrawals</small></div></div>
 <section className="panel"><div className="panel-head"><div><span><TrendingUp/> REWARD VALUE TRACKER</span><h2>What happened to your Bagz?</h2></div></div>{data?.valuations.length?data.valuations.map(v=><div className="activity-row" key={v.asset}><div><span>{v.asset}</span><strong>{Number(v.available_amount).toLocaleString(undefined,{maximumFractionDigits:8})} available</strong></div><b>{v.current_value_gbp?money(v.current_value_gbp):'Price unavailable'}</b><small>{v.original_estimated_value_gbp?`Bagged at ~${money(v.original_estimated_value_gbp)}${v.change_pct?` • ${Number(v.change_pct)>=0?'+':''}${Number(v.change_pct).toFixed(1)}%`:''}`:'Original value not recorded'}</small></div>):<div className="empty-state"><Coins/><strong>No valued rewards yet.</strong><p>When a supported reward gets a GBP price snapshot, its current value appears here automatically.</p></div>}</section>
 <div className="two-col"><section className="panel"><div className="panel-head"><div><span>LIFETIME EARNINGS</span><h2>Assets earned</h2></div></div>{data?.lifetime.length?data.lifetime.map(row=><div className="treasury-row" key={row.asset}><strong>{row.asset}</strong><b>{Number(row.amount).toLocaleString(undefined,{maximumFractionDigits:8})}</b></div>):<div className="empty-state"><Coins/><strong>No earnings yet.</strong><p>Complete your first funded Bag to start your earnings history.</p></div>}</section>
 <section className="panel"><div className="panel-head"><div><span>REFERRAL INCOME</span><h2>Earn when your people Bag</h2></div></div>{data?.referral.length?data.referral.map(row=><div className="treasury-row" key={row.asset}><strong>{row.asset}</strong><b>{Number(row.amount).toLocaleString(undefined,{maximumFractionDigits:8})}</b></div>):<div className="empty-state"><Sparkles/><strong>No referral earnings yet.</strong><p>Share your NuBagz referral code and earn from funded campaign referral allocations.</p></div>}</section></div>
 <section className="panel"><div className="panel-head"><div><span><ReceiptText/> YEARLY EARNINGS STATEMENT</span><h2>Estimated receipts & transaction history</h2></div><div className="row-actions"><select value={year} onChange={e=>setYear(Number(e.target.value))}>{(tax?.available_years?.length?tax.available_years:[year]).map(y=><option key={y} value={y}>{y}</option>)}</select><button className="btn primary" onClick={download}><FileDown/> Download CSV</button></div></div>
 <div className="bag-summary"><div><span>ESTIMATED RECEIPTS</span><strong>{money(tax?.estimated_receipts_gbp)}</strong><small>{tax?.receipt_count??0} earning records</small></div><div><span>WITHDRAWAL REQUESTS</span><strong>{tax?.withdrawal_count??0}</strong><small>{money(tax?.estimated_withdrawals_gbp)} historically priced</small></div><div><span>UNPRICED EVENTS</span><strong>{(tax?.unpriced_receipt_count??0)+(tax?.unpriced_withdrawal_count??0)}</strong><small>Left blank rather than back-filled</small></div></div>
 {tax?.receipts.slice().reverse().slice(0,8).map(r=><div className="activity-row" key={`receipt-${r.id}`}><div><span>{new Date(r.received_at).toLocaleDateString()} • {r.entry_type}</span><strong>{Number(r.amount).toLocaleString(undefined,{maximumFractionDigits:8})} {r.asset}</strong><small>{r.campaign_title||r.note||'NuBagz earning'} • {r.valuation_source.replaceAll('_',' ')}</small></div><b>{r.estimated_value_gbp?`~${money(r.estimated_value_gbp)}`:'Unpriced'}</b></div>)}
 {tax?.withdrawals.slice().reverse().slice(0,5).map(w=><div className="activity-row" key={`withdrawal-${w.id}`}><div><span>{new Date(w.requested_at).toLocaleDateString()} • WITHDRAWAL • {w.status}</span><strong>{Number(w.amount).toLocaleString(undefined,{maximumFractionDigits:8})} {w.asset} → {w.chain}</strong><small>{w.wallet_address.slice(0,10)}…{w.wallet_address.slice(-6)}{w.tx_hash?` • ${w.tx_hash}`:''}</small></div><b>{w.estimated_value_gbp?`~${money(w.estimated_value_gbp)}`:'Unpriced'}</b></div>)}
 {!tax?.receipts.length&&!tax?.withdrawals.length&&<div className="empty-state"><ReceiptText/><strong>No activity in {year}.</strong><p>The CSV is still available and will contain the statement headers.</p></div>}
 {tax?.disclaimer&&<div className="custody-note"><ShieldCheck/><p>{tax.disclaimer}</p></div>}</section>
 <section className="panel activity-panel"><div className="panel-head"><div><span><History/> MONTHLY HISTORY</span><h2>Your earning timeline</h2></div></div>{data?.monthly.length?data.monthly.slice().reverse().map(row=><div className="activity-row" key={row.month}><div><span>{row.month}</span><strong>{row.assets.length} reward asset{row.assets.length===1?'':'s'}</strong></div><b>{row.assets.map(a=>`${Number(a.amount).toLocaleString(undefined,{maximumFractionDigits:4})} ${a.asset}`).join(' • ')}</b></div>):<div className="empty-state">Your monthly earning history will appear after your first reward.</div>}</section></div>
}
