import { useEffect, useMemo, useState } from 'react'
import { ArrowDownToLine, Coins, Gem, History, Sparkles, TrendingUp } from 'lucide-react'
import { api } from '../lib/api'

type AssetAmount={asset:string;amount:string}
type Valuation={asset:string;available_amount:string;current_price_gbp:string|null;current_value_gbp:string|null;original_estimated_value_gbp:string|null;change_pct:string|null}
type Summary={lifetime:AssetAmount[];available:AssetAmount[];pending:AssetAmount[];withdrawn:AssetAmount[];referral:AssetAmount[];unique_assets:number;total_current_value_gbp:string;total_original_estimated_value_gbp:string;valuations:Valuation[];monthly:{month:string;assets:AssetAmount[]}[]}

const totalUnits=(rows:AssetAmount[])=>rows.reduce((sum,row)=>sum+Number(row.amount||0),0)
const money=(value:string|number|null|undefined)=>value===null||value===undefined?'—':`£${Number(value).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`

export default function Earnings(){
 const [data,setData]=useState<Summary|null>(null)
 useEffect(()=>{api<Summary>('/earnings/summary').then(setData)},[])
 const lifetimeUnits=useMemo(()=>totalUnits(data?.lifetime||[]),[data])
 return <div className="page"><div className="page-head"><div><span className="eyebrow small">EARNINGS CENTRE</span><h1>Everything you’ve <em>Bagged.</em></h1><p>Track earned assets, what they were worth when you earned them and what your available rewards are worth now.</p></div></div>
 <div className="stats-grid"><div className="stat-card hot"><span><Sparkles/>CURRENT TRACKED VALUE</span><strong>{money(data?.total_current_value_gbp)}</strong><small>Available rewards with a price feed</small></div><div className="stat-card"><span><History/>ORIGINAL ESTIMATE</span><strong>{money(data?.total_original_estimated_value_gbp)}</strong><small>Estimated value when Bagged</small></div><div className="stat-card"><span><Gem/>ASSETS BAGGED</span><strong>{data?.unique_assets??'—'}</strong><small>{lifetimeUnits.toLocaleString(undefined,{maximumFractionDigits:2})} lifetime token units</small></div><div className="stat-card"><span><ArrowDownToLine/>WITHDRAWALS</span><strong>{data?.withdrawn.length??'—'}</strong><small>Assets with settled withdrawals</small></div></div>
 <section className="panel"><div className="panel-head"><div><span><TrendingUp/> REWARD VALUE TRACKER</span><h2>What happened to your Bagz?</h2></div></div>{data?.valuations.length?data.valuations.map(v=><div className="activity-row" key={v.asset}><div><span>{v.asset}</span><strong>{Number(v.available_amount).toLocaleString(undefined,{maximumFractionDigits:8})} available</strong></div><b>{v.current_value_gbp?money(v.current_value_gbp):'Price unavailable'}</b><small>{v.original_estimated_value_gbp?`Bagged at ~${money(v.original_estimated_value_gbp)}${v.change_pct?` • ${Number(v.change_pct)>=0?'+':''}${Number(v.change_pct).toFixed(1)}%`:''}`:'Original value not recorded'}</small></div>):<div className="empty-state"><Coins/><strong>No valued rewards yet.</strong><p>When a supported reward gets a GBP price snapshot, its current value appears here automatically.</p></div>}</section>
 <div className="two-col"><section className="panel"><div className="panel-head"><div><span>LIFETIME EARNINGS</span><h2>Assets earned</h2></div></div>{data?.lifetime.length?data.lifetime.map(row=><div className="treasury-row" key={row.asset}><strong>{row.asset}</strong><b>{Number(row.amount).toLocaleString(undefined,{maximumFractionDigits:8})}</b></div>):<div className="empty-state"><Coins/><strong>No earnings yet.</strong><p>Complete your first funded Bag to start your earnings history.</p></div>}</section>
 <section className="panel"><div className="panel-head"><div><span>REFERRAL INCOME</span><h2>Earn when your people Bag</h2></div></div>{data?.referral.length?data.referral.map(row=><div className="treasury-row" key={row.asset}><strong>{row.asset}</strong><b>{Number(row.amount).toLocaleString(undefined,{maximumFractionDigits:8})}</b></div>):<div className="empty-state"><Sparkles/><strong>No referral earnings yet.</strong><p>Share your NuBagz referral code and earn from funded campaign referral allocations.</p></div>}</section></div>
 <section className="panel activity-panel"><div className="panel-head"><div><span><History/> MONTHLY HISTORY</span><h2>Your earning timeline</h2></div></div>{data?.monthly.length?data.monthly.slice().reverse().map(row=><div className="activity-row" key={row.month}><div><span>{row.month}</span><strong>{row.assets.length} reward asset{row.assets.length===1?'':'s'}</strong></div><b>{row.assets.map(a=>`${Number(a.amount).toLocaleString(undefined,{maximumFractionDigits:4})} ${a.asset}`).join(' • ')}</b></div>):<div className="empty-state">Your monthly earning history will appear after your first reward.</div>}</section></div>
}
