import { useEffect, useState } from 'react'
import { Fuel, Plus, ShieldCheck, Zap } from 'lucide-react'
import { api } from '../lib/api'
import { useAuth } from '../context/AuthContext'
import type { Campaign, Project } from '../types'

type Status={configured:boolean;mode:string;principle:string}
type Budget={id:number;project_id:number;project_name:string;chain:string;native_asset:string;amount_per_tx:string;max_transactions:number;executed_transactions:number;remaining_transactions:number;funded_amount:string;spent_amount:string;remaining_funded_amount:string;maximum_obligation:string;funding_status:string;funding_reference?:string;status:string}
type Request={id:number;budget_id:number;campaign_id:number;campaign_title:string;chain:string;max_sponsored_native:string;status:string;provider:string|null;provider_request_id:string|null;tx_hash:string|null;gas_spent_native:string|null}
type VerifyDraft={funded_amount:string;funding_reference:string}

export default function GasPass(){
 const {user}=useAuth();const [status,setStatus]=useState<Status|null>(null);const [budgets,setBudgets]=useState<Budget[]>([]);const [mine,setMine]=useState<Budget[]>([]);const [requests,setRequests]=useState<Request[]>([]);const [projects,setProjects]=useState<Project[]>([]);const [campaigns,setCampaigns]=useState<Campaign[]>([]);const [show,setShow]=useState(false);const [msg,setMsg]=useState('');const [verifyDrafts,setVerifyDrafts]=useState<Record<number,VerifyDraft>>({})
 const [f,setF]=useState({project_id:0,chain:'Avalanche',amount_per_tx:0.01,max_transactions:100,funded_amount:1,funding_reference:''})
 const load=()=>{
  api<Status>('/gas/status').then(setStatus);api<Request[]>('/gas/requests').then(setRequests);api<Campaign[]>('/campaigns').then(setCampaigns)
  if(user?.role==='ADMIN')api<Budget[]>('/gas/budgets/admin').then(data=>{setBudgets(data);setVerifyDrafts(current=>{const next={...current};data.filter(b=>b.status==='PENDING').forEach(b=>{if(!next[b.id])next[b.id]={funded_amount:b.funded_amount,funding_reference:b.funding_reference||''}});return next})}).catch(()=>{});else api<Budget[]>('/gas/budgets').then(setBudgets).catch(()=>{})
  if(user?.role==='CREATOR'){Promise.all([api<Budget[]>('/gas/budgets/mine'),api<Project[]>('/projects/mine')]).then(([b,p])=>{setMine(b);const approved=p.filter(x=>x.status==='APPROVED');setProjects(approved);if(!f.project_id&&approved[0])setF(v=>({...v,project_id:approved[0].id}))}).catch(()=>{})}
 }
 useEffect(()=>{load()},[user?.role])
 const obligation=f.amount_per_tx*f.max_transactions
 const create=async(e:React.FormEvent)=>{e.preventDefault();try{await api('/gas/budgets',{method:'POST',body:JSON.stringify(f)});setMsg('Gas funding declared. An admin must independently verify the funded amount and transaction/reference before activation.');setShow(false);load()}catch(e:any){setMsg(e.message||'Could not create gas budget')}}
 const activate=async(b:Budget)=>{const draft=verifyDrafts[b.id]||{funded_amount:b.funded_amount,funding_reference:b.funding_reference||''};try{await api(`/gas/budgets/${b.id}/activate`,{method:'POST',body:JSON.stringify({funded_amount:Number(draft.funded_amount),funding_reference:draft.funding_reference})});setMsg('Project-funded gas budget independently verified and activated.');load()}catch(e:any){setMsg(e.message||'Could not verify gas budget')}}
 const request=async(b:Budget)=>{const options=campaigns.filter(c=>c.project_id===b.project_id&&c.status==='LIVE');if(!options.length){setMsg('No live campaign from this sponsoring project is available.');return}const cid=options[0].id;const to=window.prompt(`Destination contract/address for a sponsored transaction tied to ${options[0].title}`,'0x');if(!to)return;const data=window.prompt('Transaction data (optional)','0x')||'0x';try{const out=await api<Request>(`/gas/budgets/${b.id}/requests`,{method:'POST',body:JSON.stringify({campaign_id:cid,transaction:{to,data,value:'0x0'}})});setMsg(status?.configured?`Gas request #${out.id} created. Execute it when ready.`:'Gas request drafted. No sponsorship provider is configured, so the verified sponsor budget cannot be spent.');load()}catch(e:any){setMsg(e.message||'Could not create sponsored gas request')}}
 const execute=async(id:number)=>{try{const out=await api<Request>(`/gas/requests/${id}/execute`,{method:'POST'});setMsg(`Sponsored transaction executed: ${out.tx_hash}. Gas spent ${out.gas_spent_native}.`);load()}catch(e:any){setMsg(e.message||'Could not execute sponsored gas request')}}
 const visible=[...mine,...budgets.filter(b=>!mine.some(m=>m.id===b.id))]
 return <div className="page"><div className="page-head"><div><span className="eyebrow small">GAS PASS</span><h1>First actions without the <em>gas headache.</em></h1><p>Projects can pre-fund capped native-gas allowances for genuine participants. Creator declarations are not spendable until independently verified, and NuBagz never substitutes founder funds.</p></div>{projects.length>0&&<button className="btn primary" onClick={()=>setShow(!show)}><Plus/> Sponsor gas</button>}</div>{msg&&<div className="form-note">{msg}</div>}
 <div className="stats-grid"><div className={status?.configured?'stat-card hot':'stat-card'}><span><Fuel/>GAS PROVIDER</span><strong>{status?.configured?'READY':'NOT CONFIGURED'}</strong><small>{status?.mode||'—'}</small></div><div className="stat-card"><span><Zap/>YOUR REQUESTS</span><strong>{requests.length}</strong><small>One request per verified sponsor budget</small></div></div>
 {show&&<form className="panel builder" onSubmit={create}><h3>Create a fully funded gas budget</h3><div className="form-grid"><label>Project<select value={f.project_id} onChange={e=>setF({...f,project_id:Number(e.target.value)})}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Chain<select value={f.chain} onChange={e=>setF({...f,chain:e.target.value})}><option>Avalanche</option><option>Ethereum</option><option>Base</option><option>Arbitrum</option><option>Polygon</option></select></label><label>Max native gas / transaction<input type="number" min="0.000000000000000001" step="any" value={f.amount_per_tx} onChange={e=>setF({...f,amount_per_tx:Number(e.target.value)})}/></label><label>Maximum transactions<input type="number" min="1" value={f.max_transactions} onChange={e=>setF({...f,max_transactions:Number(e.target.value)})}/></label><label>Total funded native amount<input type="number" min="0.000000000000000001" step="any" value={f.funded_amount} onChange={e=>setF({...f,funded_amount:Number(e.target.value)})}/></label><label>Funding transaction / reference<input required minLength={4} value={f.funding_reference} onChange={e=>setF({...f,funding_reference:e.target.value})}/><small>Declaration only until independently verified.</small></label></div><div className={f.funded_amount>=obligation?'fund-check good':'fund-check bad'}><span>Maximum obligation</span><strong>{obligation.toLocaleString()}</strong><small>{f.funded_amount>=obligation?'✓ Declared amount covers maximum gas allocation':'Increase funded amount'}</small></div><button className="btn primary" disabled={f.funded_amount<obligation}><Fuel/> Submit funding declaration</button></form>}
 <section className="panel"><div className="panel-head"><div><span>SPONSORED BUDGETS</span><h2>Project-funded gas</h2></div></div>{visible.length?visible.map(b=><div className="activity-row" key={b.id}><div><span>{b.project_name} • {b.chain} • {b.status}</span><strong>Up to {b.amount_per_tx} {b.native_asset} × {b.max_transactions} transactions</strong><small>{b.remaining_transactions} transactions left • {b.spent_amount}/{b.funded_amount} {b.native_asset} spent • {b.remaining_funded_amount} remaining</small>{user?.role==='ADMIN'&&b.status==='PENDING'&&<div className="form-grid"><label>Verified funded amount<input type="number" min="0" step="any" value={verifyDrafts[b.id]?.funded_amount??b.funded_amount} onChange={e=>setVerifyDrafts({...verifyDrafts,[b.id]:{funded_amount:e.target.value,funding_reference:verifyDrafts[b.id]?.funding_reference??b.funding_reference??''}})}/></label><label>Verified transaction / reference<input value={verifyDrafts[b.id]?.funding_reference??b.funding_reference??''} onChange={e=>setVerifyDrafts({...verifyDrafts,[b.id]:{funded_amount:verifyDrafts[b.id]?.funded_amount??b.funded_amount,funding_reference:e.target.value}})}/></label></div>}</div><b>{b.funding_status}</b><div className="row-actions">{b.status==='LIVE'&&<button className="mini-action" onClick={()=>request(b)}>Request gas</button>}{user?.role==='ADMIN'&&b.status==='PENDING'&&<button className="mini-action" disabled={Number(verifyDrafts[b.id]?.funded_amount??b.funded_amount)<Number(b.maximum_obligation)||(verifyDrafts[b.id]?.funding_reference??b.funding_reference??'').trim().length<4} onClick={()=>activate(b)}>Verify funding</button>}</div></div>):<div className="empty-state"><Fuel/><strong>No live sponsored gas budgets.</strong><p>Projects can fund capped gas allowances for participating users.</p></div>}</section>
 <section className="panel"><div className="panel-head"><div><span>YOUR GAS REQUESTS</span><h2>Provider execution status</h2></div></div>{requests.length?requests.map(r=><div className="activity-row" key={r.id}><div><span>{r.chain} • {r.status}</span><strong>{r.campaign_title}</strong><small>Maximum sponsored gas {r.max_sponsored_native}{r.tx_hash?` • ${r.tx_hash}`:''}</small></div><b>{r.gas_spent_native||r.status}</b>{r.status==='DRAFT'&&<button className="mini-action" disabled={!status?.configured} onClick={()=>execute(r.id)}>Execute sponsorship</button>}</div>):<div className="empty-state">No sponsored gas requests yet.</div>}</section>
 <div className="custody-note"><ShieldCheck/><p>{status?.principle||'Gas sponsorship requires independently verified project funding and a configured execution provider.'}</p></div></div>
}
