import { Link } from 'react-router-dom'
import { ArrowRight, BadgeCheck, Coins, Gamepad2, Rocket, ShieldCheck, Sparkles, TrendingUp, Users, Zap } from 'lucide-react'
import { Logo } from '../components/Logo'
import { BagZMascot } from '../components/BagZMascot'

const features = [
 {Icon:Gamepad2,title:'Discover',copy:'Browse live Bagz from projects that have already funded their reward allocation.'},
 {Icon:Zap,title:'Complete',copy:'Learn, play, test, create or contribute. Bag Work gets more valuable as your BagScore grows.'},
 {Icon:Coins,title:'Earn',copy:'Rewards land in your NuBagz ledger only when a funded Bag obligation is completed.'},
 {Icon:TrendingUp,title:'Level up',copy:'Build XP, reputation and a history of genuine participation to unlock better opportunities.'},
]

export default function Landing(){return <div className="landing">
 <header className="landing-nav"><Logo/><nav><a href="#how">How it works</a><a href="#creators">For projects</a><a href="#economy">The economy</a></nav><div className="nav-actions"><Link className="btn ghost" to="/login">Log in</Link><Link className="btn primary" to="/register">Start baggin' <ArrowRight size={16}/></Link></div></header>
 <section className="hero"><div className="hero-glow one"></div><div className="hero-glow two"></div><div className="hero-grid"><div className="hero-copy"><div className="eyebrow"><span></span> THE ZERO-DEPOSIT CRYPTO ECONOMY</div><h1>No money.<br/>No bag.<br/><em>No problem.</em></h1><p>Earn your way into crypto. Discover projects, complete Bag Work and build a real portfolio without putting your own money on the line.</p><div className="hero-actions"><Link className="btn primary big" to="/register">Build my first Bag <ArrowRight/></Link><a className="btn glass big" href="#creators">I have a project</a></div><div className="trust-row"><span><ShieldCheck/> No deposit required</span><span><BadgeCheck/> Reward-backed Bagz</span><span><Zap/> Built for real participation</span></div></div><div className="bag-z-hero-stage"><div className="bag-z-hero-halo"></div><div className="bag-z-hero-label"><span>MEET</span><strong>Bag Z</strong><small>Your guide to the bag economy.</small></div><BagZMascot variant="hello" className="bag-z-hero-art" eager/></div></div>
 <div className="hero-console"><div className="console-head"><div><small>MY NUBAGZ</small><strong>£0.00 → <em>£27.64</em></strong></div><span className="live-dot">LIVE</span></div><div className="console-grid"><div className="mini-bag neon"><b>NF</b><span>NFROG</span><strong>+2,000</strong></div><div className="mini-bag blue"><b>RA</b><span>RAID</span><strong>+480</strong></div><div className="mini-bag pink"><b>MO</b><span>MOCHI</span><strong>+1,120</strong></div><div className="mini-bag gold"><b>OR</b><span>ORBIT</span><strong>+240</strong></div></div><div className="ticker"><span>Lifetime bagged</span><strong>£27.64</strong><span>Own money deposited</span><strong className="zero">£0.00</strong></div></div></section>
 <section className="marquee"><span>LEARN & EARN</span><i>✦</i><span>DISCOVER BAGZ</span><i>✦</i><span>CREATE & EARN</span><i>✦</i><span>PLAY & EARN</span><i>✦</i><span>BUILD REPUTATION</span></section>
 <section id="how" className="section bag-z-section"><div className="bag-z-section-lead"><div className="section-title"><span>01 / FOR EARNERS</span><h2>Your time has value.<br/><em>Bag it.</em></h2><p>NuBagz replaces “deposit first” with a progressive earning journey.</p></div><div className="bag-z-feature-stage detective"><div><span>BAG Z / SCOUT MODE</span><strong>Find the funded opportunities worth your time.</strong></div><BagZMascot variant="detective" className="bag-z-section-art bag-z-how-art"/></div></div><div className="feature-grid">
 {features.map(({Icon,title,copy},i)=><div className="feature-card" key={title}><span>0{i+1}</span><Icon/><h3>{title}</h3><p>{copy}</p></div>)}
 </div></section>
 <section id="creators" className="creator-section"><div className="creator-panel"><div className="creator-copy"><span>02 / FOR PROJECTS</span><h2>Don't buy ads.<br/><em>Build holders.</em></h2><p>Create a project, its first funded Bag and all of its Bag Work through one guided launch flow. No five-figure campaign cheque required.</p><ul><li><BadgeCheck/> Publish your project without an endorsement gate</li><li><BadgeCheck/> Allocate token inventory, not user deposits</li><li><BadgeCheck/> Create social, on-chain, community, content or custom Bag Work</li><li><BadgeCheck/> Optionally sponsor gas on individual on-chain activities</li></ul><Link className="btn primary big" to="/register">Open Creator Studio <Rocket/></Link></div><div className="creator-visual"><div className="bag-z-creator-stage"><span>BAG Z / EARN MODE</span><BagZMascot variant="loot" className="bag-z-creator-art"/></div><div className="split-card"><div className="split-title">5,000,000 $TOKEN allocation</div><div className="split-row user"><span>80%</span><div><strong>Users</strong><small>Verified Bag rewards</small></div></div><div className="split-row platform"><span>15%</span><div><strong>NuBagz</strong><small>Platform economy share</small></div></div><div className="split-row referral"><span>5%</span><div><strong>Referrers</strong><small>Discovery & growth incentive</small></div></div><p>Splits are transparent and configurable per Bag.</p></div></div></div></section>
 <section id="economy" className="section economy bag-z-section"><div className="economy-intro"><div className="section-title"><span>03 / THE FLYWHEEL</span><h2>Everybody has a reason<br/>to <em>win.</em></h2><p>Bag Z is the face of a loop where participation, funded rewards and project growth reinforce each other.</p></div><div className="bag-z-feature-stage victory"><div><span>BAG Z / WIN MODE</span><strong>More participation. Better Bagz. Stronger projects.</strong></div><BagZMascot variant="victory" className="bag-z-section-art bag-z-economy-art"/></div></div><div className="flywheel"><div><Users/><strong>Earners</strong><span>bring attention, time & contribution</span></div><b>→</b><div><Rocket/><strong>Projects</strong><span>bring token inventory & opportunities</span></div><b>→</b><div><Sparkles/><strong>NuBagz</strong><span>turns participation into a marketplace</span></div></div></section>
 <footer><Logo/><div><strong>No money. No bag. No problem.</strong><span>© 2026 NuBagz. Built for participation, not speculation.</span></div><Link to="/register" className="btn glass">Start baggin'</Link></footer>
 </div>}
