import { useEffect, useState } from 'react'
import { ArrowDownToLine, Check, Gem, Link2, LockKeyhole, ShieldCheck, Trophy, WalletCards } from 'lucide-react'
import { Link } from 'react-router-dom'
import { api } from '../lib/api'
import type { Dashboard, PayoutAddress, WalletConnection } from '../types'
import { useAuth } from '../context/AuthContext'
import SocialAccountsPanel from '../components/SocialAccountsPanel'

const short=(a:string)=>`${a.slice(0,7)}…${a.slice(-5)}`
export default function MyBag(){const {user,refresh}=useAuth();const [d,setD]=useState<Dashboard|null>(null);const [wallets,setWallets]=useState<WalletConnection[]>([]);const [payouts,setPayouts]=useState<PayoutAddress[]>([]);const [msg,setMsg]=useState('')
 const load=async()=>{const [dash,w,p]=await Promise.all([api<Dashboard>('/users/dashboard'),api<WalletConnection[]>('/users/wallets'),api<PayoutAddress[]>('/users/payout-addresses')]);setD(dash);setWallets(w);setPayouts(p)};useEffect(()=>{load()},[])
 const makeWalletPrimary=async(id:number)=>{await api(`/users/wallets/${id}/primary`,{method:'POST'});await refresh();await load();setMsg('Primary reward wallet updated.')}
 const makePayoutPrimary=async(id:number)=>{await api(`/users/payout-addresses/${id}/primary`,{method:'POST'});await refresh();await load();setMsg('Primary payout-only address updated.')}
 const withdraw=async(asset:string,amount:string)=>{if(!user?.wallet_address){setMsg('Set a reward destination first.');return}const raw=window.prompt(`How much ${asset} would you like to withdraw?\nAvailable: ${amount}`);if(!raw)return;let chain=user.wallet_chain||'Avalanche';if(chain==='EVM'){const chosen=window.prompt('Which EVM network should this reward be settled on?','Avalanche');if(!chosen)return;chain=chosen}try{await api('/users/withdrawals',{method:'POST',body:JSON.stringify({asset_symbol:asset,amount:Number(raw),chain,wallet_address:user.wallet_address})});setMsg('Withdrawal request submitted for review.')}catch(e:any){setMsg(e.message)}}
 return <div className="page"><div className="page-head"><div><span className="eyebrow small">MY BAG</span><h1>Your wallet, rewards and <em>activity.</em></h1><p>Track project rewards, reward destinations and your NuBagz participation in one account area.</p></div></div>
 <div className="bag-summary"><div><WalletCards/><span>UNIQUE ASSETS</span><strong>{d?.lifetime_assets||0}</strong></div><div><Gem/><span>CHALLENGES COMPLETED</span><strong>{d?.completed_bagz||0}</strong></div><div><Trophy/><span>POINTS</span><strong>{(d?.bag_score||0).toLocaleString()}</strong></div></div>
 <SocialAccountsPanel/>
 <div className="two-col"><section className="panel"><div className="panel-head"><div><span>AVAILABLE BALANCES</span><h2>Reward ledger</h2></div></div>{d?.balances?.length?<div className="asset-list large">{d.balances.map((b,i)=><div className="asset-row" key={b.asset_symbol}><div className={`asset-icon a${i%4}`}>{b.asset_symbol.slice(0,2)}</div><div><strong>{b.asset_symbol}</strong><small>Available to request withdrawal</small></div><b>{Number(b.amount).toLocaleString(undefined,{maximumFractionDigits:6})}</b><button className="mini-action" onClick={()=>withdraw(b.asset_symbol,b.amount)}><ArrowDownToLine/> Withdraw</button></div>)}</div>:<div className="empty-state"><WalletCards/><strong>No assets yet</strong><p>Your first approved Challenge reward will appear here.</p></div>}</section>
 <section className="panel wallet-panel"><div className="panel-head"><div><span>REWARD DESTINATIONS</span><h2>Your wallet setup</h2></div><Link to="/wallet-setup" className="mini-action"><Link2/> Add</Link></div><p>Choose a verified connected wallet or keep your wallet disconnected and use a payout-only address.</p><div className="destination-list">{wallets.map(w=><button key={`w${w.id}`} className={`destination ${w.is_primary?'primary-destination':''}`} onClick={()=>makeWalletPrimary(w.id)}><span className="dest-icon"><ShieldCheck/></span><span><b>{w.wallet_type==='EMBEDDED'?'NuBagz embedded wallet':`${w.wallet_client_type} wallet`}</b><small>{short(w.address)} · Verified connection</small></span>{w.is_primary?<em><Check/> Primary</em>:<em>Set primary</em>}</button>)}{payouts.map(p=><button key={`p${p.id}`} className={`destination ${p.is_primary?'primary-destination':''}`} onClick={()=>makePayoutPrimary(p.id)}><span className="dest-icon safe"><LockKeyhole/></span><span><b>{p.label}</b><small>{short(p.address)} · {p.chain} · Payout-only</small></span>{p.is_primary?<em><Check/> Primary</em>:<em>Set primary</em>}</button>)}</div>{!wallets.length&&!payouts.length&&<div className="empty-destination"><LockKeyhole/><span><b>No wallet connection required.</b> Add a payout address if you prefer to keep your wallets completely disconnected.</span></div>}{msg&&<div className="form-note">{msg}</div>}<div className="custody-note"><ShieldCheck/><p><strong>Important:</strong> NuBagz never requires a deposit to unlock earned balances. Connected-wallet verification signs a plain message only; payout-only addresses request no permissions at all.</p></div></section></div>
 <section className="panel activity-panel"><div className="panel-head"><div><span>ACTIVITY</span><h2>Recent reward activity</h2></div></div>{d?.recent_activity?.length?d.recent_activity.map((a,i)=><div className="activity-row" key={i}><div><span>{a.type.replaceAll('_',' ')}</span><strong>{a.note||'NuBagz reward'}</strong></div><b>+{Number(a.amount).toLocaleString()} {a.asset}</b><small>{new Date(a.created_at).toLocaleDateString()}</small></div>):<div className="empty-state">No reward activity yet.</div>}</section></div>
}
