import { useEffect, useState } from 'react'
import { ArrowDownToLine, Copy, ExternalLink, Gem, Link2, ShieldCheck, WalletCards } from 'lucide-react'
import { api } from '../lib/api'
import type { Dashboard } from '../types'
import { useAuth } from '../context/AuthContext'

export default function MyBag(){const {user,refresh}=useAuth();const [d,setD]=useState<Dashboard|null>(null);const [wallet,setWallet]=useState(user?.wallet_address||'');const [chain,setChain]=useState(user?.wallet_chain||'Avalanche');const [msg,setMsg]=useState('')
 const load=()=>api<Dashboard>('/users/dashboard').then(setD);useEffect(()=>{load()},[])
 const saveWallet=async()=>{try{await api('/auth/wallet',{method:'PUT',body:JSON.stringify({wallet_address:wallet,wallet_chain:chain})});await refresh();setMsg('Withdrawal wallet saved.')}catch(e:any){setMsg(e.message)}}
 const withdraw=async(asset:string,amount:string)=>{if(!wallet){setMsg('Save a withdrawal wallet first.');return}const raw=window.prompt(`How much ${asset} would you like to withdraw?\nAvailable: ${amount}`);if(!raw)return;try{await api('/users/withdrawals',{method:'POST',body:JSON.stringify({asset_symbol:asset,amount:Number(raw),chain,wallet_address:wallet})});setMsg('Withdrawal request submitted for review.')}catch(e:any){setMsg(e.message)}}
 return <div className="page"><div className="page-head"><div><span className="eyebrow small">MY BAG</span><h1>Your earned <em>crypto inventory.</em></h1><p>Everything here came from completed NuBagz opportunities and referral shares.</p></div></div>
 <div className="bag-summary"><div><WalletCards/><span>UNIQUE ASSETS</span><strong>{d?.lifetime_assets||0}</strong></div><div><Gem/><span>BAGS COMPLETED</span><strong>{d?.completed_bagz||0}</strong></div><div><ShieldCheck/><span>BAGSCORE</span><strong>{d?.bag_score||0}</strong></div></div>
 <div className="two-col"><section className="panel"><div className="panel-head"><div><span>AVAILABLE BALANCES</span><h2>Reward ledger</h2></div></div>{d?.balances?.length?<div className="asset-list large">{d.balances.map((b,i)=><div className="asset-row" key={b.asset_symbol}><div className={`asset-icon a${i%4}`}>{b.asset_symbol.slice(0,2)}</div><div><strong>{b.asset_symbol}</strong><small>Available to request withdrawal</small></div><b>{Number(b.amount).toLocaleString(undefined,{maximumFractionDigits:6})}</b><button className="mini-action" onClick={()=>withdraw(b.asset_symbol,b.amount)}><ArrowDownToLine/> Withdraw</button></div>)}</div>:<div className="empty-state"><WalletCards/><strong>No assets yet</strong><p>Your first funded Bag will appear here.</p></div>}</section>
 <section className="panel wallet-panel"><div className="panel-head"><div><span>WITHDRAWAL DESTINATION</span><h2>Connect your wallet</h2></div></div><p>NuBagz keeps small rewards in an internal ledger to avoid wasting network fees. Add a self-custody wallet when you're ready to move assets on-chain.</p><label>Network<select value={chain} onChange={e=>setChain(e.target.value)}><option>Avalanche</option><option>Solana</option><option>Ethereum</option><option>Base</option></select></label><label>Wallet address<div className="address-input"><Link2/><input value={wallet} onChange={e=>setWallet(e.target.value)} placeholder="0x… or chain address"/></div></label><button className="btn primary full" onClick={saveWallet}>Save wallet</button>{msg&&<div className="form-note">{msg}</div>}<div className="custody-note"><ShieldCheck/><p><strong>Important:</strong> withdrawals are queued for settlement. The platform never requires a user deposit to unlock earned balances.</p></div></section></div>
 <section className="panel activity-panel"><div className="panel-head"><div><span>LEDGER</span><h2>Recent activity</h2></div></div>{d?.recent_activity?.length?d.recent_activity.map((a,i)=><div className="activity-row" key={i}><div><span>{a.type.replaceAll('_',' ')}</span><strong>{a.note||'NuBagz reward'}</strong></div><b>+{Number(a.amount).toLocaleString()} {a.asset}</b><small>{new Date(a.created_at).toLocaleDateString()}</small></div>):<div className="empty-state">No ledger entries yet.</div>}</section></div>
}
