import { useEffect, useMemo, useState } from 'react'
import { CheckCircle2, Link2, RadioTower, ShieldCheck, Zap } from 'lucide-react'
import { api } from '../lib/api'
import { useAuth } from '../context/AuthContext'
import type { Campaign } from '../types'

type Rule={id:number;mission_id:number;mission_title:string;campaign_id:number;campaign_title:string;chain:string;rule_type:string;contract_address:string|null;min_amount:string|null;token_decimals:number;verified:boolean;verified_at:string|null}

export default function OnchainLab(){const {user}=useAuth();const [rules,setRules]=useState<Rule[]>([]);const [campaigns,setCampaigns]=useState<Campaign[]>([]);const [msg,setMsg]=useState('');const [f,setF]=useState({mission_id:0,chain:'Avalanche',rule_type:'TX_SUCCESS',contract_address:'',min_amount:'',token_decimals:18})
 const load=()=>{api<Rule[]>('/onchain/rules').then(setRules);if(user?.role==='CREATOR'||user?.role==='ADMIN')api<Campaign[]>('/campaigns/mine').then(setCampaigns).catch(()=>{})};useEffect(()=>{load()},[])
 const missions=useMemo(()=>campaigns.flatMap(c=>c.missions.map(m=>({id:m.id,label:`${c.title} — ${m.title}`}))),[campaigns])
 useEffect(()=>{if(!f.mission_id&&missions[0])setF(v=>({...v,mission_id:missions[0].id}))},[missions])
 const verify=async(rule:Rule)=>{const needsTx=rule.rule_type==='TX_SUCCESS'||rule.rule_type==='CONTRACT_INTERACTION';const tx=needsTx?window.prompt('Paste the transaction hash to verify'):null;if(needsTx&&tx===null)return;try{await api(`/onchain/rules/${rule.id}/verify`,{method:'POST',body:JSON.stringify({tx_hash:tx||null})});setMsg('On-chain requirement verified against the configured RPC. You can now complete the mission in its Bag.');load()}catch(e:any){setMsg(e.message||'On-chain verification failed')}}
 const createRule=async(e:React.FormEvent)=>{e.preventDefault();try{await api('/onchain/rules',{method:'POST',body:JSON.stringify({mission_id:f.mission_id,chain:f.chain,rule_type:f.rule_type,contract_address:f.contract_address||null,min_amount:f.min_amount?Number(f.min_amount):null,token_decimals:f.token_decimals})});setMsg('Authoritative on-chain rule saved. Users cannot override this condition.');load()}catch(e:any){setMsg(e.message||'Could not save rule')}}
 return <div className="page"><div className="page-head"><div><span className="eyebrow small">ONCHAIN LAB</span><h1>Proof, not <em>screenshots.</em></h1><p>NuBagz verifies project-defined blockchain conditions directly against the configured chain RPC and a user’s verified wallet.</p></div></div>{msg&&<div className="form-note">{msg}</div>}
 <section className="panel"><div className="panel-head"><div><span><RadioTower/> LIVE VERIFICATION RULES</span><h2>Prove your on-chain action</h2></div></div>{rules.length?rules.map(r=><div className="activity-row" key={r.id}><div><span>{r.chain} • {r.rule_type.replaceAll('_',' ')}</span><strong>{r.campaign_title} — {r.mission_title}</strong></div><b>{r.verified?'VERIFIED ✓':'PROOF REQUIRED'}</b><small>{r.contract_address?`Contract ${r.contract_address.slice(0,10)}…`:r.min_amount?`Minimum ${r.min_amount}`:'Successful transaction'}</small><button className="mini-action" disabled={r.verified} onClick={()=>verify(r)}>{r.verified?<CheckCircle2/>:<ShieldCheck/>} {r.verified?'Verified':'Verify'}</button></div>):<div className="empty-state"><RadioTower/><strong>No live on-chain rules.</strong><p>Projects can attach authoritative blockchain verification to campaign missions.</p></div>}</section>
 {missions.length>0&&<form className="panel builder" onSubmit={createRule}><div className="panel-head"><div><span><Link2/> PROJECT RULE BUILDER</span><h2>Make a mission verifiable</h2></div></div><p>The rule is controlled by the project. Earners only provide the proof input; they cannot change the target condition.</p><div className="form-grid"><label>Mission<select value={f.mission_id} onChange={e=>setF({...f,mission_id:Number(e.target.value)})}>{missions.map(m=><option key={m.id} value={m.id}>{m.label}</option>)}</select></label><label>Chain<select value={f.chain} onChange={e=>setF({...f,chain:e.target.value})}><option>Avalanche</option><option>Ethereum</option><option>Base</option><option>Arbitrum</option><option>Polygon</option></select></label><label>Rule type<select value={f.rule_type} onChange={e=>setF({...f,rule_type:e.target.value})}><option value="TX_SUCCESS">Successful transaction</option><option value="CONTRACT_INTERACTION">Contract interaction</option><option value="NATIVE_BALANCE">Native balance</option><option value="ERC20_BALANCE">ERC-20 balance</option></select></label>{(f.rule_type==='CONTRACT_INTERACTION'||f.rule_type==='ERC20_BALANCE')&&<label>Contract address<input value={f.contract_address} onChange={e=>setF({...f,contract_address:e.target.value})} placeholder="0x…"/></label>}{(f.rule_type==='NATIVE_BALANCE'||f.rule_type==='ERC20_BALANCE')&&<label>Minimum amount<input type="number" step="any" min="0" value={f.min_amount} onChange={e=>setF({...f,min_amount:e.target.value})}/></label>}{f.rule_type==='ERC20_BALANCE'&&<label>Token decimals<input type="number" min="0" max="36" value={f.token_decimals} onChange={e=>setF({...f,token_decimals:Number(e.target.value)})}/></label>}</div><button className="btn primary"><Zap/> Save on-chain rule</button></form>}</div>
}
