import { useEffect, useState } from 'react'
import { BarChart3, CheckCircle2, Coins, ShieldAlert, Target, Users } from 'lucide-react'
import { api } from '../lib/api'

type SettlementRow={entry_type:string;amount:string}
type CampaignMetric={campaign_id:number;title:string;status:string;reward_asset:string;max_users:number;enrollments:number;completions:number;unique_completed_participants:number;completion_rate_pct:string;gross_reward_per_user:string;maximum_reward_obligation:string;funding_status:string;verified_funding:string;remaining_verified_funding:string;funding_utilization_pct:string;distributed_total:string;settlement_breakdown:SettlementRow[];linked_non_campaign_distribution_total:string;reconciled:boolean;cost_per_completed_participant:string|null;referral_conversions:number;bagbuilder_conversions:number}
type ProjectMetric={project_id:number;name:string;symbol:string;status:string;campaign_count:number;live_campaigns:number;enrollments:number;completions:number;completion_rate_pct:string;unique_completed_participants:number;distributed_by_asset:{asset:string;amount:string}[];all_campaigns_reconciled:boolean;campaigns:CampaignMetric[]}
type Payload={projects:ProjectMetric[];totals:{projects:number;campaigns:number;enrollments:number;completions:number;unique_completed_participants:number};principle:string}

export default function ProjectAnalytics(){const [d,setD]=useState<Payload|null>(null);useEffect(()=>{api<Payload>('/project-analytics').then(setD)},[])
 return <div className="page"><div className="page-head"><div><span className="eyebrow small">PROJECT ANALYTICS</span><h1>Measure <em>participation.</em></h1><p>See what verified campaign inventory produced: real enrollments, completions, acquisition pathways and ledger-backed settlement—not impression counts.</p></div></div>
 <div className="stats-grid"><div className="stat-card"><span><BarChart3/>CAMPAIGNS</span><strong>{d?.totals.campaigns??'—'}</strong></div><div className="stat-card"><span><Users/>ENROLLMENTS</span><strong>{d?.totals.enrollments??'—'}</strong></div><div className="stat-card hot"><span><Target/>COMPLETIONS</span><strong>{d?.totals.completions??'—'}</strong><small>{d?.totals.unique_completed_participants||0} unique participants</small></div><div className="stat-card"><span><Coins/>PROJECTS</span><strong>{d?.totals.projects??'—'}</strong></div></div>
 {d?.projects.map(p=><section className="panel" key={p.project_id}><div className="panel-head"><div><span>${p.symbol} • {p.status}</span><h2>{p.name}</h2></div><b>{p.completion_rate_pct}% completion rate</b></div><div className="bag-summary"><div><span>ENROLLMENTS</span><strong>{p.enrollments}</strong></div><div><span>COMPLETIONS</span><strong>{p.completions}</strong></div><div><span>UNIQUE PARTICIPANTS</span><strong>{p.unique_completed_participants}</strong></div><div><span>RECONCILIATION</span><strong>{p.all_campaigns_reconciled?'OK':'REVIEW'}</strong></div></div>{p.campaigns.map(c=><div className="activity-row" key={c.campaign_id}><div><span>{c.status} • {c.funding_status} • {c.reward_asset}</span><strong>{c.title}</strong><small>{c.enrollments} joined • {c.completions} completed • {c.completion_rate_pct}% conversion • referrals {c.referral_conversions} • BagBuilder {c.bagbuilder_conversions}</small><small>{c.settlement_breakdown.map(x=>`${x.entry_type.replaceAll('_',' ')} ${Number(x.amount).toLocaleString()}`).join(' • ')||'No settlement entries yet'}</small>{Number(c.linked_non_campaign_distribution_total)>0&&<small>Separate campaign-linked distributions: {Number(c.linked_non_campaign_distribution_total).toLocaleString()} (excluded from reward-pool consumption)</small>}</div><div><b>{c.distributed_total} {c.reward_asset} distributed</b><small>{c.remaining_verified_funding} remaining • {c.funding_utilization_pct}% utilised</small><small>{c.cost_per_completed_participant?`${Number(c.cost_per_completed_participant).toLocaleString()} ${c.reward_asset} / completion`:'No completions yet'}</small><span className={c.reconciled?'category':'category danger'}>{c.reconciled?<><CheckCircle2/> Reconciled</>:<><ShieldAlert/> Review funding</>}</span></div></div>)}</section>)}
 {!d?.projects.length&&<div className="empty-state"><BarChart3/><strong>No creator analytics yet.</strong><p>Create and fund project campaigns to start measuring verified participation.</p></div>}{d?.principle&&<div className="custody-note"><Target/><p>{d.principle}</p></div>}</div>
}
