import { useEffect, useState } from 'react'
import { ArrowUpRight, BarChart3, CheckCircle2, Coins, ShieldAlert, Target, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import { api } from '../lib/api'

type SettlementRow={entry_type:string;amount:string}
type RewardGroupMetric={compatibility_id:number;title:string;status:string;challenge_ids:number[];challenge_titles:string[];challenge_count:number;legacy_grouped:boolean;reward_asset:string;max_users:number;enrollments:number;completions:number;unique_completed_participants:number;completion_rate_pct:string;gross_reward_per_user:string;maximum_reward_obligation:string;funding_status:string;verified_funding:string;remaining_verified_funding:string;funding_utilization_pct:string;distributed_total:string;settlement_breakdown:SettlementRow[];linked_distribution_total:string;reconciled:boolean;cost_per_completed_participant:string|null;referral_conversions:number}
type ProjectMetric={project_id:number;name:string;symbol:string;status:string;challenge_count:number;live_challenges:number;enrollments:number;completions:number;completion_rate_pct:string;unique_completed_participants:number;distributed_by_asset:{asset:string;amount:string}[];all_challenges_reconciled:boolean;challenge_reward_groups:RewardGroupMetric[]}
type Payload={projects:ProjectMetric[];totals:{projects:number;challenges:number;enrollments:number;completions:number;unique_completed_participants:number};principle:string}

export default function ProjectAnalytics(){const [d,setD]=useState<Payload|null>(null);useEffect(()=>{api<Payload>('/project-analytics').then(setD)},[])
 return <div className="page"><div className="page-head"><div><span className="eyebrow small">PROJECT ANALYTICS</span><h1>Measure <em>participation.</em></h1><p>See what verified Challenge inventory produced: real joins, completions, referral conversions and ledger-backed Project Reward settlement—not impression counts.</p></div></div>
 <div className="stats-grid"><div className="stat-card"><span><BarChart3/>CHALLENGES</span><strong>{d?.totals.challenges??'—'}</strong></div><div className="stat-card"><span><Users/>JOINS</span><strong>{d?.totals.enrollments??'—'}</strong></div><div className="stat-card hot"><span><Target/>COMPLETIONS</span><strong>{d?.totals.completions??'—'}</strong><small>{d?.totals.unique_completed_participants||0} unique participants</small></div><div className="stat-card"><span><Coins/>PROJECTS</span><strong>{d?.totals.projects??'—'}</strong></div></div>
 {d?.projects.map(p=><section className="panel" key={p.project_id}><div className="panel-head"><div><span>${p.symbol} • {p.status}</span><h2>{p.name}</h2></div><b>{p.completion_rate_pct}% completion rate</b></div><div className="bag-summary"><div><span>CHALLENGES</span><strong>{p.challenge_count}</strong></div><div><span>COMPLETIONS</span><strong>{p.completions}</strong></div><div><span>UNIQUE PARTICIPANTS</span><strong>{p.unique_completed_participants}</strong></div><div><span>RECONCILIATION</span><strong>{p.all_challenges_reconciled?'OK':'REVIEW'}</strong></div></div>{p.challenge_reward_groups.map(c=>{const primary=c.challenge_ids[0];const title=c.legacy_grouped?`Pre-V2 grouped reward: ${c.title}`:(c.challenge_titles[0]||c.title);return <div className="activity-row" key={c.compatibility_id}><div><span>{c.status} • {c.funding_status} • {c.reward_asset}{c.legacy_grouped?` • ${c.challenge_count} linked requirements`:''}</span><strong>{title}</strong><small>{c.enrollments} joined • {c.completions} completed • {c.completion_rate_pct}% conversion • referral conversions {c.referral_conversions}</small><small>{c.settlement_breakdown.map(x=>`${x.entry_type.replaceAll('_',' ')} ${Number(x.amount).toLocaleString()}`).join(' • ')||'No settlement entries yet'}</small>{Number(c.linked_distribution_total)>0&&<small>Separate linked distributions: {Number(c.linked_distribution_total).toLocaleString()} (excluded from Project Reward consumption)</small>}</div><div><b>{c.distributed_total} {c.reward_asset} distributed</b><small>{c.remaining_verified_funding} remaining • {c.funding_utilization_pct}% utilised</small><small>{c.cost_per_completed_participant?`${Number(c.cost_per_completed_participant).toLocaleString()} ${c.reward_asset} / completion`:'No completions yet'}</small><span className={c.reconciled?'category':'category danger'}>{c.reconciled?<><CheckCircle2/> Reconciled</>:<><ShieldAlert/> Review funding</>}</span>{primary&&<Link className="mini-action" to={c.legacy_grouped?`/app/bagz/${c.compatibility_id}`:`/app/challenges/${primary}`}>Open {c.legacy_grouped?'group':'Challenge'} <ArrowUpRight/></Link>}</div></div>})}</section>)}
 {!d?.projects.length&&<div className="empty-state"><BarChart3/><strong>No creator analytics yet.</strong><p>Create and fund Challenges to start measuring verified participation.</p></div>}{d?.principle&&<div className="custody-note"><Target/><p>{d.principle}</p></div>}</div>
}
