import { useEffect, useState } from 'react'
import { BarChart3, Coins, Target, Users } from 'lucide-react'
import { api } from '../lib/api'

type CampaignMetric={campaign_id:number;title:string;status:string;reward_asset:string;max_users:number;enrollments:number;completions:number;completion_rate_pct:string;gross_reward_per_user:string;maximum_reward_obligation:string;funding_status:string;verified_funding:string;distributed_total:string;cost_per_completed_participant:string|null;referral_conversions:number;bagbuilder_conversions:number}
type ProjectMetric={project_id:number;name:string;symbol:string;status:string;campaign_count:number;live_campaigns:number;enrollments:number;completions:number;completion_rate_pct:string;unique_completed_participants:number;distributed_by_asset:{asset:string;amount:string}[];campaigns:CampaignMetric[]}
type Payload={projects:ProjectMetric[];totals:{projects:number;campaigns:number;enrollments:number;completions:number;unique_completed_participants:number};principle:string}

export default function ProjectAnalytics(){const [d,setD]=useState<Payload|null>(null);useEffect(()=>{api<Payload>('/project-analytics').then(setD)},[])
 return <div className="page"><div className="page-head"><div><span className="eyebrow small">PROJECT ANALYTICS</span><h1>Measure <em>participation.</em></h1><p>See what funded inventory produced: real enrollments, completions, reward distribution and acquisition pathways—not impression counts.</p></div></div>
 <div className="stats-grid"><div className="stat-card"><span><BarChart3/>CAMPAIGNS</span><strong>{d?.totals.campaigns??'—'}</strong></div><div className="stat-card"><span><Users/>ENROLLMENTS</span><strong>{d?.totals.enrollments??'—'}</strong></div><div className="stat-card hot"><span><Target/>COMPLETIONS</span><strong>{d?.totals.completions??'—'}</strong><small>{d?.totals.unique_completed_participants||0} unique participants</small></div><div className="stat-card"><span><Coins/>PROJECTS</span><strong>{d?.totals.projects??'—'}</strong></div></div>
 {d?.projects.map(p=><section className="panel" key={p.project_id}><div className="panel-head"><div><span>${p.symbol} • {p.status}</span><h2>{p.name}</h2></div><b>{p.completion_rate_pct}% completion rate</b></div><div className="bag-summary"><div><span>ENROLLMENTS</span><strong>{p.enrollments}</strong></div><div><span>COMPLETIONS</span><strong>{p.completions}</strong></div><div><span>UNIQUE PARTICIPANTS</span><strong>{p.unique_completed_participants}</strong></div></div>{p.campaigns.map(c=><div className="activity-row" key={c.campaign_id}><div><span>{c.status} • {c.funding_status} • {c.reward_asset}</span><strong>{c.title}</strong><small>{c.enrollments} joined • {c.completions} completed • {c.completion_rate_pct}% conversion • referrals {c.referral_conversions} • BagBuilder {c.bagbuilder_conversions}</small></div><b>{c.distributed_total} {c.reward_asset} distributed</b><small>{c.cost_per_completed_participant?`${Number(c.cost_per_completed_participant).toLocaleString()} ${c.reward_asset} / completion`:'No completions yet'}</small></div>)}</section>)}
 {!d?.projects.length&&<div className="empty-state"><BarChart3/><strong>No creator analytics yet.</strong><p>Create and fund project campaigns to start measuring verified participation.</p></div>}{d?.principle&&<div className="custody-note"><Target/><p>{d.principle}</p></div>}</div>
}