import { useEffect, useState } from 'react'
import { Copy, Network, Sparkles, Users, CircleDollarSign, ShieldAlert, ShieldCheck } from 'lucide-react'
import { api } from '../lib/api'

type AssetAmount={asset:string;amount:string}
type Person={username:string;joined_at:string;bag_score:number;converted:boolean;paid_conversions:number;redirected_conversions:number;last_conversion_at:string|null}
type Event={id:number;referred_username:string;campaign:string;asset:string;allocated_amount:string;paid_amount:string;status:string;reason:string;created_at:string}
type Referral={referral_code:string;referral_path:string;reward_eligible:boolean;trust_level:string;referred_users:number;converted_users:number;pending_users:number;completed_campaign_conversions:number;redirected_conversions:number;conversion_rate_pct:string;earnings:AssetAmount[];people:Person[];events:Event[];rule:string;abuse_rule:string}

export default function Referrals(){const [d,setD]=useState<Referral|null>(null);const [msg,setMsg]=useState('');useEffect(()=>{api<Referral>('/referrals/me').then(setD)},[]);const copy=async()=>{if(!d||!d.reward_eligible)return;await navigator.clipboard?.writeText(`${window.location.origin}${d.referral_path}`);setMsg('Referral link copied.')}
 return <div className="page"><div className="page-head"><div><span className="eyebrow small">REFERRALS</span><h1>Bring people in. <em>Earn when they earn.</em></h1><p>No bounty for empty signups. A referral becomes economically valuable only when that user completes a real pre-funded Bag.</p></div></div>{msg&&<div className="form-note">{msg}</div>}
 <div className="stats-grid"><div className="stat-card hot"><span><Users/>REFERRED USERS</span><strong>{d?.referred_users??'—'}</strong><small>{d?.pending_users??0} waiting for first funded conversion</small></div><div className="stat-card"><span><Network/>CONVERTED USERS</span><strong>{d?.converted_users??'—'}</strong><small>{Number(d?.conversion_rate_pct||0).toFixed(1)}% referral conversion rate</small></div><div className="stat-card"><span><CircleDollarSign/>PAID CONVERSIONS</span><strong>{d?.completed_campaign_conversions??'—'}</strong><small>Actual funded referral settlements</small></div><div className="stat-card"><span>{d?.reward_eligible?<ShieldCheck/>:<ShieldAlert/>}REFERRAL STATUS</span><strong>{d?.reward_eligible?'ACTIVE':'PAUSED'}</strong><small>Trust level {d?.trust_level||'—'} • {d?.redirected_conversions||0} redirected</small></div></div>
 <section className="panel"><div className="panel-head"><div><span>YOUR INVITE</span><h2>{d?.referral_code||'Loading…'}</h2></div><button className="mini-action" disabled={!d?.reward_eligible} onClick={copy}><Copy/> {d?.reward_eligible?'Copy referral link':'Referral link paused'}</button></div><p>{d?.rule}</p>{d&&!d.reward_eligible&&<div className="custody-note"><ShieldAlert/><p><strong>Referral rewards paused:</strong> your current trust level is {d.trust_level}. New attribution and referral payouts require NORMAL or VERIFIED status while NuBagz reviews farming signals.</p></div>}<div className="custody-note"><ShieldAlert/><p><strong>Anti-farming rule:</strong> {d?.abuse_rule}</p></div></section>
 <div className="two-col"><section className="panel"><div className="panel-head"><div><span>REFERRAL EARNINGS</span><h2>Assets Bagged from your network</h2></div></div>{d?.earnings.length?d.earnings.map(e=><div className="treasury-row" key={e.asset}><strong>{e.asset}</strong><b>{Number(e.amount).toLocaleString(undefined,{maximumFractionDigits:8})}</b></div>):<div className="empty-state">No funded referral shares yet. Signups alone never create a payout.</div>}</section><section className="panel"><div className="panel-head"><div><span>YOUR PEOPLE</span><h2>Referral funnel</h2></div></div>{d?.people.length?d.people.map(p=><div className="activity-row" key={p.username}><div><span>BagScore {p.bag_score} • {p.converted?'CONVERTED':'SIGNED UP'}</span><strong>{p.username}</strong></div><b>{p.paid_conversions} paid</b><small>{p.last_conversion_at?`Last conversion ${new Date(p.last_conversion_at).toLocaleDateString()}`:`Joined ${new Date(p.joined_at).toLocaleDateString()}`}</small></div>):<div className="empty-state">No referrals yet.</div>}</section></div>
 <section className="panel"><div className="panel-head"><div><span>CONVERSION LEDGER</span><h2>Why every referral reward exists</h2></div></div>{d?.events.length?d.events.map(e=><div className="activity-row" key={e.id}><div><span>{e.status} • {e.referred_username}</span><strong>{e.campaign}</strong></div><b>{Number(e.paid_amount).toLocaleString(undefined,{maximumFractionDigits:8})} {e.asset}</b><small>{e.status==='PAID'?`${e.allocated_amount} ${e.asset} referral allocation settled`:`${e.allocated_amount} ${e.asset} allocated • ${e.reason}`}</small></div>):<div className="empty-state">No funded referral conversions have settled yet.</div>}</section></div>
}
