import { useEffect, useState } from 'react'
import { AlertTriangle, MessageSquare, Scale, ShieldCheck } from 'lucide-react'
import { api } from '../lib/api'
import { useAuth } from '../context/AuthContext'

type Message={id:number;author:string;message:string;created_at:string}
type Case={id:number;target_type:string;target_id:number;category:string;detail:string;status:string;resolution_action:string;resolution_note:string|null;reporter:string;is_reporter:boolean;is_target_owner:boolean;messages:Message[];created_at:string;resolved_at:string|null}

export default function Reports(){
 const {user}=useAuth();const [rows,setRows]=useState<Case[]>([]);const [affected,setAffected]=useState<Case[]>([]);const [msg,setMsg]=useState('');const [form,setForm]=useState({target_type:'PROJECT',target_id:0,category:'SAFETY',detail:''})
 const load=()=>{if(user?.role==='ADMIN'){api<Case[]>('/reports/admin').then(setRows).catch(()=>{});setAffected([])}else{api<Case[]>('/reports/mine').then(setRows).catch(()=>{});api<Case[]>('/reports/affected').then(setAffected).catch(()=>setAffected([]))}}
 useEffect(()=>{load()},[user?.role])
 const create=async(e:React.FormEvent)=>{e.preventDefault();try{await api('/reports',{method:'POST',body:JSON.stringify(form)});setMsg('Report opened. No automatic penalty or balance action has been applied.');setForm({...form,detail:''});load()}catch(e:any){setMsg(e.message||'Could not open report')}}
 const addMessage=async(row:Case)=>{const message=window.prompt('Add a message to this dispute case');if(!message)return;try{await api(`/reports/${row.id}/messages`,{method:'POST',body:JSON.stringify({message})});setMsg('Message added to the case record.');load()}catch(e:any){setMsg(e.message||'Could not add message')}}
 const resolve=async(row:Case)=>{const action=(window.prompt('Resolution action: NONE, HIDE_REVIEW, SUSPEND_PROJECT or SUSPEND_CAMPAIGN','NONE')||'').toUpperCase();if(!action)return;const status=(window.prompt('Case status: RESOLVED or DISMISSED','RESOLVED')||'').toUpperCase();if(!status)return;const note=window.prompt('Admin resolution note');if(!note)return;try{await api(`/reports/${row.id}/resolve`,{method:'POST',body:JSON.stringify({status,action,note})});setMsg(`Case ${status.toLowerCase()} with action ${action}. Final decisions cannot be overwritten through this workflow.`);load()}catch(e:any){setMsg(e.message||'Could not resolve case')}}
 const all=[...rows,...affected.filter(a=>!rows.some(r=>r.id===a.id))]
 return <div className="page"><div className="page-head"><div><span className="eyebrow small">REPORTS & DISPUTES</span><h1>Raise concerns. <em>Keep due process.</em></h1><p>A report creates an auditable case. It does not automatically suspend a project, hide a review, restrict an account or move funds.</p></div></div>{msg&&<div className="form-note">{msg}</div>}
 <form className="panel builder" onSubmit={create}><div className="panel-head"><div><span>OPEN A CASE</span><h2>Report project activity or content</h2></div></div><div className="form-grid"><label>Target type<select value={form.target_type} onChange={e=>setForm({...form,target_type:e.target.value})}><option>PROJECT</option><option>CAMPAIGN</option><option>REVIEW</option></select></label><label>Target ID<input type="number" min="1" required value={form.target_id||''} onChange={e=>setForm({...form,target_id:Number(e.target.value)})}/></label><label>Category<input required value={form.category} onChange={e=>setForm({...form,category:e.target.value.toUpperCase()})}/></label><label className="full-span">What happened?<textarea required minLength={20} value={form.detail} onChange={e=>setForm({...form,detail:e.target.value})}/></label></div><button className="btn primary"><AlertTriangle/> Open report</button></form>
 <section className="panel"><div className="panel-head"><div><span>CASE HISTORY</span><h2>{user?.role==='ADMIN'?'Moderation queue':'Your reports & cases affecting your content'}</h2></div></div>{all.length?all.map(r=><div className="activity-row" key={r.id}><div><span>CASE #{r.id} • {r.target_type} #{r.target_id} • {r.category} • {r.status}</span><strong>{r.detail}</strong><small>Reporter: {r.reporter}{r.resolution_note?` • Resolution: ${r.resolution_note}`:''}</small>{r.messages.map(m=><small key={m.id}><MessageSquare/> {m.author}: {m.message}</small>)}</div><b>{r.resolution_action}</b><div className="row-actions">{!['RESOLVED','DISMISSED'].includes(r.status)&&<button className="mini-action" onClick={()=>addMessage(r)}>Add message</button>}{user?.role==='ADMIN'&&!['RESOLVED','DISMISSED'].includes(r.status)&&<button className="mini-action" onClick={()=>resolve(r)}>Resolve</button>}</div></div>):<div className="empty-state"><Scale/><strong>No cases here.</strong><p>Reports and dispute responses will remain attached to a persistent case record.</p></div>}</section>
 <div className="custody-note"><ShieldCheck/><p><strong>Moderation principle:</strong> reports are allegations requiring review. Reporter identity is not exposed to the affected party through case labels or messages; affected project owners, campaign owners and review authors can respond. Only explicit admin resolution actions can change status. A dismissed case cannot carry a penalty, and a final decision cannot be silently overwritten.</p></div></div>
}
