import { useEffect, useState } from 'react'
import { Coins, PlayCircle, Plus, ShieldCheck, Users } from 'lucide-react'
import { api } from '../lib/api'
import { useAuth } from '../context/AuthContext'
import type { Campaign } from '../types'

type Distribution={id:number;project_name:string;campaign_id:number;campaign_title:string;title:string;asset_symbol:string;funded_amount:string;distributed_amount:string;funding_status:string;status:string;recipient_count:number;amount_per_recipient:string|null;my_amount:string|null;disclaimer:string}

export default function RevenueShare(){
 const {user}=useAuth();const [rows,setRows]=useState<Distribution[]>([]);const [mine,setMine]=useState<Distribution[]>([]);const [campaigns,setCampaigns]=useState<Campaign[]>([]);const [show,setShow]=useState(false);const [msg,setMsg]=useState('')
 const [f,setF]=useState({campaign_id:0,title:'',asset_symbol:'',funded_amount:1000,funding_reference:''})
 const load=()=>{
  if(user?.role==='ADMIN') api<Distribution[]>('/revenue-share/admin').then(setRows).catch(()=>{})
  else if(user?.role==='CREATOR') Promise.all([api<Distribution[]>('/revenue-share'),api<Distribution[]>('/revenue-share/mine'),api<Campaign[]>('/campaigns/mine')]).then(([all,own,c])=>{setMine(own);setRows([...own,...all.filter(x=>!own.some(m=>m.id===x.id))]);setCampaigns(c);if(!f.campaign_id&&c[0])setF(v=>({...v,campaign_id:c[0].id,asset_symbol:c[0].reward_asset}))}).catch(()=>{})
  else api<Distribution[]>('/revenue-share').then(setRows).catch(()=>{})
 }
 useEffect(()=>{load()},[user?.role])
 const create=async(e:React.FormEvent)=>{e.preventDefault();try{await api('/revenue-share',{method:'POST',body:JSON.stringify(f)});setMsg('Fixed distribution pool submitted for funding verification.');setShow(false);load()}catch(e:any){setMsg(e.message||'Could not create distribution')}}
 const activate=async(id:number)=>{try{await api(`/revenue-share/${id}/activate`,{method:'POST'});setMsg('Distribution funding manually verified.');load()}catch(e:any){setMsg(e.message||'Could not activate distribution')}}
 const execute=async(id:number)=>{if(!window.confirm('Execute this one-time snapshot now? Only currently eligible completed participants will receive a share.'))return;try{const out=await api<Distribution>(`/revenue-share/${id}/execute`,{method:'POST'});setMsg(`Distribution executed: ${out.recipient_count} recipients received ${out.amount_per_recipient} ${out.asset_symbol} each.`);load()}catch(e:any){setMsg(e.message||'Could not execute distribution')}}
 return <div className="page"><div className="page-head"><div><span className="eyebrow small">FUNDED REVENUE SHARE</span><h1>Reward contributors from <em>real pools.</em></h1><p>Projects can share an already-funded community or realised-revenue pool with people who completed a qualifying Bag. NuBagz does not advertise unknown future yield.</p></div>{campaigns.length>0&&<button className="btn primary" onClick={()=>setShow(!show)}><Plus/> Create distribution</button>}</div>{msg&&<div className="form-note">{msg}</div>}
 {show&&<form className="panel builder" onSubmit={create}><h3>Create a fixed distribution pool</h3><div className="form-grid"><label>Qualifying campaign<select value={f.campaign_id} onChange={e=>{const id=Number(e.target.value);const c=campaigns.find(x=>x.id===id);setF({...f,campaign_id:id,asset_symbol:c?.reward_asset||f.asset_symbol})}}>{campaigns.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>Distribution asset<input required value={f.asset_symbol} onChange={e=>setF({...f,asset_symbol:e.target.value.toUpperCase()})}/></label><label className="full-span">Distribution title<input required value={f.title} onChange={e=>setF({...f,title:e.target.value})} placeholder="August contributor share"/></label><label>Fixed funded pool<input type="number" min="0" step="any" value={f.funded_amount} onChange={e=>setF({...f,funded_amount:Number(e.target.value)})}/></label><label>Funding transaction / reference<input required value={f.funding_reference} onChange={e=>setF({...f,funding_reference:e.target.value})}/></label></div><div className="custody-note"><ShieldCheck/><p>This creates a fixed pool only. The amount per recipient is calculated once at execution from the eligible completed-participant snapshot. It does not promise APY, future dividends or a guaranteed investment return.</p></div><button className="btn primary"><Coins/> Submit funded pool</button></form>}
 <div className="bag-grid">{rows.map(r=><article className="bag-card" key={r.id}><div className="bag-card-top"><span className="category"><Users/> {r.project_name}</span><span>{r.status}</span></div><div className="big-token">{r.asset_symbol.slice(0,3)}</div><h3>{r.title}</h3><p>Qualifying Bag: {r.campaign_title}</p><div className="bag-meta"><span><ShieldCheck/> {r.funding_status}</span><span>{Number(r.funded_amount).toLocaleString()} {r.asset_symbol} pool</span></div>{r.status==='EXECUTED'&&<div className="fund-check good"><span>{r.recipient_count} recipients</span><strong>{r.amount_per_recipient} {r.asset_symbol} each</strong><small>{r.my_amount?`You received ${r.my_amount}`:'Snapshot complete'}</small></div>}{user?.role==='ADMIN'&&r.status==='PENDING'&&<button className="btn primary full" onClick={()=>activate(r.id)}>Verify funding</button>}{mine.some(m=>m.id===r.id)&&r.status==='LIVE'&&<button className="btn primary full" onClick={()=>execute(r.id)}><PlayCircle/> Execute snapshot</button>}<small>{r.disclaimer}</small></article>)}</div>{!rows.length&&<div className="empty-state"><Coins/><strong>No verified distributions yet.</strong><p>Completed contributors will see funded project distributions here.</p></div>}</div>
}
