import { useEffect, useState } from 'react'
import { Coins, PlayCircle, Plus, ShieldCheck, Users } from 'lucide-react'
import { api } from '../lib/api'
import { useAuth } from '../context/AuthContext'
import type { Campaign } from '../types'

type Distribution={id:number;project_name:string;campaign_id:number;campaign_title:string;title:string;asset_symbol:string;funded_amount:string;distributed_amount:string;remaining_funded_amount:string;funding_status:string;funding_reference?:string;status:string;recipient_count:number;amount_per_recipient:string|null;my_amount:string|null;disclaimer:string}
type VerifyDraft={funded_amount:string;funding_reference:string}

export default function RevenueShare(){
 const {user}=useAuth();const [rows,setRows]=useState<Distribution[]>([]);const [mine,setMine]=useState<Distribution[]>([]);const [campaigns,setCampaigns]=useState<Campaign[]>([]);const [show,setShow]=useState(false);const [msg,setMsg]=useState('');const [verifyDrafts,setVerifyDrafts]=useState<Record<number,VerifyDraft>>({})
 const [f,setF]=useState({campaign_id:0,title:'',asset_symbol:'',funded_amount:1000,funding_reference:''})
 const load=()=>{
  if(user?.role==='ADMIN') api<Distribution[]>('/revenue-share/admin').then(data=>{setRows(data);setVerifyDrafts(current=>{const next={...current};data.filter(x=>x.status==='PENDING').forEach(x=>{if(!next[x.id])next[x.id]={funded_amount:x.funded_amount,funding_reference:x.funding_reference||''}});return next})}).catch(()=>{})
  else if(user?.role==='CREATOR') Promise.all([api<Distribution[]>('/revenue-share'),api<Distribution[]>('/revenue-share/mine'),api<Campaign[]>('/campaigns/mine')]).then(([all,own,c])=>{const eligible=c.filter(x=>x.project?.status==='LIVE'||x.project?.status==='APPROVED');setMine(own);setRows([...own,...all.filter(x=>!own.some(m=>m.id===x.id))]);setCampaigns(eligible);if(!f.campaign_id&&eligible[0])setF(v=>({...v,campaign_id:eligible[0].id,asset_symbol:eligible[0].reward_asset}))}).catch(()=>{})
  else api<Distribution[]>('/revenue-share').then(setRows).catch(()=>{})
 }
 useEffect(()=>{load()},[user?.role])
 const create=async(e:React.FormEvent)=>{e.preventDefault();try{await api('/revenue-share',{method:'POST',body:JSON.stringify(f)});setMsg('Funding declared. An admin must independently verify the funded amount and transaction/reference before this distribution can go live.');setShow(false);load()}catch(e:any){setMsg(e.message||'Could not create distribution')}}
 const activate=async(row:Distribution)=>{const draft=verifyDrafts[row.id]||{funded_amount:row.funded_amount,funding_reference:row.funding_reference||''};try{await api(`/revenue-share/${row.id}/activate`,{method:'POST',body:JSON.stringify({funded_amount:Number(draft.funded_amount),funding_reference:draft.funding_reference})});setMsg('Funding independently verified. The fixed distribution is now ready for its one-time snapshot.');load()}catch(e:any){setMsg(e.message||'Could not verify distribution funding')}}
 const execute=async(id:number)=>{if(!window.confirm('Execute this one-time snapshot now? Only currently eligible completed participants will receive a share.'))return;try{const out=await api<Distribution>(`/revenue-share/${id}/execute`,{method:'POST'});setMsg(`Distribution executed: ${out.recipient_count} recipients received ${out.amount_per_recipient} ${out.asset_symbol} each.`);load()}catch(e:any){setMsg(e.message||'Could not execute distribution')}}
 return <div className="page"><div className="page-head"><div><span className="eyebrow small">FUNDED REVENUE SHARE</span><h1>Reward contributors from <em>real pools.</em></h1><p>Projects can share an already-funded community or realised-revenue pool with people who completed a qualifying Bag. Creator declarations are not treated as verified funding, and NuBagz does not advertise unknown future yield.</p></div>{campaigns.length>0&&<button className="btn primary" onClick={()=>setShow(!show)}><Plus/> Create distribution</button>}</div>{msg&&<div className="form-note">{msg}</div>}
 {show&&<form className="panel builder" onSubmit={create}><h3>Create a fixed distribution pool</h3><div className="form-grid"><label>Qualifying campaign<select value={f.campaign_id} onChange={e=>{const id=Number(e.target.value);const c=campaigns.find(x=>x.id===id);setF({...f,campaign_id:id,asset_symbol:c?.reward_asset||f.asset_symbol})}}>{campaigns.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>Distribution asset<input required value={f.asset_symbol} onChange={e=>setF({...f,asset_symbol:e.target.value.toUpperCase()})}/></label><label className="full-span">Distribution title<input required minLength={4} value={f.title} onChange={e=>setF({...f,title:e.target.value})} placeholder="August contributor share"/></label><label>Declared funded pool<input type="number" min="0.00000001" step="any" value={f.funded_amount} onChange={e=>setF({...f,funded_amount:Number(e.target.value)})}/></label><label>Funding transaction / reference<input required minLength={4} value={f.funding_reference} onChange={e=>setF({...f,funding_reference:e.target.value})}/><small>This remains a declaration until admin verification.</small></label></div><div className="custody-note"><ShieldCheck/><p>This creates a fixed pool only. The amount per recipient is calculated once at execution from the eligible completed-participant snapshot. It does not promise APY, future dividends or a guaranteed investment return.</p></div><button className="btn primary"><Coins/> Submit funding declaration</button></form>}
 <div className="bag-grid">{rows.map(r=><article className="bag-card" key={r.id}><div className="bag-card-top"><span className="category"><Users/> {r.project_name}</span><span>{r.status}</span></div><div className="big-token">{r.asset_symbol.slice(0,3)}</div><h3>{r.title}</h3><p>Qualifying Bag: {r.campaign_title}</p><div className="bag-meta"><span><ShieldCheck/> {r.funding_status==='VERIFIED'?'Funding verified':'Funding declared — awaiting independent verification'}</span><span>{Number(r.funded_amount).toLocaleString()} {r.asset_symbol} pool</span></div>{r.status==='EXECUTED'&&<div className="fund-check good"><span>{r.recipient_count} recipients</span><strong>{r.amount_per_recipient} {r.asset_symbol} each</strong><small>{r.my_amount?`You received ${r.my_amount}`:`Distributed ${Number(r.distributed_amount).toLocaleString()} • remaining ${Number(r.remaining_funded_amount).toLocaleString()}`}</small></div>}{user?.role==='ADMIN'&&r.status==='PENDING'&&<div><label>Verified funded amount<input type="number" min="0.00000001" step="any" value={verifyDrafts[r.id]?.funded_amount??r.funded_amount} onChange={e=>setVerifyDrafts({...verifyDrafts,[r.id]:{funded_amount:e.target.value,funding_reference:verifyDrafts[r.id]?.funding_reference??r.funding_reference??''}})}/></label><label>Verified transaction / reference<input minLength={4} value={verifyDrafts[r.id]?.funding_reference??r.funding_reference??''} onChange={e=>setVerifyDrafts({...verifyDrafts,[r.id]:{funded_amount:verifyDrafts[r.id]?.funded_amount??r.funded_amount,funding_reference:e.target.value}})}/></label><button className="btn primary full" disabled={Number(verifyDrafts[r.id]?.funded_amount??r.funded_amount)<=0||(verifyDrafts[r.id]?.funding_reference??r.funding_reference??'').trim().length<4} onClick={()=>activate(r)}>Verify funding</button></div>}{mine.some(m=>m.id===r.id)&&r.status==='LIVE'&&<button className="btn primary full" onClick={()=>execute(r.id)}><PlayCircle/> Execute snapshot</button>}<small>{r.disclaimer}</small></article>)}</div>{!rows.length&&<div className="empty-state"><Coins/><strong>No verified distributions yet.</strong><p>Completed contributors will see funded project distributions here.</p></div>}</div>
}
