import { useEffect, useState } from 'react'
import { MessageSquare, ShieldCheck, Star } from 'lucide-react'
import { api } from '../lib/api'

type Review={id:number;username:string;rating:number;review:string;verified_participant:boolean;updated_at:string}
type ProjectReviews={project_id:number;name:string;symbol:string;average_rating:string;review_count:number;eligible_to_review:boolean;my_review:Review|null;reviews:Review[];disclaimer:string}

export default function Reviews(){const [rows,setRows]=useState<ProjectReviews[]>([]);const [msg,setMsg]=useState('');const load=()=>api<ProjectReviews[]>('/reviews/projects').then(setRows);useEffect(()=>{load()},[])
 const write=async(p:ProjectReviews)=>{const ratingRaw=window.prompt(`Rate your NuBagz participation experience with ${p.name} from 1–5`,String(p.my_review?.rating||5));if(ratingRaw===null)return;const rating=Number(ratingRaw);if(!Number.isInteger(rating)||rating<1||rating>5){setMsg('Rating must be a whole number from 1 to 5.');return}const review=window.prompt('Share your participant experience',p.my_review?.review||'');if(!review)return;try{await api(`/reviews/projects/${p.project_id}`,{method:'POST',body:JSON.stringify({rating,review})});setMsg('Verified participant review saved.');load()}catch(e:any){setMsg(e.message||'Could not save review')}}
 return <div className="page"><div className="page-head"><div><span className="eyebrow small">VERIFIED REVIEWS</span><h1>Experience, not <em>hype.</em></h1><p>Only users who completed a funded project campaign can review that project. Ratings describe the NuBagz participant experience—not investment quality.</p></div></div>{msg&&<div className="form-note">{msg}</div>}
 <div className="bag-grid">{rows.map(p=><article className="bag-card" key={p.project_id}><div className="bag-card-top"><span className="category"><Star/> ${p.symbol}</span><span>{p.review_count} reviews</span></div><div className="big-token">{p.average_rating}</div><h3>{p.name}</h3><p>{p.disclaimer}</p><div className="bag-meta"><span><ShieldCheck/> Verified participants only</span><span>{p.average_rating}/5</span></div>{p.eligible_to_review&&<button className="btn primary full" onClick={()=>write(p)}><MessageSquare/> {p.my_review?'Update your review':'Review your experience'}</button>}{p.reviews.slice(0,3).map(r=><div className="custody-note" key={r.id}><Star/><p><strong>{r.username} • {r.rating}/5</strong><br/>{r.review}</p></div>)}</article>)}</div></div>}
