import { useEffect, useState } from 'react'
import { ArrowLeftRight, ExternalLink, ShieldCheck, Wallet } from 'lucide-react'
import { api } from '../lib/api'

type Status={configured:boolean;mode:string;execution_model:string}
type Intent={id:number;chain:string;sell_asset:string;buy_asset:string;sell_amount:string;max_slippage_bps:number;status:string;wallet_address:string;provider:string|null;provider_quote_id:string|null;quoted_buy_amount:string|null;quote_expires_at:string|null;transaction_payload:Record<string,unknown>|null;created_at:string}

export default function Swaps(){
 const [status,setStatus]=useState<Status|null>(null);const [rows,setRows]=useState<Intent[]>([]);const [msg,setMsg]=useState('');const [f,setF]=useState({chain:'Avalanche',sell_asset:'',buy_asset:'',sell_amount:1,max_slippage_bps:100})
 const load=()=>Promise.all([api<Status>('/swaps/status'),api<Intent[]>('/swaps/intents')]).then(([s,r])=>{setStatus(s);setRows(r)});useEffect(()=>{load()},[])
 const create=async(e:React.FormEvent)=>{e.preventDefault();try{await api('/swaps/intents',{method:'POST',body:JSON.stringify(f)});setMsg(status?.configured?'Swap intent created. Request a live provider quote when ready.':'Draft saved. No swap provider is configured, so no quote or transaction can be generated.');load()}catch(e:any){setMsg(e.message||'Could not create swap intent')}}
 const quote=async(id:number)=>{try{const out=await api<Intent>(`/swaps/intents/${id}/quote`,{method:'POST'});setMsg(`Live quote received: ${out.quoted_buy_amount} ${out.buy_asset}. The transaction still requires signature and broadcast from your verified wallet.`);load()}catch(e:any){setMsg(e.message||'Could not request quote')}}
 return <div className="page"><div className="page-head"><div><span className="eyebrow small">SWAP ROUTING</span><h1>Swap through your <em>verified wallet.</em></h1><p>NuBagz can request provider-backed unsigned swap transactions. It never marks a swap successful just because a button was clicked.</p></div></div>{msg&&<div className="form-note">{msg}</div>}
 <div className="stats-grid"><div className={status?.configured?'stat-card hot':'stat-card'}><span><ArrowLeftRight/>ROUTING PROVIDER</span><strong>{status?.configured?'READY':'NOT CONFIGURED'}</strong><small>{status?.mode||'—'}</small></div><div className="stat-card"><span><Wallet/>SWAP INTENTS</span><strong>{rows.length}</strong><small>Drafts and live quotes</small></div></div>
 <form className="panel builder" onSubmit={create}><div className="panel-head"><div><span>NEW SWAP INTENT</span><h2>Prepare a wallet swap</h2></div></div><div className="form-grid"><label>Chain<select value={f.chain} onChange={e=>setF({...f,chain:e.target.value})}><option>Avalanche</option><option>Ethereum</option><option>Base</option><option>Arbitrum</option><option>Polygon</option></select></label><label>Max slippage (bps)<input type="number" min="1" max="500" value={f.max_slippage_bps} onChange={e=>setF({...f,max_slippage_bps:Number(e.target.value)})}/></label><label>Sell asset<input required value={f.sell_asset} onChange={e=>setF({...f,sell_asset:e.target.value.toUpperCase()})} placeholder="USDC or token address"/></label><label>Buy asset<input required value={f.buy_asset} onChange={e=>setF({...f,buy_asset:e.target.value.toUpperCase()})} placeholder="AVAX or token address"/></label><label>Sell amount<input type="number" min="0" step="any" value={f.sell_amount} onChange={e=>setF({...f,sell_amount:Number(e.target.value)})}/></label></div><button className="btn primary"><ArrowLeftRight/> Save swap intent</button></form>
 <section className="panel"><div className="panel-head"><div><span>YOUR INTENTS</span><h2>Quotes & transaction requests</h2></div></div>{rows.length?rows.map(r=><div className="activity-row" key={r.id}><div><span>{r.chain} • {r.status}</span><strong>{r.sell_amount} {r.sell_asset} → {r.quoted_buy_amount?`${r.quoted_buy_amount} ${r.buy_asset}`:r.buy_asset}</strong><small>Wallet {r.wallet_address.slice(0,8)}…{r.wallet_address.slice(-6)} • max slippage {r.max_slippage_bps} bps{r.provider?` • ${r.provider}`:''}</small></div><b>{r.status}</b><div className="row-actions">{r.status==='DRAFT'&&<button className="mini-action" disabled={!status?.configured} onClick={()=>quote(r.id)}>Request quote</button>}{r.transaction_payload&&<button className="mini-action" onClick={()=>navigator.clipboard?.writeText(JSON.stringify(r.transaction_payload))}>Copy tx <ExternalLink/></button>}</div></div>):<div className="empty-state"><ArrowLeftRight/><strong>No swap intents yet.</strong><p>Create a draft after connecting and verifying an EVM wallet.</p></div>}</section>
 <div className="custody-note"><ShieldCheck/><p><strong>Execution boundary:</strong> {status?.execution_model||'A verified wallet and configured routing provider are required.'} Drafts and failed quote requests do not debit NuBagz balances or move crypto.</p></div></div>
}