import { useEffect, useMemo, useRef, useState } from 'react'
import { AlertTriangle, ArrowDown, ArrowLeftRight, CheckCircle2, ExternalLink, Gauge, Info, RefreshCw, Route, Search, ShieldCheck, Sparkles, Wallet } from 'lucide-react'
import { useWallets } from '@privy-io/react-auth'
import { api } from '../lib/api'
import { privyConfigured } from '../context/WalletProvider'

const NATIVE='0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee'
const QUOTE_FRESHNESS_SECONDS=15

type Token={address:string;symbol:string;name:string;decimals:number;kind:string;metadata_estimated?:boolean}
type Chain={key:string;name:string;display_name:string;chain_id:number;native_symbol:string;rpc_url?:string|null;explorer:string;dexscreener:string;wrapped_native?:string|null;tokens:Token[]}
type Config={primary_chain:string;fee_bps:number;fee_percent:string;wallet_address:string|null;providers:Record<string,boolean>;provider_auth?:Record<string,string>;ready:boolean;chains:Chain[];execution_model:string}
type RouteQuote={session_id:number;provider:string;provider_quote_id?:string;buy_amount:string;min_buy_amount:string;allowance_target?:string|null;allowance_actual?:string|null;requires_approval:boolean;transaction:Record<string,unknown>;sources:string[];network_fee_native?:string|null;network_fee_usd?:string|null;nubagz_fee_amount?:string|null;nubagz_fee_bps:number;recommended:boolean;provider_fees?:unknown}
type QuoteResponse={chain:string;chain_id:number;wallet_address:string;sell_token:string;buy_token:string;sell_amount:string;slippage_bps:number;nubagz_fee_bps:number;routes:RouteQuote[];provider_errors:Record<string,string>;quote_expires_seconds:number}
type Market={available:boolean;pair_address?:string;dex?:string;url?:string;embed_url?:string;price_usd?:string;liquidity_usd?:string;volume_24h_usd?:string;price_change_24h?:number;fdv?:number;market_cap?:number;pair_age_days?:number|null;signals:string[];disclaimer?:string}
type HistoryRow={session_id:number;chain:string;provider:string;status:string;sell_token:string;buy_token:string;sell_amount:string;quoted_buy_amount:string|null;wallet_address:string;tx_hash?:string;actual_buy_amount?:string;block_number?:string;gas_used?:string;explorer_url?:string;created_at:string}
type ExecutorProps={route:RouteQuote;chain:Chain;sellToken:Token;sellAmount:string;walletAddress:string;onMessage:(value:string)=>void;onConfirmed:(result:any)=>void;disabled?:boolean}

function parseUnits(value:string,decimals:number){
 const text=value.trim();if(!/^\d*(\.\d*)?$/.test(text)||!text||text==='.')throw new Error('Enter a valid amount')
 const [whole='0',fraction='']=text.split('.');if(fraction.length>decimals)throw new Error(`Maximum ${decimals} decimal places`)
 return (BigInt(whole||'0')*10n**BigInt(decimals)+BigInt((fraction+'0'.repeat(decimals)).slice(0,decimals)||'0')).toString()
}
function formatUnits(value:string|undefined|null,decimals:number,max=8){
 if(!value)return'—';try{const n=BigInt(value);const base=10n**BigInt(decimals);const whole=n/base;const fraction=(n%base).toString().padStart(decimals,'0').slice(0,max).replace(/0+$/,'');return fraction?`${whole}.${fraction}`:whole.toString()}catch{return value}
}
function formatEstimate(value:number|undefined|null){if(value===undefined||value===null||!Number.isFinite(value))return'—';if(value===0)return'0';if(value>=1000)return value.toLocaleString('en-GB',{maximumFractionDigits:3});if(value>=1)return value.toLocaleString('en-GB',{maximumFractionDigits:6});return value.toLocaleString('en-GB',{maximumSignificantDigits:7})}
function money(value:string|number|undefined|null){const n=Number(value);return Number.isFinite(n)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:n>=100?0:2}).format(n):'—'}
function usdEstimate(amount:string|number|undefined|null,price:string|number|undefined|null){const a=Number(amount),p=Number(price);return Number.isFinite(a)&&a>=0&&Number.isFinite(p)&&p>0?a*p:null}
function shortAddress(value?:string|null){return value?`${value.slice(0,6)}…${value.slice(-4)}`:'—'}
function toHexQuantity(value:unknown){if(value===undefined||value===null)return undefined;const text=String(value);if(text.startsWith('0x'))return text;try{return `0x${BigInt(text).toString(16)}`}catch{return text}}
function approvalData(spender:string,amount:string){return `0x095ea7b3${spender.toLowerCase().replace('0x','').padStart(64,'0')}${BigInt(amount).toString(16).padStart(64,'0')}`}
function allowanceData(owner:string,spender:string){return `0xdd62ed3e${owner.toLowerCase().replace('0x','').padStart(64,'0')}${spender.toLowerCase().replace('0x','').padStart(64,'0')}`}
function cleanTransaction(raw:Record<string,unknown>,from:string){const tx:any={from,to:raw.to,data:raw.data||'0x'};for(const key of ['value','gas','gasLimit','gasPrice','maxFeePerGas','maxPriorityFeePerGas','nonce']){if(raw[key]!==undefined&&raw[key]!==null)tx[key==='gasLimit'?'gas':key]=toHexQuantity(raw[key])}return tx}

function SwapExecutor({route,chain,sellToken,sellAmount,walletAddress,onMessage,onConfirmed,disabled}:ExecutorProps){
 const {wallets}=useWallets();const [busy,setBusy]=useState(false);const signer=wallets.find(w=>w.address.toLowerCase()===walletAddress.toLowerCase());const signerReady=Boolean(signer)
 const execute=async()=>{if(!signer){onMessage('Reconnect the exact verified interactive signer before swapping. A reward-only address cannot sign.');return}setBusy(true);try{
   const wallet=signer
   const provider=await wallet.getEthereumProvider();const wanted=`0x${chain.chain_id.toString(16)}`;const current=String(await provider.request({method:'eth_chainId'}))
   if(current.toLowerCase()!==wanted.toLowerCase()){
     try{await provider.request({method:'wallet_switchEthereumChain',params:[{chainId:wanted}]})}
     catch(error:any){if(error?.code!==4902||!chain.rpc_url)throw error;await provider.request({method:'wallet_addEthereumChain',params:[{chainId:wanted,chainName:chain.display_name,nativeCurrency:{name:chain.native_symbol,symbol:chain.native_symbol,decimals:18},rpcUrls:[chain.rpc_url],blockExplorerUrls:[chain.explorer]}]})}
   }
   if(route.requires_approval&&sellToken.address.toLowerCase()!==NATIVE&&route.allowance_target){
     let allowance=0n
     try{const raw=await provider.request({method:'eth_call',params:[{to:sellToken.address,data:allowanceData(walletAddress,route.allowance_target)},'latest']}) as string;allowance=BigInt(raw||'0x0')}catch{}
     if(allowance<BigInt(sellAmount)){
       onMessage(`Approve exactly ${formatUnits(sellAmount,sellToken.decimals)} ${sellToken.symbol} in your wallet.`)
       const approvalHash=await provider.request({method:'eth_sendTransaction',params:[{from:walletAddress,to:sellToken.address,data:approvalData(route.allowance_target,sellAmount),value:'0x0'}]}) as string
       if(approvalHash){let mined=false;for(let i=0;i<45;i++){const receipt=await provider.request({method:'eth_getTransactionReceipt',params:[approvalHash]}) as any;if(receipt){if(parseInt(receipt.status||'0x0',16)!==1)throw new Error('Token approval failed.');mined=true;break}await new Promise(r=>setTimeout(r,1200))}if(!mined)throw new Error('Token approval is still pending. Refresh the route after it confirms.')}
     }
   }
   onMessage(`Confirm the ${route.provider} swap in your wallet. NuBagz never signs for you.`)
   const txHash=await provider.request({method:'eth_sendTransaction',params:[cleanTransaction(route.transaction,walletAddress)]}) as string
   onMessage(`Swap submitted: ${shortAddress(txHash)}. Waiting for an on-chain receipt…`)
   let result:any=null
   for(let i=0;i<50;i++){try{result=await api('/swaps/confirm',{method:'POST',body:JSON.stringify({session_id:route.session_id,tx_hash:txHash})});if(result?.status!=='SUBMITTED')break}catch(error:any){if(i>4)throw error}await new Promise(r=>setTimeout(r,1400))}
   onConfirmed(result||{status:'SUBMITTED',tx_hash:txHash});onMessage(result?.confirmed?'Swap confirmed on-chain. The receipt below is based on the exact real transaction.':'Swap submitted. Confirmation will appear in your history once mined.')
 }catch(error:any){onMessage(error?.message||'Swap execution failed or was cancelled.')}finally{setBusy(false)}}
 return <>{!signerReady&&<div className="inline-guidance warning"><AlertTriangle/><span>Verified signer {shortAddress(walletAddress)} is not currently available in the wallet provider. Reconnect that exact wallet; changing the reward destination does not fix signer access.</span></div>}<button className="btn primary full execute-swap-btn" disabled={busy||disabled||!signerReady} onClick={()=>void execute()}>{busy?'Waiting for wallet…':disabled?<><RefreshCw/> Quote stale — refresh route</>:!signerReady?<><Wallet/> Reconnect verified signer</>:<><Wallet/> Review & swap with {route.provider}</>}</button></>
}

function TokenPicker({label,chain,value,onChange}:{label:string;chain:Chain;value:Token;onChange:(token:Token)=>void}){
 const rootRef=useRef<HTMLDivElement|null>(null);const [open,setOpen]=useState(false);const [q,setQ]=useState('');const [rows,setRows]=useState<Token[]>(chain.tokens||[]);const [loading,setLoading]=useState(false)
 useEffect(()=>{setRows(chain.tokens||[]);setQ('');setOpen(false)},[chain.key])
 useEffect(()=>{if(!open)return;const closeOnOutside=(event:PointerEvent)=>{if(rootRef.current&&!rootRef.current.contains(event.target as Node)){setOpen(false);setQ('')}};document.addEventListener('pointerdown',closeOnOutside);return()=>document.removeEventListener('pointerdown',closeOnOutside)},[open])
 useEffect(()=>{if(!open||!q.trim()){setRows(chain.tokens||[]);return}const timer=setTimeout(()=>{setLoading(true);api<Token[]>(`/swaps/token-search?chain=${encodeURIComponent(chain.name)}&q=${encodeURIComponent(q.trim())}`).then(setRows).catch(()=>setRows([])).finally(()=>setLoading(false))},250);return()=>clearTimeout(timer)},[q,open,chain])
 return <div ref={rootRef} className={`swap-token-field ${open?'open':''}`}><span>{label}</span><button type="button" className="token-select" onClick={()=>setOpen(v=>!v)} aria-expanded={open}><b>{value.symbol}</b><small>{value.kind==='native'?chain.display_name:shortAddress(value.address)}</small><ArrowDown/></button>{open&&<div className="token-menu"><div className="token-search"><Search/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Search token or paste 0x contract"/></div>{loading&&<small>Reading token metadata…</small>}{rows.map(token=><button type="button" key={token.address.toLowerCase()} onClick={()=>{onChange(token);setOpen(false);setQ('')}}><div><strong>{token.symbol}</strong><span>{token.name}</span></div><small>{token.kind==='native'?'Native':shortAddress(token.address)}{token.metadata_estimated?' • metadata estimated':''}</small></button>)}{!loading&&!rows.length&&<div className="token-empty">No matching token found on this chain.</div>}</div>}</div>
}

export default function Swaps(){
 const [config,setConfig]=useState<Config|null>(null);const [chainKey,setChainKey]=useState('robinhood');const [sell,setSell]=useState<Token|null>(null);const [buy,setBuy]=useState<Token|null>(null);const [amount,setAmount]=useState('0.1');const [slippage,setSlippage]=useState(100);const [quote,setQuote]=useState<QuoteResponse|null>(null);const [quoteSeconds,setQuoteSeconds]=useState(0);const [selected,setSelected]=useState(0);const [buyMarket,setBuyMarket]=useState<Market|null>(null);const [sellMarket,setSellMarket]=useState<Market|null>(null);const [history,setHistory]=useState<HistoryRow[]>([]);const [msg,setMsg]=useState('');const [quoting,setQuoting]=useState(false)
 const loadHistory=()=>api<HistoryRow[]>('/swaps/history').then(setHistory).catch(()=>setHistory([]))
 const clearQuote=()=>{setQuote(null);setQuoteSeconds(0);setSelected(0)}
 useEffect(()=>{api<Config>('/swaps/config').then(c=>{setConfig(c);const robin=c.chains.find(x=>x.key==='robinhood')||c.chains[0];setChainKey(robin.key);setSell(robin.tokens[0]);setBuy(robin.tokens.find(t=>t.symbol==='USDG')||robin.tokens[1]||robin.tokens[0])}).catch(e=>setMsg(e.message||'Could not load swap configuration'));void loadHistory()},[])
 const chain=useMemo(()=>config?.chains.find(c=>c.key===chainKey)||null,[config,chainKey])
 useEffect(()=>{if(!chain)return;setQuote(null);setQuoteSeconds(0);setSelected(0);setSell(chain.tokens[0]);setBuy(chain.tokens.find(t=>t.symbol==='USDG')||chain.tokens[1]||chain.tokens[0])},[chainKey])
 useEffect(()=>{if(!chain||!buy){setBuyMarket(null);return}api<Market>(`/swaps/market?chain=${encodeURIComponent(chain.name)}&token=${encodeURIComponent(buy.address)}`).then(setBuyMarket).catch(()=>setBuyMarket(null))},[chain,buy])
 useEffect(()=>{if(!chain||!sell){setSellMarket(null);return}api<Market>(`/swaps/market?chain=${encodeURIComponent(chain.name)}&token=${encodeURIComponent(sell.address)}`).then(setSellMarket).catch(()=>setSellMarket(null))},[chain,sell])
 useEffect(()=>{if(!quote||quoteSeconds<=0)return;const timer=window.setTimeout(()=>setQuoteSeconds(seconds=>Math.max(0,seconds-1)),1000);return()=>window.clearTimeout(timer)},[quote,quoteSeconds])
 useEffect(()=>{if(quote&&quoteSeconds===0)setMsg('Executable quote is 15 seconds old. Refresh the route before swapping.')},[quote,quoteSeconds])
 const active=quote?.routes[selected]
 const quoteExpired=Boolean(quote)&&quoteSeconds<=0
 const marketEstimate=useMemo(()=>{const input=Number(amount),sp=Number(sellMarket?.price_usd),bp=Number(buyMarket?.price_usd);if(!(input>0&&sp>0&&bp>0))return null;const feeFactor=1-(config?.fee_bps||0)/10000;return input*sp/bp*feeFactor},[amount,sellMarket,buyMarket,config])
 const receiveText=active&&buy?formatUnits(active.buy_amount,buy.decimals):formatEstimate(marketEstimate)
 const receiveMode=active?(quoteExpired?'QUOTE STALE':'EXECUTABLE QUOTE'):marketEstimate!==null?'MARKET ESTIMATE':'WAITING FOR PRICE'
 const minReceived=active&&buy?formatUnits(active.min_buy_amount,buy.decimals):'—'
 const sellTradeUsd=useMemo(()=>usdEstimate(amount,sellMarket?.price_usd),[amount,sellMarket?.price_usd])
 const receiveTradeUsd=useMemo(()=>usdEstimate(receiveText,buyMarket?.price_usd),[receiveText,buyMarket?.price_usd])
 const signals=buyMarket?.signals||[]
 const requestQuote=async()=>{if(!chain||!sell||!buy)return;let base='';try{base=parseUnits(amount,sell.decimals);if(BigInt(base)<=0n)throw new Error('Enter an amount greater than zero.')}catch(e:any){setMsg(e.message||'Enter a valid amount.');return}setQuoting(true);clearQuote();setMsg('Racing live fee-enabled routes…');try{const out=await api<QuoteResponse>('/swaps/quote',{method:'POST',body:JSON.stringify({chain:chain.name,sell_token:sell.address,buy_token:buy.address,sell_amount:base,slippage_bps:slippage})});setQuote(out);setQuoteSeconds(Math.min(QUOTE_FRESHNESS_SECONDS,out.quote_expires_seconds||QUOTE_FRESHNESS_SECONDS));setSelected(0);const failed=Object.entries(out.provider_errors||{}).filter(([,v])=>v);setMsg(out.routes.length>1?`Route Race complete — ${out.routes.length} executable routes compared.`:`Executable ${out.routes[0]?.provider||''} route ready.${failed.length?' Another router was unavailable.':''}`)}catch(e:any){setMsg(e.message||'No executable route is available for this pair right now.')}finally{setQuoting(false)}}
 const changePair=()=>{setSell(buy);setBuy(sell);clearQuote();setMsg('')}
 const changeChain=(key:string)=>{setChainKey(key);setMsg('')}
 const amountWidth=`${Math.max(4,Math.min(18,amount.length+1))}ch`
 return <div className="page swap-page">
  <div className="page-head swap-head"><div><span className="eyebrow small">NUBAGZ SWAP / ROUTE RACE</span><h1>Trade onchain. <em>Keep the keys.</em></h1><p>Robinhood Chain is first-class. See a live market estimate immediately, then compare genuine fee-enabled routes before your wallet signs anything.</p></div></div>
  <div className="swap-workspace">
   <section className="panel swap-terminal">
    <div className="terminal-topbar"><div className="network-control"><span>NETWORK</span><select value={chainKey} onChange={e=>changeChain(e.target.value)}>{config?.chains.map(c=><option key={c.key} value={c.key}>{c.display_name}{c.key==='robinhood'?' • PRIMARY':''}</option>)}</select></div><div className={`wallet-chip ${config?.wallet_address?'connected':''}`}><Wallet/><span>{config?.wallet_address?shortAddress(config.wallet_address):'Verify wallet to trade'}</span></div></div>
    {chain&&sell&&buy&&<div className="trade-composer"><div className="swap-box"><div className="box-row"><TokenPicker label="YOU PAY" chain={chain} value={sell} onChange={t=>{setSell(t);clearQuote()}}/></div><div className="trade-value-line"><input className="swap-amount" style={{width:amountWidth}} value={amount} onChange={e=>{setAmount(e.target.value);clearQuote()}} inputMode="decimal" placeholder="0.0"/><span className="trade-asset-symbol">{sell.symbol}</span>{sellTradeUsd!==null&&<span className="trade-usd-estimate">~ {money(sellTradeUsd)}</span>}</div><small>{sell.name} • {sell.kind==='native'?'native gas asset':sell.address}</small></div><button className="swap-flip" type="button" onClick={changePair} aria-label="Swap pay and receive tokens"><ArrowLeftRight/></button><div className="swap-box receive"><div className="box-row"><TokenPicker label="YOU RECEIVE" chain={chain} value={buy} onChange={t=>{setBuy(t);clearQuote()}}/><span className={`quote-mode ${active&&!quoteExpired?'firm':''}`}>{receiveMode}</span></div><div className="trade-value-line output-value-line"><strong className={`swap-output ${marketEstimate!==null&&!active?'estimated':''}`}>{receiveText}</strong><span className="trade-asset-symbol">{buy.symbol}</span>{receiveTradeUsd!==null&&<span className="trade-usd-estimate">~ {money(receiveTradeUsd)}</span>}</div><div className="receive-meta"><small>{buy.name} • {buy.kind==='native'?'native gas asset':buy.address}</small>{!active&&marketEstimate!==null&&<small>Indicative DexScreener cross-price after NuBagz fee. Final route can differ.</small>}</div></div></div>}
    <div className="swap-settings-row"><label>Max slippage<select value={slippage} onChange={e=>{setSlippage(Number(e.target.value));clearQuote()}}><option value={50}>0.5%</option><option value={100}>1.0%</option><option value={200}>2.0%</option><option value={300}>3.0%</option></select></label><div><span>Route engines</span><strong>{Object.entries(config?.providers||{}).filter(([,v])=>v).map(([k])=>k).join(' + ')||'Setup required'}</strong></div><div><span>NuBagz fee</span><strong>{config?.fee_percent||'—'}%</strong></div></div>
    {msg&&<div className={`swap-status ${msg.toLowerCase().includes('no executable')||msg.toLowerCase().includes('unavailable')||msg.toLowerCase().includes('old')?'warning':''}`}><Info/><span>{msg}</span></div>}
    {chain&&sell&&buy&&<button className="btn primary full route-race-btn" disabled={quoting||!config?.wallet_address||sell.address.toLowerCase()===buy.address.toLowerCase()} onClick={()=>void requestQuote()}><Route/>{quoting?'Checking live routes…':quote?'Refresh executable route':'Find best executable route'}</button>}
    {!config?.wallet_address&&<div className="inline-guidance"><ShieldCheck/><span>A verified interactive wallet is required for an executable quote because the router builds the transaction for the actual signer. Reward-only addresses cannot execute swaps.</span></div>}
    {quote&&active&&buy&&sell&&chain&&<div className={`route-results ${quoteExpired?'stale':''}`}><div className="route-results-head"><div className="route-results-title"><Sparkles/><span>ROUTE RACE</span></div><div className="quote-freshness-control"><span className={`quote-timer ${quoteSeconds<=5&&!quoteExpired?'urgent':''} ${quoteExpired?'expired':''}`}>{quoteExpired?'Quote stale — refresh':`Fresh for 00:${String(quoteSeconds).padStart(2,'0')}`}</span><button type="button" className="mini-action quote-refresh-btn" disabled={quoting} onClick={()=>void requestQuote()}><RefreshCw/>{quoting?'Refreshing…':'Refresh quote'}</button></div></div>{quote.routes.map((r,i)=><button type="button" key={`${r.provider}-${r.session_id}`} className={`route-card ${i===selected?'selected':''}`} onClick={()=>setSelected(i)}><div><span>{r.recommended?'BEST OUTPUT':'ALTERNATIVE'}</span><strong>{r.provider}</strong><small>{r.sources?.length?r.sources.join(' → '):'aggregated liquidity'}</small></div><div><b>{formatUnits(r.buy_amount,buy.decimals)} {buy.symbol}</b><small>minimum {formatUnits(r.min_buy_amount,buy.decimals)}</small></div></button>)}<div className="execution-breakdown"><div><span>You pay</span><b>{amount} {sell.symbol}</b></div><div><span>Expected</span><b>{formatUnits(active.buy_amount,buy.decimals)} {buy.symbol}</b></div><div><span>Minimum received</span><b>{minReceived} {buy.symbol}</b></div><div><span>Approval</span><b>{active.requires_approval?'Exact amount only':'Not required'}</b></div><div><span>NuBagz fee</span><b>{config?.fee_percent}%</b></div><div><span>Router</span><b>{active.provider}</b></div></div>{privyConfigured&&config?.wallet_address?<SwapExecutor route={active} chain={chain} sellToken={sell} sellAmount={quote.sell_amount} walletAddress={config.wallet_address} onMessage={setMsg} onConfirmed={()=>void loadHistory()} disabled={quoteExpired}/>:<div className="inline-guidance warning"><AlertTriangle/><span>Connect and verify your interactive EVM wallet to execute this route. A payout-only reward address cannot sign a swap.</span></div>}</div>}
    <div className="execution-protection"><ShieldCheck/><div><strong>Execution protection</strong><p>Market estimates are informational. Executable quotes are treated as fresh for 15 seconds and must be refreshed once stale. NuBagz never holds your keys or swap funds; the exact verified signer must currently be available in your wallet provider, then your wallet separately approves and signs the transaction. NuBagz adds no extra confirmation layer.</p></div><div className="protection-fee"><span>PLATFORM FEE</span><b>{config?.fee_percent||'—'}%</b></div></div>
   </section>
   <section className="panel market-panel"><div className="panel-head market-head"><div><span>MARKET VIEW</span><h2>{buy?.symbol||'Token'} / market</h2></div>{buyMarket?.url&&<a className="mini-action" href={buyMarket.url} target="_blank" rel="noreferrer">Open DexScreener <ExternalLink/></a>}</div>{buyMarket?.available&&buyMarket.embed_url?<iframe title={`${buy?.symbol} DexScreener chart`} src={buyMarket.embed_url} className="dex-chart" loading="lazy"/>:<div className="market-empty"><Gauge/><strong>No DexScreener pair found</strong><p>An aggregator may still find executable liquidity even when a public chart is unavailable.</p></div>}{buyMarket?.available&&<div className="market-stats"><div><span>Price</span><b>{money(buyMarket.price_usd)}</b></div><div><span>24h</span><b>{buyMarket.price_change_24h??'—'}%</b></div><div><span>Liquidity</span><b>{money(buyMarket.liquidity_usd)}</b></div><div><span>24h volume</span><b>{money(buyMarket.volume_24h_usd)}</b></div></div>}
    <div className="market-signal-strip"><div className="signal-title"><ShieldCheck/><span><b>Bag Z Swap Check</b><small>Execution signals, not a safety rating.</small></span></div><div className="signal-chips">{signals.includes('LOW_LIQUIDITY')&&<span className="warn"><AlertTriangle/> Low liquidity</span>}{signals.includes('NEW_PAIR')&&<span className="warn"><AlertTriangle/> New pair</span>}{signals.includes('NO_DEXSCREENER_PAIR')&&<span className="warn"><AlertTriangle/> No public pair</span>}{signals.includes('NO_BASIC_MARKET_WARNING')&&<span><CheckCircle2/> No basic market warning</span>}<span><ShieldCheck/> Non-custodial</span></div></div>
   </section>
  </div>
  <section className="panel swap-history"><div className="panel-head"><div><span>REAL SWAP RECEIPTS</span><h2>Wallet-signed activity</h2></div></div>{history.length?history.map(row=><div className="activity-row" key={row.session_id}><div><span>{row.chain} • {row.provider}</span><strong>{row.status} {row.tx_hash?`• ${shortAddress(row.tx_hash)}`:''}</strong><small>Quoted output {row.quoted_buy_amount||'—'} base units{row.actual_buy_amount?` • observed received ${row.actual_buy_amount} base units`:''}</small></div><div className="row-actions">{row.explorer_url&&<a className="mini-action" href={row.explorer_url} target="_blank" rel="noreferrer">Block explorer <ExternalLink/></a>}</div></div>):<div className="empty-state compact"><ArrowLeftRight/><strong>No executed swaps yet.</strong><p>Finding a quote does not create a trade. Receipts appear only for real wallet transactions.</p></div>}</section>
 </div>
}
