import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, ArrowDown, ArrowLeftRight, CheckCircle2, ExternalLink, Gauge, Route, Search, ShieldCheck, Sparkles, Wallet } from 'lucide-react'
import { useWallets } from '@privy-io/react-auth'
import { api } from '../lib/api'
import { privyConfigured } from '../context/WalletProvider'

const NATIVE='0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee'

type Token={address:string;symbol:string;name:string;decimals:number;kind:string;metadata_estimated?:boolean}
type Chain={key:string;name:string;display_name:string;chain_id:number;native_symbol:string;rpc_url?:string|null;explorer:string;dexscreener:string;wrapped_native?:string|null;tokens:Token[]}
type Config={primary_chain:string;fee_bps:number;fee_percent:string;wallet_address:string|null;providers:Record<string,boolean>;ready:boolean;chains:Chain[];execution_model:string}
type RouteQuote={session_id:number;provider:string;provider_quote_id?:string;buy_amount:string;min_buy_amount:string;allowance_target?:string|null;allowance_actual?:string|null;requires_approval:boolean;transaction:Record<string,unknown>;sources:string[];network_fee_native?:string|null;network_fee_usd?:string|null;nubagz_fee_amount?:string|null;nubagz_fee_bps:number;recommended:boolean;provider_fees?:unknown}
type QuoteResponse={chain:string;chain_id:number;wallet_address:string;sell_token:string;buy_token:string;sell_amount:string;slippage_bps:number;nubagz_fee_bps:number;routes:RouteQuote[];provider_errors:Record<string,string>;quote_expires_seconds:number}
type Market={available:boolean;pair_address?:string;dex?:string;url?:string;embed_url?:string;price_usd?:string;liquidity_usd?:string;volume_24h_usd?:string;price_change_24h?:number;fdv?:number;market_cap?:number;pair_age_days?:number|null;signals:string[];disclaimer?:string}
type HistoryRow={session_id:number;chain:string;provider:string;status:string;sell_token:string;buy_token:string;sell_amount:string;quoted_buy_amount:string|null;wallet_address:string;tx_hash?:string;actual_buy_amount?:string;block_number?:string;gas_used?:string;explorer_url?:string;created_at:string}

type ExecutorProps={route:RouteQuote;chain:Chain;sellToken:Token;sellAmount:string;walletAddress:string;onMessage:(value:string)=>void;onConfirmed:(result:any)=>void;disabled?:boolean}

function parseUnits(value:string,decimals:number){
 const text=value.trim();if(!/^\d*(\.\d*)?$/.test(text)||!text||text==='.')throw new Error('Enter a valid amount')
 const [whole='0',fraction='']=text.split('.');if(fraction.length>decimals)throw new Error(`Maximum ${decimals} decimal places`)
 return (BigInt(whole||'0')*10n**BigInt(decimals)+BigInt((fraction+'0'.repeat(decimals)).slice(0,decimals)||'0')).toString()
}
function formatUnits(value:string|undefined|null,decimals:number,max=8){
 if(!value)return'—';try{const n=BigInt(value);const base=10n**BigInt(decimals);const whole=n/base;const fraction=(n%base).toString().padStart(decimals,'0').slice(0,max).replace(/0+$/,'');return fraction?`${whole}.${fraction}`:whole.toString()}catch{return value}
}
function money(value:string|number|undefined|null){const n=Number(value);return Number.isFinite(n)?new Intl.NumberFormat('en-GB',{style:'currency',currency:'USD',maximumFractionDigits:n>=100?0:2}).format(n):'—'}
function shortAddress(value?:string|null){return value?`${value.slice(0,6)}…${value.slice(-4)}`:'—'}
function toHexQuantity(value:unknown){if(value===undefined||value===null)return undefined;const text=String(value);if(text.startsWith('0x'))return text;try{return `0x${BigInt(text).toString(16)}`}catch{return text}}
function approvalData(spender:string,amount:string){return `0x095ea7b3${spender.toLowerCase().replace('0x','').padStart(64,'0')}${BigInt(amount).toString(16).padStart(64,'0')}`}
function allowanceData(owner:string,spender:string){return `0xdd62ed3e${owner.toLowerCase().replace('0x','').padStart(64,'0')}${spender.toLowerCase().replace('0x','').padStart(64,'0')}`}
function cleanTransaction(raw:Record<string,unknown>,from:string){const tx:any={from,to:raw.to,data:raw.data||'0x'};for(const key of ['value','gas','gasPrice','maxFeePerGas','maxPriorityFeePerGas','nonce']){if(raw[key]!==undefined&&raw[key]!==null)tx[key]=toHexQuantity(raw[key])}return tx}

function SwapExecutor({route,chain,sellToken,sellAmount,walletAddress,onMessage,onConfirmed,disabled}:ExecutorProps){
 const {wallets}=useWallets();const [busy,setBusy]=useState(false)
 const execute=async()=>{setBusy(true);try{
   const wallet=wallets.find(w=>w.address.toLowerCase()===walletAddress.toLowerCase())
   if(!wallet)throw new Error('Open the same verified wallet in NuBagz before swapping.')
   const provider=await wallet.getEthereumProvider();const wanted=`0x${chain.chain_id.toString(16)}`;const current=String(await provider.request({method:'eth_chainId'}))
   if(current.toLowerCase()!==wanted.toLowerCase()){
     try{await provider.request({method:'wallet_switchEthereumChain',params:[{chainId:wanted}]})}
     catch(error:any){if(error?.code!==4902||!chain.rpc_url)throw error;await provider.request({method:'wallet_addEthereumChain',params:[{chainId:wanted,chainName:chain.display_name,nativeCurrency:{name:chain.native_symbol,symbol:chain.native_symbol,decimals:18},rpcUrls:[chain.rpc_url],blockExplorerUrls:[chain.explorer]}]})}
   }
   if(route.requires_approval&&sellToken.address.toLowerCase()!==NATIVE&&route.allowance_target){
     let allowance=0n
     try{const raw=await provider.request({method:'eth_call',params:[{to:sellToken.address,data:allowanceData(walletAddress,route.allowance_target)},'latest']}) as string;allowance=BigInt(raw||'0x0')}catch{}
     if(allowance<BigInt(sellAmount)){
       onMessage(`Approve exactly ${formatUnits(sellAmount,sellToken.decimals)} ${sellToken.symbol} in your wallet.`)
       const approvalHash=await provider.request({method:'eth_sendTransaction',params:[{from:walletAddress,to:sellToken.address,data:approvalData(route.allowance_target,sellAmount),value:'0x0'}]}) as string
       if(approvalHash){let mined=false;for(let i=0;i<45;i++){const receipt=await provider.request({method:'eth_getTransactionReceipt',params:[approvalHash]}) as any;if(receipt){if(parseInt(receipt.status||'0x0',16)!==1)throw new Error('Token approval failed.');mined=true;break}await new Promise(r=>setTimeout(r,1200))}if(!mined)throw new Error('Token approval is still pending. Try the swap again after it confirms.')}
     }
   }
   onMessage(`Confirm the ${route.provider} swap in your wallet. NuBagz never signs for you.`)
   const txHash=await provider.request({method:'eth_sendTransaction',params:[cleanTransaction(route.transaction,walletAddress)]}) as string
   onMessage(`Swap submitted: ${shortAddress(txHash)}. Waiting for an on-chain receipt…`)
   let result:any=null
   for(let i=0;i<50;i++){try{result=await api('/swaps/confirm',{method:'POST',body:JSON.stringify({session_id:route.session_id,tx_hash:txHash})});if(result?.status!=='SUBMITTED')break}catch(error:any){if(i>4)throw error}await new Promise(r=>setTimeout(r,1400))}
   onConfirmed(result||{status:'SUBMITTED',tx_hash:txHash});onMessage(result?.confirmed?'Swap confirmed on-chain. The receipt below is based on the exact real transaction.':'Swap submitted. Confirmation will appear in your history once mined.')
 }catch(error:any){onMessage(error?.message||'Swap execution failed or was cancelled.')}finally{setBusy(false)}}
 return <button className="btn primary full" disabled={busy||disabled} onClick={()=>void execute()}>{busy?'Waiting for wallet…':<><Wallet/> Swap with {route.provider}</>}</button>
}

function TokenPicker({label,chain,value,onChange}:{label:string;chain:Chain;value:Token;onChange:(token:Token)=>void}){
 const [open,setOpen]=useState(false);const [q,setQ]=useState('');const [rows,setRows]=useState<Token[]>(chain.tokens||[]);const [loading,setLoading]=useState(false)
 useEffect(()=>{setRows(chain.tokens||[]);setQ('')},[chain.key])
 useEffect(()=>{if(!open||!q.trim()){setRows(chain.tokens||[]);return}const timer=setTimeout(()=>{setLoading(true);api<Token[]>(`/swaps/token-search?chain=${encodeURIComponent(chain.name)}&q=${encodeURIComponent(q.trim())}`).then(setRows).catch(()=>setRows([])).finally(()=>setLoading(false))},250);return()=>clearTimeout(timer)},[q,open,chain])
 return <div className="swap-token-field"><span>{label}</span><button type="button" className="token-select" onClick={()=>setOpen(v=>!v)}><b>{value.symbol}</b><small>{value.kind==='native'?chain.display_name:shortAddress(value.address)}</small><ArrowDown/></button>{open&&<div className="token-menu"><div className="token-search"><Search/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Search symbol or paste 0x contract"/></div>{loading&&<small>Reading token metadata…</small>}{rows.map(token=><button type="button" key={token.address.toLowerCase()} onClick={()=>{onChange(token);setOpen(false);setQ('')}}><div><strong>{token.symbol}</strong><span>{token.name}</span></div><small>{token.kind==='native'?'Native':shortAddress(token.address)}{token.metadata_estimated?' • metadata estimated':''}</small></button>)}{!loading&&!rows.length&&<div className="token-empty">No token found on this chain.</div>}</div>}</div>
}

export default function Swaps(){
 const [config,setConfig]=useState<Config|null>(null);const [chainKey,setChainKey]=useState('robinhood');const [sell,setSell]=useState<Token|null>(null);const [buy,setBuy]=useState<Token|null>(null);const [amount,setAmount]=useState('0.1');const [slippage,setSlippage]=useState(100);const [quote,setQuote]=useState<QuoteResponse|null>(null);const [selected,setSelected]=useState(0);const [market,setMarket]=useState<Market|null>(null);const [history,setHistory]=useState<HistoryRow[]>([]);const [msg,setMsg]=useState('');const [quoting,setQuoting]=useState(false)
 const loadHistory=()=>api<HistoryRow[]>('/swaps/history').then(setHistory).catch(()=>setHistory([]))
 useEffect(()=>{api<Config>('/swaps/config').then(c=>{setConfig(c);const robin=c.chains.find(x=>x.key==='robinhood')||c.chains[0];setChainKey(robin.key);setSell(robin.tokens[0]);setBuy(robin.tokens.find(t=>t.symbol==='USDG')||robin.tokens[1]||robin.tokens[0])}).catch(e=>setMsg(e.message||'Could not load swap configuration'));void loadHistory()},[])
 const chain=useMemo(()=>config?.chains.find(c=>c.key===chainKey)||null,[config,chainKey])
 useEffect(()=>{if(!chain)return;setQuote(null);setSelected(0);setSell(chain.tokens[0]);setBuy(chain.tokens.find(t=>t.symbol==='USDG')||chain.tokens[1]||chain.tokens[0])},[chainKey])
 useEffect(()=>{if(!chain||!buy)return;api<Market>(`/swaps/market?chain=${encodeURIComponent(chain.name)}&token=${encodeURIComponent(buy.address)}`).then(setMarket).catch(()=>setMarket(null))},[chain,buy])
 const requestQuote=async()=>{if(!chain||!sell||!buy)return;setQuoting(true);setMsg('Racing 0x and LI.FI for executable routes…');try{const base=parseUnits(amount,sell.decimals);const out=await api<QuoteResponse>('/swaps/quote',{method:'POST',body:JSON.stringify({chain:chain.name,sell_token:sell.address,buy_token:buy.address,sell_amount:base,slippage_bps:slippage})});setQuote(out);setSelected(0);setMsg(out.routes.length>1?`Route Race complete — ${out.routes.length} executable routes compared.`:'Executable route ready.')}catch(e:any){setQuote(null);setMsg(e.message||'No executable route is currently available.')}finally{setQuoting(false)}}
 const active=quote?.routes[selected]
 const changeChain=(key:string)=>{setChainKey(key);setMsg('')}
 const received=active&&buy?formatUnits(active.buy_amount,buy.decimals):'—'
 const minReceived=active&&buy?formatUnits(active.min_buy_amount,buy.decimals):'—'
 const signals=market?.signals||[]
 return <div className="page swap-page"><div className="page-head swap-head"><div><span className="eyebrow small">NUBAGZ SWAP / ROUTE RACE</span><h1>Trade onchain. <em>Keep the keys.</em></h1><p>Robinhood Chain is first-class. NuBagz compares genuine aggregator routes, includes the disclosed platform fee in the quote, and your connected wallet signs the real transaction.</p></div><div className="swap-fee-badge"><span>NUBAGZ FEE</span><strong>{config?.fee_percent||'—'}%</strong><small>included in executable quotes</small></div></div>{msg&&<div className="form-note">{msg}</div>}
 <div className="swap-layout"><section className="panel swap-terminal"><div className="swap-network-row"><div><span>NETWORK</span><select value={chainKey} onChange={e=>changeChain(e.target.value)}>{config?.chains.map(c=><option key={c.key} value={c.key}>{c.display_name}{c.key==='robinhood'?' • PRIMARY':''}</option>)}</select></div><div className="wallet-chip"><Wallet/><span>{config?.wallet_address?shortAddress(config.wallet_address):'Verify wallet to trade'}</span></div></div>{chain&&sell&&buy&&<><div className="swap-box"><TokenPicker label="YOU PAY" chain={chain} value={sell} onChange={t=>{setSell(t);setQuote(null)}}/><input className="swap-amount" value={amount} onChange={e=>{setAmount(e.target.value);setQuote(null)}} inputMode="decimal"/><small>{sell.name} • {sell.kind==='native'?'native gas asset':sell.address}</small></div><button className="swap-flip" type="button" onClick={()=>{setSell(buy);setBuy(sell);setQuote(null)}}><ArrowLeftRight/></button><div className="swap-box receive"><TokenPicker label="YOU RECEIVE" chain={chain} value={buy} onChange={t=>{setBuy(t);setQuote(null)}}/><strong className="swap-output">{received}</strong><small>{buy.name} • {buy.kind==='native'?'native gas asset':buy.address}</small></div><div className="swap-controls"><label>Max slippage<select value={slippage} onChange={e=>{setSlippage(Number(e.target.value));setQuote(null)}}><option value={50}>0.5%</option><option value={100}>1.0%</option><option value={200}>2.0%</option><option value={300}>3.0%</option></select></label><div><span>Platform fee</span><strong>{config?.fee_percent}%</strong></div></div><button className="btn primary full route-race-btn" disabled={quoting||!config?.wallet_address||sell.address.toLowerCase()===buy.address.toLowerCase()} onClick={()=>void requestQuote()}><Route/>{quoting?'Racing routes…':'Find best executable route'}</button></>}
 {quote&&active&&buy&&sell&&chain&&<div className="route-results"><div className="route-results-head"><div><Sparkles/><span>ROUTE RACE</span></div><small>Quotes are executable, not indicative.</small></div>{quote.routes.map((r,i)=><button type="button" key={`${r.provider}-${r.session_id}`} className={`route-card ${i===selected?'selected':''}`} onClick={()=>setSelected(i)}><div><span>{r.recommended?'BEST OUTPUT':'ALTERNATIVE'}</span><strong>{r.provider}</strong><small>{r.sources?.length?r.sources.join(' → '):'aggregated liquidity'}</small></div><div><b>{formatUnits(r.buy_amount,buy.decimals)} {buy.symbol}</b><small>min {formatUnits(r.min_buy_amount,buy.decimals)}</small></div></button>)}<div className="execution-breakdown"><div><span>You pay</span><b>{amount} {sell.symbol}</b></div><div><span>Expected</span><b>{received} {buy.symbol}</b></div><div><span>Minimum received</span><b>{minReceived} {buy.symbol}</b></div><div><span>NuBagz fee</span><b>{config?.fee_percent}%</b></div><div><span>Approval</span><b>{active.requires_approval?'Exact amount only':'Not required'}</b></div><div><span>Router</span><b>{active.provider}</b></div></div>{active.requires_approval&&<div className="swap-safety-note"><ShieldCheck/><p>NuBagz requests an <strong>exact-amount approval</strong> to the spender supplied by the selected route. An existing sufficient allowance is reused; unlimited approval is not requested by NuBagz.</p></div>}{privyConfigured&&config?.wallet_address?<SwapExecutor route={active} chain={chain} sellToken={sell} sellAmount={quote.sell_amount} walletAddress={config.wallet_address} onMessage={setMsg} onConfirmed={()=>void loadHistory()}/>:<div className="swap-safety-note warning"><AlertTriangle/><p>Connect and verify your external EVM wallet through NuBagz wallet setup to execute this route.</p></div>}</div>}</section>
 <aside className="swap-side"><section className="panel market-panel"><div className="panel-head"><div><span>MARKET VIEW</span><h2>{buy?.symbol||'Token'} liquidity</h2></div>{market?.url&&<a className="mini-action" href={market.url} target="_blank" rel="noreferrer">DexScreener <ExternalLink/></a>}</div>{market?.available&&market.embed_url?<iframe title={`${buy?.symbol} DexScreener chart`} src={market.embed_url} className="dex-chart" loading="lazy"/>:<div className="market-empty"><Gauge/><strong>No DexScreener pair found</strong><p>The swap router may still find executable liquidity even when a public chart is unavailable.</p></div>}{market?.available&&<div className="market-stats"><div><span>Price</span><b>{money(market.price_usd)}</b></div><div><span>24h</span><b>{market.price_change_24h??'—'}%</b></div><div><span>Liquidity</span><b>{money(market.liquidity_usd)}</b></div><div><span>24h volume</span><b>{money(market.volume_24h_usd)}</b></div></div>}</section><section className="panel bagz-swap-check"><div className="panel-head"><div><span><ShieldCheck/> BAG Z SWAP CHECK</span><h2>Signals before signing</h2></div></div><div className="signal-list">{signals.includes('LOW_LIQUIDITY')&&<div className="warn"><AlertTriangle/><span><b>Low liquidity</b>Higher price impact and execution risk may apply.</span></div>}{signals.includes('NEW_PAIR')&&<div className="warn"><AlertTriangle/><span><b>New pair</b>This DexScreener pair is less than seven days old.</span></div>}{signals.includes('NO_BASIC_MARKET_WARNING')&&<div><CheckCircle2/><span><b>No basic market warning detected</b>This does not mean the token is safe.</span></div>}{signals.includes('NO_DEXSCREENER_PAIR')&&<div className="warn"><AlertTriangle/><span><b>No public market pair</b>Review the contract and route carefully.</span></div>}<div><ShieldCheck/><span><b>Non-custodial</b>NuBagz cannot sign or move funds without your wallet.</span></div><div><Route/><span><b>Exact route receipt</b>The backend matches sender, router destination, calldata and transaction value before accepting a receipt.</span></div></div><small>These are execution and market signals, not investment advice or a claim that any token is safe.</small></section></aside></div>
 <section className="panel swap-history"><div className="panel-head"><div><span>REAL SWAP RECEIPTS</span><h2>Confirmed wallet activity</h2></div></div>{history.length?history.map(row=><div className="activity-row" key={row.session_id}><div><span>{row.chain} • {row.provider}</span><strong>{row.status} {row.tx_hash?`• ${shortAddress(row.tx_hash)}`:''}</strong><small>Quoted output {row.quoted_buy_amount||'—'} base units{row.actual_buy_amount?` • observed ERC-20 received ${row.actual_buy_amount} base units`:''}</small></div><div className="row-actions">{row.explorer_url&&<a className="mini-action" href={row.explorer_url} target="_blank" rel="noreferrer">Block explorer <ExternalLink/></a>}</div></div>):<div className="empty-state"><ArrowLeftRight/><strong>No executed swaps yet.</strong><p>Quotes are not counted as trades. A receipt appears only after a real wallet transaction is submitted.</p></div>}</section>
 <div className="custody-note"><ShieldCheck/><p><strong>Execution boundary:</strong> {config?.execution_model||'Your connected wallet is the signer.'} Aggregator, liquidity-provider and network fees can also apply and are part of route economics.</p></div></div>
}
