import { useEffect, useState } from 'react'
import { AlertTriangle, CheckCircle2, ShieldCheck, Send, BadgeCheck, Users, Clock3, BadgeDollarSign } from 'lucide-react'
import { api } from '../lib/api'
import { useAuth } from '../context/AuthContext'
import type { Project } from '../types'

type Evidence={status:string;contract_address?:string|null;token_launch_date?:string|null;docs_url?:string|null;socials_url?:string|null;contract_source_verified?:boolean;dangerous_permissions_absent?:boolean;liquidity_verified?:boolean;holder_distribution_verified?:boolean;team_verified?:boolean;docs_verified?:boolean;socials_verified?:boolean;verification_notes?:string|null;verified_at?:string|null}
type Trust={project_id:number;name:string;symbol:string;score:number;level:string;factors:Record<string,number>;metrics:{campaigns:number;verified_funded_campaigns:number;participants:number;completions:number;completion_rate_pct:string;project_age_days:number;token_age_days:number};evidence:Evidence;score_version:string;disclaimer:string}
type AdminEvidence={project_id:number;project_name:string;evidence:Evidence}
const factorLabel=(key:string)=>({project_history:'History',verified_funding:'Funding',completion_quality:'Completion',contract_safety:'Contract',market_structure:'Market',identity_community:'Identity'}[key]||key)
const factorMax=(key:string)=>({project_history:10,verified_funding:20,completion_quality:15,contract_safety:15,market_structure:10,identity_community:10}[key]||100)

export default function TrustCenter(){
 const {user}=useAuth();const [rows,setRows]=useState<Trust[]>([]);const [projects,setProjects]=useState<Project[]>([]);const [queue,setQueue]=useState<AdminEvidence[]>([]);const [msg,setMsg]=useState('')
 const [f,setF]=useState({project_id:0,contract_address:'',token_launch_date:'',docs_url:'',socials_url:'',contract_source_verified:false,dangerous_permissions_absent:false,liquidity_verified:false,holder_distribution_verified:false,team_verified:false,docs_verified:false,socials_verified:false})
 const load=()=>{api<Trust[]>('/trust/projects').then(setRows);if(user?.role==='CREATOR')api<Project[]>('/projects/mine').then(p=>{const live=p.filter(x=>x.status==='LIVE'||x.status==='APPROVED');setProjects(live);if(!f.project_id&&live[0])setF(v=>({...v,project_id:live[0].id}))}).catch(()=>{});if(user?.role==='ADMIN')api<AdminEvidence[]>('/trust/admin/evidence').then(setQueue).catch(()=>{})}
 useEffect(()=>{load()},[user?.role])
 const submit=async(e:React.FormEvent)=>{e.preventDefault();try{await api('/trust/evidence',{method:'POST',body:JSON.stringify({...f,contract_address:f.contract_address||null,token_launch_date:f.token_launch_date||null,docs_url:f.docs_url||null,socials_url:f.socials_url||null})});setMsg('Trust evidence submitted. Self-declared claims remain separate from verified signals until NuBagz reviews the evidence.');load()}catch(e:any){setMsg(e.message||'Could not submit trust evidence')}}
 const decide=async(projectId:number,status:'VERIFIED'|'REJECTED')=>{try{await api(`/trust/admin/evidence/${projectId}/verify`,{method:'POST',body:JSON.stringify({status,notes:status==='VERIFIED'?'Evidence reviewed by NuBagz admin.':'Evidence requires correction or further proof.'})});setMsg(`Evidence ${status.toLowerCase()}.`);load()}catch(e:any){setMsg(e.message||'Could not review evidence')}}
 return <div className="page trust-page"><div className="page-head"><div><span className="eyebrow small">PROJECT TRUST</span><h1>Signals before <em>hype.</em></h1><p>Projects do not need a NuBagz endorsement to exist. Trust combines verified evidence, funding, history and participation so users can assess risk for themselves.</p></div></div>{msg&&<div className="form-note">{msg}</div>}
 <div className="custody-note trust-disclaimer"><AlertTriangle/><p><strong>Important:</strong> a NuBagz Trust Score is not an endorsement, audit, safety guarantee or investment recommendation. Crypto projects can fail or lose value even with strong signals.</p></div>
 {projects.length>0&&<form className="panel builder trust-evidence-panel" onSubmit={submit}><div className="panel-head"><div><span>PROJECT TRUST EVIDENCE</span><h2>Submit evidence for verification</h2></div><Send/></div><p>Your project can already be live. Verification only changes how evidence is represented in Project Trust; it does not constitute project approval.</p><div className="form-grid"><label>Project<select value={f.project_id} onChange={e=>setF({...f,project_id:Number(e.target.value)})}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Token launch date<input type="date" value={f.token_launch_date} onChange={e=>setF({...f,token_launch_date:e.target.value})}/></label><label>Contract address<input value={f.contract_address} onChange={e=>setF({...f,contract_address:e.target.value})} placeholder="0x…"/></label><label>Docs URL<input value={f.docs_url} onChange={e=>setF({...f,docs_url:e.target.value})} placeholder="https://…"/></label><label>Social/community URL<input value={f.socials_url} onChange={e=>setF({...f,socials_url:e.target.value})} placeholder="https://…"/></label></div><div className="chips"><label className="chip"><input type="checkbox" checked={f.contract_source_verified} onChange={e=>setF({...f,contract_source_verified:e.target.checked})}/> Contract source verified</label><label className="chip"><input type="checkbox" checked={f.dangerous_permissions_absent} onChange={e=>setF({...f,dangerous_permissions_absent:e.target.checked})}/> No dangerous permissions found</label><label className="chip"><input type="checkbox" checked={f.liquidity_verified} onChange={e=>setF({...f,liquidity_verified:e.target.checked})}/> Liquidity evidence</label><label className="chip"><input type="checkbox" checked={f.holder_distribution_verified} onChange={e=>setF({...f,holder_distribution_verified:e.target.checked})}/> Holder distribution evidence</label><label className="chip"><input type="checkbox" checked={f.team_verified} onChange={e=>setF({...f,team_verified:e.target.checked})}/> Team identity evidence</label><label className="chip"><input type="checkbox" checked={f.docs_verified} onChange={e=>setF({...f,docs_verified:e.target.checked})}/> Docs evidence</label><label className="chip"><input type="checkbox" checked={f.socials_verified} onChange={e=>setF({...f,socials_verified:e.target.checked})}/> Social/community evidence</label></div><button className="btn primary"><ShieldCheck/> Submit for verification</button></form>}
 {user?.role==='ADMIN'&&queue.some(q=>q.evidence.status==='SUBMITTED')&&<section className="panel"><div className="panel-head"><div><span>ADMIN TRUST QUEUE</span><h2>Evidence awaiting verification</h2></div><BadgeCheck/></div>{queue.filter(q=>q.evidence.status==='SUBMITTED').map(q=><div className="activity-row" key={q.project_id}><div><span>{q.evidence.contract_address||'No contract supplied'}</span><strong>{q.project_name}</strong></div><b>SUBMITTED</b><div className="row-actions"><button onClick={()=>void decide(q.project_id,'VERIFIED')}>Verify evidence</button><button onClick={()=>void decide(q.project_id,'REJECTED')}>Reject evidence</button></div></div>)}</section>}
 {rows.length>0&&<div className="trust-grid">{rows.map(r=>{const factors=[['project_history',r.factors.project_history??0],['verified_funding',r.factors.verified_funding??0],['completion_quality',r.factors.completion_quality??0],['contract_safety',r.factors.contract_safety??0],['market_structure',r.factors.market_structure??0],['identity_community',r.factors.identity_community??0]] as const;return <article className="trust-card" key={r.project_id}><div className="trust-card-head"><div className="trust-score"><strong>{r.score}</strong><span>/100</span></div><div className="trust-project-copy"><span className="trust-symbol"><ShieldCheck/> ${r.symbol}</span><h3>{r.name}</h3><small>{r.metrics.verified_funded_campaigns}/{r.metrics.campaigns} funded Bags verified</small></div><span className={`trust-level trust-level-${r.level.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`}>{r.level}</span></div><div className="trust-summary-grid"><div><BadgeDollarSign/><span>Funded Bags</span><strong>{r.metrics.verified_funded_campaigns}/{r.metrics.campaigns}</strong></div><div><Users/><span>Completions</span><strong>{r.metrics.completions}/{r.metrics.participants}</strong></div><div><Clock3/><span>Project age</span><strong>{r.metrics.project_age_days}d</strong></div></div><div className="trust-factor-grid">{factors.map(([key,value])=>{const max=factorMax(key);const pct=Math.max(0,Math.min(100,(Number(value)/max)*100));return <div className="trust-factor" key={key}><div><span>{factorLabel(key)}</span><strong>{value}<em>/{max}</em></strong></div><div className="trust-factor-bar"><i style={{width:`${pct}%`}}/></div></div>})}</div><div className="trust-card-foot"><span className={`evidence-pill evidence-${(r.evidence.status||'not-submitted').toLowerCase().replace(/_/g,'-')}`}><CheckCircle2/>{r.evidence.status.replace(/_/g,' ')}</span><span>Score model {r.score_version}</span></div></article>})}</div>}
 {!rows.length&&<div className="empty-state"><ShieldCheck/><strong>No live projects yet.</strong><p>Trust signals appear as projects enter the NuBagz ecosystem.</p></div>}</div>
}
