export type User = {
  id:number; email:string; username:string; role:string; xp:number; bag_score:number; streak_days:number;
  referral_code:string; account_state:string; wallet_address?:string|null; wallet_chain?:string|null; created_at:string;
}
export type SocialAccount = {id:number;provider:'GOOGLE'|'X'|string;provider_user_id:string;username?:string|null;email?:string|null;display_name?:string|null;profile_picture_url?:string|null;connected_at:string;last_verified_at:string}
export type WalletConnection = {id:number;address:string;chain_type:string;chain_id?:number|null;wallet_client_type:string;connector_type:string;wallet_type:string;is_primary:boolean;is_primary_interactive:boolean;verified_at?:string|null;last_connected_at:string;created_at:string}
export type PayoutAddress = {id:number;address:string;chain:string;label:string;is_primary:boolean;verification_status:string;created_at:string}
export type Project = { id:number; owner_id:number; name:string; slug:string; symbol:string; description:string; website?:string|null; chain:string; logo_url?:string|null; treasury_address?:string|null; status:string; created_at:string }
export type Mission = { id:number; title:string; description:string; mission_type:string; verification_type:string; target_url?:string|null; quiz_question?:string|null; quiz_options?:string[]|null; xp_reward:number; position:number }
export type GasPassSummary = {enabled:boolean;active?:boolean;status?:string;chain?:string;native_asset?:string;max_native_per_claim?:string;max_unique_users?:number|null;max_claims?:number;max_claims_per_wallet?:number;starts_at?:string|null;ends_at?:string|null}
export type Challenge = {id:number;campaign_id:number;title:string;description:string;category:string;provider?:string|null;action?:string|null;verification_type:string;target_url?:string|null;target_id?:string|null;config:Record<string,unknown>;xp_reward:number;position:number;status:string;created_at:string}
export type ChallengeFeed = {id:number;campaign_id:number;campaign_title:string;project_id:number;project_name:string;project_symbol:string;title:string;description:string;category:string;provider?:string|null;action?:string|null;verification_type:string;target_url?:string|null;target_id?:string|null;config:Record<string,unknown>;proof_code?:string|null;xp_reward:number;position:number;reward_asset:string;user_reward:string;starts_at?:string|null;ends_at?:string|null;completion_status?:string|null;gas_pass?:GasPassSummary|null}
export type Campaign = { id:number; project_id:number; title:string; description:string; category:string; difficulty:string; reward_asset:string; funding_type:string; token_allocation:string; gross_reward_per_user:string; user_share_pct:string; nubagz_share_pct:string; referral_share_pct:string; max_users:number; status:string; featured:boolean; estimated_value_gbp?:string|null; created_at:string; missions:Mission[]; challenges:Challenge[]; project?:Project|null; enrolled_count:number; completed_count:number }
export type Dashboard = { lifetime_assets:number; active_bagz:number; completed_bagz:number; xp:number; bag_score:number; streak_days:number; balances:{asset_symbol:string;amount:string}[]; recent_activity:{asset:string;amount:string;type:string;status:string;note?:string;created_at:string}[] }
